### ISSUE TITLE
Need to support specifying custom logger in AssemblyQualifiedName format

### ISSUE THREAD

**Issue by DukeNuken** [paypal/PayPal-NET-SDK#102]
Hello. 

I am tring to make my own logger based on BaseLogger abstract class. 
In your SDK code I see strange logic in class LogConfiguration.cs it use privat splitters by simbol ',' and it makes a problem, because when I try put in web.config AssemblyQualifiedName to my own class it doesnt work. AssemblyQualifiedName usualy looks like that 

"PayPalLogger"="PayPal.Sample.Core.PayPalTest, PayPal.Sample, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null"

Like you see it have coma (simbol ',') and without it namespace cant be loaded by code Log/Loggers.cs
Type loggerType = Type.GetType(loggerName);

So or there are a bug with it because simbol ',' cant be splitter for Assembly full name and you should use some other simbol like '|' or please show me how to load class from other assembly.

Duke

**Comment by jziaja** [comment]
Hi @DukeNuken , thanks for reporting this!  It does look like the current logger format is not designed to handle `AssemblyQualifiedName` formats.  I'll need to play around with this a bit to see if specifying a qualified assembly name is at all possible in the current setup without breaking compatibility with existing users.

**Comment by jziaja** [comment]
**v1.5.0-beta** has been published ([GitHub](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.5.0-beta) | [NuGet](https://www.nuget.org/packages/PayPal/1.5.0-beta)) that includes support for a new `<appSettings>` key called `PayPalLogger.Delimiter`.  This key will override the delimiter used to parse the `PayPalLogger` string (the default will continue to be `,` for backwards compatibility).  Can you verify if this resolves your issue?

Here's what your config's `<appSettings>` section will need to look like when overriding the delimiter:

````xml
<appSettings>
  <add key="PayPalLogger" value="PayPal.Sample.Core.PayPalTest | PayPal.Sample, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null"/>
  <add key="PayPalLogger.Delimiter" value="|" />
</appSettings>
````

Thanks!

**Comment by jziaja** [comment]
[Version 1.5.0](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.5.0) is now published and includes this fix.
