### ISSUE TITLE
How to implement custom logger based on BaseLogger?

### ISSUE THREAD

**Issue by harumburum** [paypal/PayPal-NET-SDK#103]
I'm trying to implement custom logger in .net sdk sample project (PayPal.SDK.Sample.VS.2013) 

```
namespace PayPal.Sample
{
    public class PayPalLogger  :Log.BaseLogger
    {
```
Here is my config

```
  <appSettings>
    <!-- Diagnostics logging is only available in a Full Trust environment. -->
    <!--<add key="PayPalLogger" value="PayPal.Log.DiagnosticsLogger, PayPal.Log.Log4netLogger"/>-->
    <add key="PayPalLogger" value="PayPal.Sample.PayPalLogger"/>
  </appSettings>
```

I fount that it is not working because in the PayPal.Log.Logger constructor method loggerType is always null

```
  private Logger(Type givenType)
        {
            baseLoggerList = new List<BaseLogger>();

            if (LogConfiguration.LoggerListInConfiguration != null)
            {
                foreach (string loggerName in LogConfiguration.LoggerListInConfiguration)
                {
                    Type loggerType = Type.GetType(loggerName); // null when logger name is PayPal.Sample.PayPalLogger
```

I've tried to specify qualified assembly name in the config parameter 
```
 <add key="PayPalLogger" value="PayPal.Sample.PayPalLogger, PayPal.Sample, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null"/>
```
but it still not words, because PayPal.Log.LogConfiguration splitting config value by commas.

Could you please provide any solution for it?

**Comment by jziaja** [comment]
Hi @harumburum, thanks for reporting this!  I'm currently looking into the qualified assembly name issue with custom loggers in Issue #102.  Was the customer logger working for you in a previous release?

**Comment by harumburum** [comment]
Hi @jziaja, I didn't use sdk before, looks like me and my colleague have posted same question in
#102, so I'm closing this one, thx.
