### ISSUE TITLE
Is there an example for PayPal Express and recurring payments?

### ISSUE THREAD

**Issue by biapar** [paypal/PayPal-NET-SDK#107]
Is there an example for PayPal Express and recurring payments? ( Italy market )

**Comment by jziaja** [comment]
Hi @biapar, the [samples project](https://github.com/paypal/PayPal-NET-SDK/tree/develop/Samples) in this repo contains samples for both the Payments API (equivalent to Express Checkout) and the Subscription API (equivalent to recurring payments).  For a more detailed explanation of each API, I'd also recommend checking out the documentation on [PayPal Developer](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/).
