### ISSUE TITLE
Shipping address override

### ISSUE THREAD

**Issue by baroale** [paypal/PayPal-NET-SDK#109]
Hello, I have used your SDK to integrate an e-Commerce site with PayPal and I am having an issue which I can not solve.

I get a 400 error when trying to create a payment overriding the address (`shipping_address` in `item_list`) telling me that many fields of the `ShippingAddress` class are not accepted by the API in this type of requests (`default_address`, `preferred_address`, `status` and `id` to be precise). Of course I am passing them as null, but the `ShippingAddress` class has them, and there is no way of avoiding that.

Input fields in my experience profile:

`input_fields = new InputFields`
               ` {`
                   ` address_override = 1,`
                 `  allow_note = false,`
                  `  no_shipping = 2` 
              `  }`

**Comment by jziaja** [comment]
Hi @baroale, would you mind sharing your code for setting up the item's `ShippingAdress` prior to creating the payment?  Thanks!

**Comment by baroale** [comment]
No problem. `FlowAddress` is the model we use in our system for addresses. `ShippingAddress` is your address. 

I use automapper for getting your model:

`Mapper.CreateMap<FlowAddress, ShippingAddress>()`
                 `.ConstructUsing(src => new ShippingAddress`
                  `{`
                      `line1 = src.Line1,`
                      `line2 = src.Line2,`
                      `city = string.IsNullOrEmpty(src.PostTown) ? src.Line3 : src.PostTown,`
                      `state = string.IsNullOrEmpty(src.PostTown) == false ? src.Line3 : string.Empty,`
                      `postal_code = src.PostCode,`
                      `country_code = src.Country.Iso2CountryCode,`
                      phone = src.Phone,
                      `recipient_name = src.FullName()`
                  `});`

Then in the payment's transaction I do:

`var paypalTransaction = new Transaction`
           ` {`
               ` amount = new Amount`
            `    {`
                  `  currency = "GBP",`
                   ` total = orderTotal,`
                   ` details = new Details`
                 `   {`
                      `  tax = tax.ToString("n2"),`
                     `   shipping = shipping.ToString("n2"),`
                       ` subtotal = subtotal.ToString("n2")`
                 `   }`
              ` },`
              `  custom = order.Id.ToString(CultureInfo.InvariantCulture),`
              `  description = string.Format("E-Commerce order no. {0} from {1}", orderId, GlobalConfig.Site),`
             `   invoice_number = "BAU" + order.Id.ToString(CultureInfo.InvariantCulture),`
               ` item_list = new ItemList`
               ` {`
                `    items = order.OrderLines.Select(ol => new Item`
                  `  {`
                  `      name = ol.ProductVariant.FullName(),`
                   `     description = string.Empty,`
                    `    quantity = ol.Quantity.ToString(CultureInfo.InvariantCulture),`
                      `  price = Math.Round(ol.GetUnitPriceExcludingVat(),2).ToString("n2"),`
                    `    currency = "GBP",`
                     `   sku = ol.ProductVariant.Id.ToString(CultureInfo.InvariantCulture)`
                 `   }).ToList(),`
                 `   shipping_address = AutoMapper.Mapper.Map<ShippingAddress>(order.DeliveryAddress)`
              `  }`
        `    };`

**Comment by baroale** [comment]
I am attaching the error I get:

`{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].item_list.shipping_address.id","issue":"This field name is not defined for this resource type"},{"field":"transactions[0].item_list.shipping_address.default_address","issue":"This field name is not defined for this resource type"},{"field":"transactions[0].item_list.shipping_address.status","issue":"This field name is not defined for this resource type"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"3450afb7c1607"}`

**Comment by jziaja** [comment]
Thanks @baroale.  The code is setup to not serialize those fields if they're set to null.  Can you confirm whether or not AutoMapper is setting those fields to null?  Also, are you able to capture the outgoing request body to see what those fields are being set to?  You can inspect what the outgoing request body looks like by either enabling logging or by inspecting `PayPalResource.LastRequestDetails.Value` after you make the payment call.

**Comment by baroale** [comment]
Hello @jziaja , it looks like automapper was setting some fields wrong. In fact, if I create the ShippingAddress object by myself everything works fine. Anyway, when I pass the shipping address I want to set for the transaction, paypal does not give it to me as the default option when I get redirected to paypal.com. Instead I see the first confirmed address in my test user account. Do I need to set its Status as "CONFIRMED" in order to see it as my selected delivery address when I get redirected?

**Comment by jziaja** [comment]
@baroale are you testing against live or sandbox?  I just tried this with the sample project on sandbox using using an experience profile similar to how you have yours setup, and I see the shipping address I provide when authorizing the payment on the PayPal site:

![image](https://cloud.githubusercontent.com/assets/8227966/8806174/02d5c8bc-2f9b-11e5-9b39-79e1607a6414.png)

**Test experience profile:**
````csharp
var profile = new WebProfile
{
    name = Guid.NewGuid().ToString(),
    presentation = new Presentation
    {
        brand_name = "PayPal .NET SDK",
        locale_code = "US",
        logo_image = "https://raw.githubusercontent.com/wiki/paypal/PayPal-NET-SDK/images/homepage.jpg"
    },
    input_fields = new InputFields
    {
        address_override = 1,
        allow_note = false,
        no_shipping = 2
    }
};
````

**Test payment:**
````csharp
var payment = new Payment
{
    intent = "sale",
    experience_profile_id = createdProfile.id,
    payer = new Payer
    {
        payment_method = "paypal"
    },
    transactions = new List<Transaction>
{
    new Transaction
    {
        description = "Ticket information.",
        item_list = new ItemList
        {
            items = new List<Item>
            {
                new Item
                {
                    name = "Concert ticket",
                    currency = "USD",
                    price = "20.00",
                    quantity = "2",
                    sku = "ticket_sku"
                }
            },
            shipping_address = new ShippingAddress
            {
                line1 = "7700 TEST TEST TEST",
                line2 = "",
                city = "Austin",
                state = "TX",
                country_code = "US",
                postal_code = "78729",
                recipient_name = "Joe"
            }
        },
        amount = new Amount
        {
            currency = "USD",
            total = "45.00",
            details = new Details
            {
                tax = "5.00",
                subtotal = "40.00"
            }
        }
    }
},
    redirect_urls = new RedirectUrls
    {
        return_url = baseURI + "&return=true",
        cancel_url = baseURI + "&cancel=true"
    }
};
````

**Comment by baroale** [comment]
Hello, ?I was finally able to make it work using the sandbox. Thank you very much for your help and time @jziaja 
The whole problem was originated by Automapper and NHibernate. First of all, automapper was setting weird values to fields I was not intending to set in the ShippingAddress class, and second, NHibernate not flushing the session when I selected the address.
The API is completely fine.
Sorry for the inconvenience.
