### ISSUE TITLE
Please update reference to Newtonsoft.Json to 7.0

### ISSUE THREAD

**Issue by GuilMagalhaes** [paypal/PayPal-NET-SDK#110]
The current reference is not up to date with the latest release version of Newtonsoft.Json; causing assembly linking to break.

To avoid users having to manually add assembly binding rules, please update the reference to the latest Newtonsoft.Json release.

**Comment by jziaja** [comment]
Thanks for pointing this out @GuilMagalhaes.  I'll see if I can the dependency updated in the next release.
