### ISSUE TITLE
Payment Patch Request Issue

### ISSUE THREAD

**Issue by urbietav** [paypal/PayPal-NET-SDK#111]
The PayPal.Api.Payment.Update for  a payment patch request always returns exception "The remote server returned an error: (400) Bad Request" and the response payment patch request message "Payment_State_Invalid". I tested a billing plan patch with now issues but no success on the Payment Patch Request.

**Comment by jziaja** [comment]
@urbietav can you share the details of the patch request you're making as well as the initial state of the payment resource?  Can you share the full body of the error response you're receiving?  Thanks!

**Comment by jaypatel512** [comment]
Hey @urbietav ! 

It seems like you are trying to update the payment once it is completed/executed. Can you please confirm that ?

**Comment by urbietav** [comment]
The payment status is "created" and not executed yet. From my understanding, you are allow to make a payment patch request for "created" status. The request and response are below. I replaced payment id & Bearer for "x"s.
=============================================================================
Request:
{PayPal.Api.RequestDetails}
Body: "[{\"op\":\"replace\",\"path\":\"/transactions/0/amount\",\"value\":{\"currency\":\"USD\",\"total\":\"14.62\",\"details\":{\"subtotal\":\"6.99\",\"shipping\":\"7.11\",\"tax\":\"0.52\"}}}]"
Headers: {Content-Type: application/json
User-Agent: PayPalSDK/PayPal-NET-SDK 1.5.0 (lang=DOTNET;v=4.5;clr=4.0.30319.18444;bit=64;os=Microsoft Windows NT 6.1.7601 Service Pack 1)
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PayPal-Request-Id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Host: api.sandbox.paypal.com
Content-Length: 154

}
Method: "PATCH"
RetryAttempts: 0
Url: "https://api.sandbox.paypal.com/v1/payments/payment/PAY-xxxxxxxxxxxxxxxxxxxxxxxx"

=============================================================================
Response
{PayPal.Api.ResponseDetails}
Body: ""
Exception: {"The remote server returned an error: (400) Bad Request."}
Headers: {PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=63908
Paypal-Debug-Id: 42aeee67be9a3
CORRELATION-ID: 42aeee67be9a3
Content-Language: *
Connection: close,close
Content-Length: 235
Date: Tue, 04 Aug 2015 16:07:25 GMT
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D1038336085; domain=.paypal.com; path=/; Secure; HttpOnly,X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Server: Apache
Vary: Authorization
Content-Type: application/json

}
StatusCode: BadRequest

**Comment by urbietav** [comment]
Sorry somehow the text was got bold. My apologies

**Comment by jaypatel512** [comment]
My first observation:

You should be using PatchObject instead of requestDetails. Not sure if you are from the logs, but if not, here is a tiny sample, on how to do this in billing. You just need to implement similar in payments : 
https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/BillingPlanUpdate.aspx.cs#L29

**Comment by urbietav** [comment]
I actually did take a look the billing plan update sample and followed it but for the payment. The objects I am using for the request are below. The request output and the response details I provided are the outcome of the below.

PayPal.Api.Payment pmt = PayPal.Api.Payment.Get(apiContext, paymentId);

PayPal.Api.PatchRequest payReq = new PayPal.Api.PatchRequest();
PayPal.Api.Details pmtDetails = new PayPal.Api.Details();
PayPal.Api.Amount amount = new PayPal.Api.Amount();
PayPal.Api.Patch patch = new PayPal.Api.Patch();

payReq.Add(patch); 

pmt.Update(apiContext, payReq);

**Comment by urbietav** [comment]
here are some other details on how the objects is created:

pmtDetails.subtotal = string.Format("{0:0.00}", cart.SubTotal);
pmtDetails.shipping = string.Format("{0:0.00}", cart.Shipping );
pmtDetails.tax = string.Format("{0:0.00}", cart.Tax);

PayPal.Api.Amount amount = new PayPal.Api.Amount() { currency = "USD", total = string.Format("{0:0.00}", cart.Total), details = pmtDetails};

 PayPal.Api.Patch patch = new PayPal.Api.Patch() { op = "replace" , path = "/transactions/0/amount", value = amount };

**Comment by jaypatel512** [comment]
That is wondeful. This really helps understand better. I am trying to see if I could reproduce the issue in our local machine, and see if I can point out the issue.

**Comment by jaypatel512** [comment]
I have asked the internal team about this, as I am not able to get the reason why it is failing for you. I will get back to you as soon as I hear back from them. It should be quick.

**Comment by jaypatel512** [comment]
Hey @urbietav !

Just making sure here. When you create the above payment, has the user already completed the UI flow approval process ? and you are trying to change the values before executing ? 

The update payment is only allowed when you create the payment, and is not approved by customer. Once the consumer completes the approval process, you are not allowed to update the payment.

**Comment by urbietav** [comment]
That is correct. I am using the approval HATEOAS link to direct user to paypal. The flow I am seeking is User is directed to paypal for checkout >> returns to a review page where the tax + shipping is added based on the paypal shipping address >> User confirms and click Pay (this is the Update) >> user is redirected to a conformation page. Is this possible and I am using the wrong HATEOAS link ?

**Comment by jaypatel512** [comment]
Oh ! In that case, you need to use a different way of doing this. Updating the payment is not the way. The execute object allows you to pass the transaction object where only amount object could be set to different value.

You can read more about it here: https://developer.paypal.com/webapps/developer/docs/api/#execute-an-approved-paypal-payment

Here is the snippet of it.

![screen shot 2015-08-12 at 4 29 40 pm](https://cloud.githubusercontent.com/assets/1309895/9237215/5e503c7e-410f-11e5-9182-73c55ffb0876.png)

Here is how the execution object should look like:

```
{
    "payer_id": "REABK2UGK7PLW",
    "transactions": [
        {
            "amount": {
                "currency": "USD",
                "total": "21",
                "details": {
                    "shipping": "2.20",
                    "tax": "1.30",
                    "subtotal": "17.50"
                }
            }
        }
    ]
}
```

**Comment by urbietav** [comment]
Oh, I see. I will try this way and see if it works out. Thanks
