### ISSUE TITLE
how to fetch all transaction ID from paypal in asp.net c#???

### ISSUE THREAD

**Issue by projectscollection** [paypal/PayPal-NET-SDK#118]
Hi There

i want to get all transaction id from paypal in asp.net c#.

Please Help,
Thanks

**Comment by pp-randy** [comment]
Are the transactions going to be created using the REST API (or this SDK only)?  If not, I would point you to a transaction search of the Classic API.

**Comment by projectscollection** [comment]
i have paypal merchant account and my paypal account have lot of transaction in it, i just want to get all transactions id from my paypal merchant account using ap.net c#...is it any way to get transactions ids from paypal merchant account if yes then please let me know.

Thanks,

**Comment by jziaja** [comment]
@projectscollection , [`PayPal.Api.Payment.List()`](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Payment.cs#L227) should get you what you need.  

See also: [PayPal REST API Reference - List payment resources](https://developer.paypal.com/docs/api/#list-payment-resources).

**Comment by projectscollection** [comment]
Thank you so much.

**Comment by jibboo** [comment]
PayPal.Api.Payment.List() returns 0 results for me.  Got any other ideas?

**Comment by xiaoleih41** [comment]
@jibboo Please create a new issue with your detail issue sandbox or live and a `debugId` as well as any error message you might have received. I will lock this conversation as the original issue was resolved.
