### ISSUE TITLE
Express checkout with REST api

### ISSUE THREAD

**Issue by DukeNuken** [paypal/PayPal-NET-SDK#119]
I dont get the idea. If Classic api have DoExpressCheckout methods... what Rest API have for it?
On that image we have the way how it should work for classic way
![ec_hooks 1](https://cloud.githubusercontent.com/assets/2789880/10198021/cec04ae4-67a2-11e5-9620-2aeb21daf2e0.gif)

So for my case Express Checkout steps are:
1) Customer put items in cart and click on PayPal checkout button
I run 
         var payment = new PayPal.Api.Payment();
         var createdPayment = payment.Create(apiContext);

so make the payment and redirect customer to paypal site

2) Customer go thu the paypal process and return back to my site. From his pay pal transaction I should get Shipment address and his email (without submit that payment!) and based on his shipment address calculate shipment cost 

3) After customer select shipment method I need update his transaction (add shipment cost) and only then sumbit it.

So the questions here
1) how to get payment (transaction) info with C# lib based on paymentId (like PAY-21A17783AU475540MKYGAM5Q) because PayPal.Api.Payment() have methods only Creare, Execute and Update?
2) How to Update current transaction (add some new data like shipment cost) and then submit it?

PS. In the documents a lot of mess and a lot of people dont understand how they should use that api properly.

Duke

**Comment by jziaja** [comment]
Hi @DukeNuken, the Express Checkout functionality is available via [REST Payments API](https://developer.paypal.com/docs/integration/web/accept-paypal-payment/).  To help you get started, I'd recommend using [the samples available here in this repo](https://github.com/paypal/PayPal-NET-SDK/wiki/Samples).  They should give you a good overview of how the API calls work.

Regarding your questions:

> 1) how to get payment (transaction) info with C# lib based on paymentId (like PAY-21A17783AU475540MKYGAM5Q) because PayPal.Api.Payment() have methods only Creare, Execute and Update?

If you have a `paymentId`, then you'll want to use [`PayPal.Api.Payment.Get()`](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Payment.cs#L139) to retrieve the payment details.  Also, this payment resource is **not** the transaction.  The transaction details (including any associated transaction IDs) will be included in the payment resource under its `related_resources` property.  For example, if you create a payment with `intent` set to `sale`, then the created payment resource will contain a `sale` object in its `related_resource` list.  The transaction ID that appears in your merchant dashboard will map to the `sale.id` property.  You can also use [`PayPal.Api.Sale.Get()`](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Sale.cs#L140) with the `sale.id` to get just the sale transaction details.

> 2) How to Update current transaction (add some new data like shipment cost) and then submit it?

When you execute the payment, the provided `PaymentExecution` object includes a `transactions` property where you can specify the tax and/or shipping cost associated with the payment.  You will also need to provide an updated `amount.total`.

If you run the [**Make a payment with a PayPal account**](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentWithPayPal.aspx.cs) sample, you can test this out by doing the following:

1. Remove or comment out [lines 65 & 66](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentWithPayPal.aspx.cs#L65) where `tax` and `shipping` are set prior to creating the payment.

1. Add the following code after [line 146](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentWithPayPal.aspx.cs#L146), which will set the `tax` and `shipping` after the payment has been approved by the buyer:

    ```csharp
    paymentExecution.transactions = new List<Transaction>
    {
        new Transaction
        {
            amount = new Amount
            {
                total = "100",
                currency = "USD",
                details = new Details
                {
                    tax = "15",
                    shipping = "10",
                    subtotal = "75"
                }
            }
        }
    };
    ```

Hope that helps! :+1:
