### ISSUE TITLE
Create payment on Sandbox, getting wrong links back

### ISSUE THREAD

**Issue by dlalex83** [paypal/PayPal-NET-SDK#121]
Hi there,

I'm using the 1.5 version of the SDK and I've always been able to successfully using the sandbox mode for testing. Since this afternoon the create payment API (creating them with authorize intent) in sandbox mode gives me a response with the wrong links, more specifically:

1. GET, SELF, https://127.0.0.1/v1/payments/payment/PAY-3J041487P5058351GKYHKEDQ
2. REDIRECT, AUTHORIZE, https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-2W7266730F1412848
3. POST, EXECUTE, https://127.0.0.1/v1/payments/payment/PAY-3J041487P5058351GKYHKEDQ/execute

I've always got back the sandbox links for the 3 of them whilst now, as you can see, 2 of them point to localhost and one (the one that I actually need to authorize the payment) points to Live paypal.

Anyone else getting this ? Could it be just a temporary problem with the sandbox environment? or could it depend on the SDK?

Thanks in advance

Alex

**Comment by wisconsinjim** [comment]
I just came here to report the very same symptoms; the authorize link goes the regular Paypal site and the other two to localhost. 

I was able to double check this against a test instance that I deployed yesterday morning and confirmed it was working correctly at the time. The instance has not been changed and is now showing the same issue.

Presumably a problem on Paypal's end. Hopefully a fix will be coming shortly.

**Comment by pp-randy** [comment]
I will look into this, it is reproducible outside of the SDK as well.

**Comment by dlalex83** [comment]
Great, thanks. I guess we'll wait for PayPal to fix it.

**Comment by jziaja** [comment]
Related:
* https://github.com/paypal/PayPal-PHP-SDK/issues/409
* https://github.com/paypal/PayPal-node-SDK/issues/111

**Comment by jaypatel512** [comment]
The fix has been released, and now it should be back to normal. Closing the issue.
