### ISSUE TITLE
when i am fetching paymentList it gave me count 0??

### ISSUE THREAD

**Issue by projectscollection** [paypal/PayPal-NET-SDK#122]
when i am fetching paymentList it gave me count 0 ?? whereas in '2015-09-22' i have nine payments.
In webconfig i gave my own sandbox clientId and clientSecret.
Can you please tell me, why paymentList return count 0???
In addition
when i use clientId and clientSecret. of Paypal.sdk.sample app it return some result, but when i provided my own clientId and clientSecret it return nothing.

![pic](https://cloud.githubusercontent.com/assets/12823791/10254538/3e22d72e-68f9-11e5-9c5f-5cf7cf80e3d4.jpg)

**Comment by jziaja** [comment]
Hi @projectscollection, instead of `startDate` and `endDate`, can you try the call again using `startTime` and `endTime` with the following datetime format:

```csharp
var paymentHistory = Payment.List(apiContext, startTime: "2015-09-22T00:00:00Z", endTime: "2015-09-22T23:59:59Z");
```

Also, if you do a search without any date specified, do you get back any payment resources?

I'm going to classify this as an SDK bug since `startDate` and `endDate` do not appear to be [valid search fields](https://developer.paypal.com/docs/api/#paging--filtering) in context of `Payment.List()`.

**Comment by projectscollection** [comment]
when i do search without date specified it also return nothing mention below.
![pic1](https://cloud.githubusercontent.com/assets/12823791/10283189/63350f28-6b33-11e5-8061-8521cd2f82b1.png)

and

When i do serach as startTime and EndTime it also return nothing.
![pic3](https://cloud.githubusercontent.com/assets/12823791/10283218/83a16d42-6b33-11e5-8996-30452190761d.jpg)

**Comment by jziaja** [comment]
Is this on live or sandbox?  Are you certain the REST app you're using should have REST payment transactions associated with it?  If yes, [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) should be able to help you figure out why your transactions aren't showing up.

**Comment by projectscollection** [comment]
My only purpose is to fetch all transaction ids from my paypal sandbox account.
Please see my transaction mention in pictures, i want to fetch transaction ids form these transaction.

![transaction](https://cloud.githubusercontent.com/assets/12823791/10283501/b787e2ca-6b34-11e5-9c89-83dce150743e.jpg)

**Comment by jziaja** [comment]
Were those transactions created via REST or Classic API calls?

**Comment by projectscollection** [comment]
i'm new in Paypal, i just use this NVPAPICaller to created these transaction.

**Comment by jziaja** [comment]
Unfortunately, that means these transactions were all created via the Classic API and are not retrievable using the REST API.  You'll either need to switch to create the payments using the REST API (which is what [`Payment.Create()`](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Payment.cs#L121) will do if you use this SDK), or you can use other Classic API calls like [TransactionSearch](https://developer.paypal.com/docs/classic/api/merchant/TransactionSearch_API_Operation_NVP/) to search for transactions created using Classic API calls.

**Comment by projectscollection** [comment]
Thank you so much, now i get my transaction through TransactionSearch.
Again 
Thank you :-)

**Comment by jziaja** [comment]
No problem! :+1: 

I'll close this out once I've removed those parameters from the `Payment.List()` call in this SDK.

**Comment by projectscollection** [comment]
No problem!

**Comment by jaypatel512** [comment]
For future reference, we are not going to fix this bug in our 1.x SDK, as there is no way for us to do that without making a breaking change. Simply ignoring those fields is not a very good fix either, neither is throwing an exception back.

We will definitely be fixing this in 2.x of our SDK. Closing this issue.
