### ISSUE TITLE
Simple VB.Net Example of CC payment?

### ISSUE THREAD

**Issue by SynerSoft** [paypal/PayPal-NET-SDK#124]
Sorry if this is not the right place to ask a question..

I'm looking for a _simple_ vb.net example of submitting a payment.  Couldn't find one anywhere.  Surely a payment can be submitted with an object and 10 or so properties?  

I don't mind starting with hard coded credentials, once it is working I know how to move that stuff.

Regards,

-Jay

**Comment by ppmtscory** [comment]
@SynerSoft unfortunately we don't have any VB.Net samples on our developer portal.  You can use the [curl sample](https://developer.paypal.com/docs/rest/api/payments/#payment.create) and convert it or maybe check StackOverflow to see if other developers have already accomplished this.
