### ISSUE TITLE
Direct Payment with American Express and Discover 

### ISSUE THREAD

**Issue by kravchukalexander** [paypal/PayPal-NET-SDK#126]
I'm using version 1.5.0 to handle payments with PayPal.
For test purposes I use credit card numbers from http://www.getcreditcardnumbers.com/ and it works perfect with Visa and MasterCard. When I'm trying to use American Express or Discover cards I'm getting an error.

Here is my request to paypal:

{
	"body": {
		"intent": "authorize",
		"payer": {
			"payment_method": "credit_card",
			"funding_instruments": [
				{
					"credit_card": {
						"first_name": "retest1",
						"billing_address": {
							"city": "Toronto",
							"state": "ON",
							"postal_code": "M5V 1M1",
							"line1": "******",
							"country_code": "CA"
						},
						"expire_month": 11,
						"number": "xxxxxxxxxxx9164",
						"last_name": "techguils",
						"cvv2": "***",
						"expire_year": 2018,
						"type": "amex"
					}
				}
			]
		},
		"transactions": [
			{
				"invoice_number": "1340",
				"amount": {
					"currency": "USD",
					"total": "31.39",
					"details": {
						"subtotal": "25.00",
						"tax": "0.00",
						"shipping": "6.39"
					}
				},
				"description": "1340",
				"item_list": {
					"items": [
						{
							"sku": "B12",
							"currency": "USD",
							"price": "25",
							"name": "The Writings of Dr. Smedley",
							"quantity": "1"
						}
					]
				}
			}
		]
	},
	"header": {
		"x-pp-ads-performed": "false",
		"content-length": "652",
		"x-forwarded-server": "jensenhealey.ca1.paypal.com",
		"x-forwarded-host": "api.sandbox.paypal.com",
		"x-pp-silover": "name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D3960227414",
		"x-forwarded-for": "10.72.108.11",
		"paypal-request-id": "89092621-4cd7-4545-8775-9d410def08ed",
		"connection": "Keep-Alive",
		"accept": "*/*",
		"client-auth": "No cert",
		"host": "api.sandbox.paypal.com",
		"user-agent": "PayPalSDK/PayPal-NET-SDK 1.4.4 (lang\\u003dDOTNET;v\\u003d4.5.1;clr\\u003d4.0.30319.42000;bit\\u003d64;os\\u003dMicrosoft Windows NT 10.0.10240.0)",
		"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxB0WC",
		"x-pp-corrid": "869b6cb25c259",
		"pp_remote_addr": "68.232.69.42",
		"content-type": "application/json",
		"x-pp-slingshot-targetapp": "platformapiserv"
	},
	"additional_properties": {},
	"method": "POST"
}

And this is the response to this request:

{
	"status": 400,
	"duration_time": 506,
	"body": {
		"message": "An unknown error has occurred",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
		"name": "UNKNOWN_ERROR",
		"debug_id": "869b6cb25c259"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "185",
		"Content-Language": "*",
		"CORRELATION-ID": "869b6cb25c259",
		"Date": "Fri, 13 Nov 2015 16:16:43 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "869b6cb25c259",
		"PROXY_SERVER_INFO": "host\\u003dslcsbplatformapiserv3001.slc.paypal.com;threadId\\u003d2316",
		"Content-Type": "application/json"
	}
}

And once again. It works perfect for visa and master card, but fails with amex and discover.

**Comment by ppmtscory** [comment]
@kravchukalexander unfortunately only Visa and Mastercard are supported for Canadian merchants using direct credit card.  I will file an internal ticket to have a more relevant error message displayed for this particular use case.
