### ISSUE TITLE
REST Api - accessToken not being returned

### ISSUE THREAD

**Issue by GTatAeronix** [paypal/PayPal-NET-SDK#128]
Hi, not sure where to start with this.

I have had successful responses inc. full payment process in my test env. using sandbox. I have moved this to the live host to test against the sandbox but cannot get an accessToken in the very first call to paypal sandbox. OAuthTokenCredentials are good but .GetAccessToken() followed by PayPal.HttpConnection.Execute() fails with a PayPal.Exception. This returns a an exception code -2146233088. in the HResult. 

I'm using C# on VS2015. I have failed in trying to implement log4net, no logfile is being written to. 

Can you tell me the meaning of this code so I can get onto either or both PayPal or my Host(1&1).

 Message and stack trace below. If more info is needed please ask.

Regards.

https://www.geodetica.co.uk/G2v3AppTest.aspx 

PayPalEx TargetSite name: Execute
PayPalEx TargetSite declaringType: PayPal.Api.HttpConnection
PayPalEx TargetSite type: System.Reflection.RuntimeMethodInfo
PayPalEx Source: PayPal
PayPalEx HResult: -2146233088

PayPalEx BaseException: 
PayPal.PayPalException: Retried 1 times.... Exception in PayPal.HttpConnection.Execute(). Check log for more details. 
at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest) 
at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader) 
at PayPal.Api.OAuthTokenCredential.GenerateOAuthToken() 
at PayPal.Api.OAuthTokenCredential.GetAccessToken() 
at ASP.g2v3apptest_aspx.__RenderContent1(HtmlTextWriter __w, Control parameterContainer) in https://www\geodetica.co.uk/G2v3AppTest.aspx   line 106

**Comment by GTatAeronix** [comment]
Further to the above:
PayPal.Api.OAuthTokenCredential.GetAccessToken() 
            // Summary:
            //     Returns the currently cached access token. If no access token was previously
            //     cached, or if the current access token is expired, then a new one is generated
            //     and returned.
            //
            // Returns:
            //     The OAuth access token to use for making PayPal requests.
            //
            // Exceptions:
            //   T:PayPal.MissingCredentialException:
            //     Thrown if clientId or clientSecret are null or empty.
            //
            //   T:PayPal.InvalidCredentialException:
            //     Thrown if there is an issue converting the credentials to a formatted authorization
            //     string.
            //
            //   T:PayPal.IdentityException:
            //     Thrown if authorization fails as a result of providing invalid credentials.
            //
            //   T:PayPal.HttpException:
            //     Thrown if authorization fails and an HTTP error response is received.
            //
            //   T:PayPal.ConnectionException:
            //     Thrown if there is an issue attempting to connect to PayPal's services.
            //
            //   T:PayPal.ConfigException:
            //     Thrown if there is an error with any informaiton provided by the PayPal.Api.ConfigManager.
            //
            //   T:PayPal.PayPalException:
            //     Thrown for any other general exception. See inner exception for further details.

I check for each of these exceptions in the page and the only one thrown Is
PayPal.PayPalException: However, the inner exception is null and there is no helplink only the HResult number

I am in week 2 of this error.
GT

**Comment by GTatAeronix** [comment]
Worked it. 

1&1 shared asp.net hosting requires a proxy server to be referenced in the web.config file in order to issue http requests. 

There would still be the case for some kind of exception message/help link/inner exception if possible as this correction has taken too long to achieve. 

Rgds
GT

**Comment by brown11188** [comment]
So could we keep the proxy enable and still get access token?

**Comment by bluk** [comment]
Unfortunately I don't have access to an environment to test this, but in environments that limit outbound HTTP requests for security reasons, you may have to follow their suggestions. I found this [article on 1&1 shared ASP.net hosting](http://help.1and1.com/hosting-c37630/scripts-and-programming-languages-c85099/aspnet-c39624/resolving-aspnet-errors-a617716.html).

Please be sure that your credentials and other secrets are not readable by unauthorized users in a shared hosting environment.
