### ISSUE TITLE
Paypal with discount bug

### ISSUE THREAD

**Issue by DukeNuken** [paypal/PayPal-NET-SDK#130]
Hello. 

I have the problem with setup descount amount after customer return from paypal. 
Here is an real live example
1) I have one item in the cart. It cost 18.99.
2) I create the new payment with that new item 18.99, subtotal = 18.99 and amount.total = 18.99
<code>var payment = new PayPal.Api.Payment();</code>
3) Then customer go to sandbox paypal and return back to my site.
4) I need add shipment cost, tax and new total
For that i am setup new transaction with the same paymentId
```
            var paypalTransaction = new PayPal.Api.Transaction
            {
                amount = new PayPal.Api.Amount
                {
                    total = "25.50",
                    currency = "USD",
                    details = new PayPal.Api.Details
                    {
                        shipping = "4.99",
                        subtotal = "18.99",
                        tax = "1.52"
                    }
                }
            };
```
 
and it works fine and correct.
5) In case I need add discount (when customer insert coupon code like -10% on item cost). Here is the problem
When he return back from paypal I need add shipment cost, tax and new total and discount. Based on examples which I found in SDK only one way I can do it it is the trick with item which have negotive price. So code now look like that
```
            var paypalTransaction = new PayPal.Api.Transaction
                {
                    amount = new PayPal.Api.Amount
                    {
                        total = "23.60",
                        currency = "USD",
                        details = new PayPal.Api.Details
                        {
                            shipping = "4.99",
                            subtotal = "17.09",
                            tax = "1.52"
                        }
                    }
                };

                paypalTransaction.item_list = new PayPal.Api.ItemList();
                paypalTransaction.item_list.items = new List<PayPal.Api.Item>();
                paypalTransaction.item_list.items.Add(
                        new PayPal.Api.Item()
                        {
                            name = "Item1",
                            currency = "USD",
                            price = "18.99",
                            quantity = "1",
                            sku = "SC7111"
                        }
               );
                paypalTransaction.item_list.items.Add(
                        new PayPal.Api.Item()
                        {
                            name = "Discount",
                            currency = "USD",
                            price = "-1.9",
                            quantity = "1",
                            sku = "dsicount"
                        }
                );
```
When I do payment execute for this transaction it fail with error "<b>Item amount must add up to specified amount subtotal (or total if amount details not specified)</b>"

Questions here:
1) Why that REST api version still dont have Discount value in paypalTransaction.amount.details ? It is exist in old api and it is so strange add items with negative price!

2) What is woring with my emaple? Math looks correct to me.

PS. It show the same error if I am adding only discount item (without real one).
Duke

**Comment by ppmtscory** [comment]
@DukeNuken I apologize for the delay here.  Can you please let me know a recent debug ID of the error message?  This will allow me to look into our logs and see what's causing the issue.

**Comment by pbonita** [comment]
I have the same issue, cannot reflect discounts in the cart as an item. Any ideas?

**Comment by ppmtscory** [comment]
@pbonita can you provide a debug ID for us to look at please?

**Comment by pbonita** [comment]
Ok, my mistake. I see that "behind scenes" the total is calculated and checked, so literally my total was different to the one calculated "behind scenes". Anyways, I would like to know if there is a way that I can show more than one price per item, one valid (discounted price) and another invalid (initial price) for those items that are being discounted, or if I could make a coupon object that could be inserted to the cart... Thanks!

**Comment by ppmtscory** [comment]
Thank you for the update.  Unfortunately what we have available currently for discounts is all that we have.  There's no way to specify multiple prices for a single item, nor a way for a coupon object.

**Comment by OleksiiBrylin** [comment]
I have the same issue. ("debug_id": "7cc4ad31795e2").
