### ISSUE TITLE
What is the best way to retrieve the CorrelationId for a response?

### ISSUE THREAD

**Issue by Zhaph** [paypal/PayPal-NET-SDK#131]
As part of our PayPal testing and Certification we're being asked to log the Correlation or Debug Id for each call to the API:

> Every response from PayPal will return a ‘Paypal-Debug-Id’ in the headers. Please do add that value to your logs. Correlation-Id’s are required to efficiently find transactions on PayPal records. PayPal engineers will ask for this value when diagnosing any issue you may find. It is also required to complete this document

This doesn't appear to be exposed in the API, only via interrogating the thread static variable on `PayPalResource.LastResponseDetails.Value` which doesn't look like it guarantees to be the details of the request in question?

Will calling `GetHeaderMap` on a response result in the headers from the response, or only on the request?

**Comment by pp-randy** [comment]
The Paypal-Debug-Id header does not get exposed in the top-level response objects. However, the value does get added at the API level to the response body for error responses as the debug_id property.

**Comment by pp-randy** [comment]
Looking at the PaymentWithPayPal sample I don't see the headers getting exposed beyond HttpConnection.

https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentWithPayPal.aspx.cs#L113

https://github.com/paypal/PayPal-NET-SDK/blob/966510e35a997a4886bb2eeb8fad2efc9f140d64/Source/SDK/Api/Payment.cs#L128

https://github.com/paypal/PayPal-NET-SDK/blob/966510e35a997a4886bb2eeb8fad2efc9f140d64/Source/SDK/Api/PayPalResource.cs#L186

https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/HttpConnection.cs#L242

**Comment by Zhaph** [comment]
Yes, we've seen it on the error responses, but we are being asked to capture it for all requests. Would it be possible to pull that up at all?

**Comment by xjijies** [comment]
Hi @Zhaph ,
You still need help on this or shall I close this issue?

**Comment by Zhaph** [comment]
Thanks for checking in xjijies, yep you're right in that I no longer need this :)
