### ISSUE TITLE
Getting access token from refresh token

### ISSUE THREAD

**Issue by ghhtimsgh1970** [paypal/PayPal-NET-SDK#132]
I looked at [the docs to do this](https://developer.paypal.com/docs/api/#grant-token-from-refresh-token) and it seems pretty straightforward, but it's not working.

I've successfully got the onboarding process working where my I use Log In With PayPal to return an auth code and then get a refresh/access token and then use that to get the user profile information.  I'm saving the refresh token against the user to use for future access token requests.

The sample C# code you show [in your docs area](https://developer.paypal.com/docs/api/#grant-token-from-refresh-token) looks like this: (I just copy/pasted this)

```
CreateFromAuthorizationCodeParameters createFromAuthorizationCodeParameters = new CreateFromAuthorizationCodeParameters();
createFromAuthorizationCodeParameters.setCode("6Aam6hMOrHl4v7l...sv16l");
Tokeninfo tokenInfo = Tokeninfo.CreateFromAuthorizationCode(createFromAuthorizationCodeParameters);

CreateFromRefreshTokenParameters createFromRefreshTokenParameters = new CreateFromRefreshTokenParameters();

Tokeninfo refreshedTokenInfo = tokenInfo.CreateFromRefreshToken(createFromRefreshTokenParameters);
```

If you look at that carefully, you'll notice that it's referencing `CreateFromAuthorizationCodeParameters` which should be used for getting an **authorization code**, not a refresh token.

And sure enough, if I pass my saved refresh token for the user into that `setCode()` method, I get back a predictable **error message**:

```
{
    "error_description":"Invalid authorization code",
    "error":"access_denied",
    "correlation_id":"f0bbf4a1bd2b4",
    "information_link":"https://developer.paypal.com/docs/api/#errors"
}
```

I looked into using just `tokenInfo.CreateFromRefreshToken` but that appears to be an instance method on Tokeninfo class.  How can I use that without first supplying an auth code?

Is there a different example somewhere?  I don't want to manually call the REST api directly, but I'm wondering if the SDK doesn't support this?

**Comment by ghhtimsgh1970** [comment]
Not sure if my above comment is clear enough.  To put it differently, the curl version of doing this is very simple.  Looks like this:

    curl -v https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice \
          -u "<Client-Id>:<Secret>" \
          -d "grant_type=refresh_token
          &refresh_token=<Refresh-Token>"

**How is this call made using the the .NET SDK?**

From what I can gather, this would correlate to Tokeninfo.CreateFromFreshToken() but that doesn't work because it's a instance method that only works if the TokenInfo instance has already been created using the authorization code.

**Comment by ghhtimsgh1970** [comment]
I downloaded the source and debugged it out.  The `CreateFromFreshToken()` is pretty gnarly.  You may want to clean that up.

As an example, in other places, your pattern follows this:

    PayPalResource.ConfigureAndExecute<T>

So that ApiContext isn't required (it's created and configured on the fly from the config settings).  But in thise case, `CreateFromFreshToken` doesn't follow that pattern so ApiContext has to be supplied.  Without, you get a null reference exception.

This block of code will solve this issue and return a new access token from a refresh token alone:

    APIContext apiContext = new APIContext()
    {
        Config = ConfigManager.Instance.GetProperties()
    };
    
    Tokeninfo tokenInfo = new Tokeninfo()
    {
        refresh_token = linkedAccount.OAuthRefreshToken
    };
    
    Tokeninfo refreshedTokenInfo = tokenInfo.CreateFromRefreshToken(apiContext, new CreateFromRefreshTokenParameters());

Definitely change the C# samples showing in the REST api doc so that others aren't stumped on that as well.

**Comment by jziaja** [comment]
Hey @ghhtimsgh1970 I appreciate the investigation into this!  I had [a branch](https://github.com/paypal/PayPal-NET-SDK/tree/fix-lipp-support) I was working on a while back to fix  this because, as you pointed out, it is indeed a pretty gnarly section of this SDK.  While the branch is a bit outdated, it does include some improvements to the LIPP (Log In with PayPal) support (see [this commit](https://github.com/paypal/PayPal-NET-SDK/commit/ad3c08dbdfa2ae92b263678ae15145ba38d9e276)) that may help to resolve the issue you're seeing.

**Comment by ghhtimsgh1970** [comment]
Thanks, @jziaja!  That branch looks a lot better, looking at the token creation parts of it.

**Comment by sucithrashanu** [comment]
@ghhtimsgh1970 

Please Check [PayPal Community](https://www.paypal-community.com ) and  [MTS](https://paypal.com/mts )

Thanks!
