### ISSUE TITLE
REST end points for the Permissions Service?

### ISSUE THREAD

**Issue by ghhtimsgh1970** [paypal/PayPal-NET-SDK#133]
Hi, I'm looking to integrate with your [Permissions Service](https://developer.paypal.com/docs/classic/products/permissions/).

I don't see any mention of it in this SDK.  Does the .NET SDK have support for it yet?  Are there any REST end points for it?

**Comment by jziaja** [comment]
REST doesn't have support for the Classic Permissions API yet.  You'll want to use the [Classic Permissions SDK for .NET](https://github.com/paypal/permissions-sdk-dotnet).
