### ISSUE TITLE
Refund unknown error has occurred

### ISSUE THREAD

**Issue by nathan-lens** [paypal/PayPal-NET-SDK#137]
Hi,

I passed in saleId and created a refund object, when I execute the method I get unknown error

saleId = 7NK605716R8455046
 var sale = Sale.Get(ApiContext, saleId);
 return sale.Refund(ApiContext, refund);

This is happening SaleRefund.aspx

{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"ff7d8c4c1f7a1"}

**Comment by ppmtscory** [comment]
@nathan-lens the issue was due to your sandbox account, that you were refunding from, had a restriction on it.  I'm not sure why this happened but I've removed the restriction so you should be able to function as normal on that account.
