### ISSUE TITLE
Can't build solution on linux

### ISSUE THREAD

**Issue by xplicit** [paypal/PayPal-NET-SDK#141]
When I try to compile solution on linux with mono 4.2, I've got an error

      xbuild PayPal.SDK.NET45.sln 

     /usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	CSC: error CS2011: Unable to open response file: (ExternalCompile)

**Comment by pp-randy** [comment]
I do not have much experience with mono; however, after researching this it could be file permission issue.  

Does the mono process have the correct access to the ExternalCompile directory and files?

**Comment by xplicit** [comment]
Isn't ExternalCompile just msbuild directive? Where is this directory located?

What I did to avoid this error, I replaced all `<ExternalCompile>` to `<Compile>` tags from PayPal.SDK.Files.csproj and insert into PayPal.SDK.NET45.csproj then I was able to compile with small code changes.

**Comment by xplicit** [comment]
Also the solution uses MSTest for unit testing - this library requires VS installed which is not possible under linux, so I can't run unit tests and check what SDK functionality works with mono and what is not. Why not to use cross-platform NUnit or XUnit for unit testing?

**Comment by jziaja** [comment]
Hi @xplicit, unfortunately we have no plans to support building this SDK with Mono at this time.

**Comment by xplicit** [comment]
@jziaja .NET Core you do not support too?
