### ISSUE TITLE
TLS 1.2 setting eventually breaks compatibility with legacy services

### ISSUE THREAD

**Issue by andregrohmann** [paypal/PayPal-NET-SDK#142]
In https://github.com/paypal/PayPal-NET-SDK/commit/966510e35a997a4886bb2eeb8fad2efc9f140d64 ConnectionManager.cs was modified for TLS 1.2 support.
`ServicePointManager.SecurityProtocol` gets set to `SecurityProtocolType.Tls12` explicitly.
Unfortunately this setting affects the whole AppDomain. Therefore after using the PayPal .NET SDK only TLS 1.2 Connections are possible. This will eventually break compatibility to legacy services only providing a lower security protocol than TLS 1.2.

A possible fix would be to only add TLS 1.2 support if it is not already added.

```C#
if (!ServicePointManager.SecurityProtocol.HasFlag(SecurityProtocolType.Tls12))
{
    ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol | SecurityProtocolType.Tls12;
}
```
Another in my opinion better solution would be to delegate this setting to the application using the PayPal .NET SDK. You could throw an Exception when someone tries to use the SDK without the TLS 1.2 flag. Therefore an API consumer gets aware of this required settings change an can think about possible side effects.

It would be really great if you could change the exisitng behaviour in some way.

Many thanks in advance.

**Comment by jziaja** [comment]
Hi @andregrohmann, thanks for sharing this!  I definitely agree that the SDK shouldn't be so intrusive with this setting, and should simply enable support for PayPal connections while not impacting the protocol being used for other, non-PayPal connections.

Would you mind submitting a PR for this fix?  If not, I can get this change added, but would like to give credit where credit's due. :)

Thanks!

**Comment by andregrohmann** [comment]
Hi @jziaja , thanks for your answer and giving me a chance to fix it. I will try to submit a PR in the next days.

**Comment by capsizeno4** [comment]
Hi,

My application is getting an error which I believe is related to the TLS update.  

<b>Invalid HTTP response The request was aborted: Could not create SSL/TLS secure channel.</b>

Ive tested my development machine and production machines, both receive positive responses to the TLS tests, and my .NET is at version is 4.5.

i can call https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize...

Example -- when i Log in With Paypal and receive a token.  however my application then fails:

    var paypalLoginEndoint = System.Configuration.ConfigurationManager.AppSettings["PaypalApilLoginEndpoint"];
    var clientId = System.Configuration.ConfigurationManager.AppSettings["PaypalAPIClientId"];
    var response_type = "code";
    var scope = HttpUtility.UrlEncode("openid address email profile https://uri.paypal.com/services/expresscheckout");
    var redirect_uri = System.Configuration.ConfigurationManager.AppSettings["PaypalApiLoginRedirect"];
    var redirectURL = string.Concat(
                paypalLoginEndoint, 
                "?client_id=", clientId, 
                "&response_type=", response_type,
                "&scope=", scope, 
                "&redirect_uri=", redirect_uri);

    return Redirect(redirectURL);

then using the returned auth code:

    GetExpressCheckoutDetailsRequestType request = new GetExpressCheckoutDetailsRequestType();
    request.Version = "106.0";
    request.Token = authCode; // authCode is retrieved succesfully using the http call above

    GetExpressCheckoutDetailsReq wrapper = new GetExpressCheckoutDetailsReq();
    wrapper.GetExpressCheckoutDetailsRequest = request;

    var sdkConfig = Helpers.PayPal.CreateSDKConfig();
    // my sdkConfig has the mode, api username, password and signature.

    PayPalAPIInterfaceServiceService service = new PayPalAPIInterfaceServiceService(sdkConfig);

    GetExpressCheckoutDetailsResponseType ecResponse = service.GetExpressCheckoutDetails(wrapper); // fails here

Any help would be appreciated.

Thanks!

**Comment by andregrohmann** [comment]
Hi @capsizeno4, it seems you are using SOAP to communicate with PayPal and not the PayPal .NET SDK. Nevertheless i think you get this Error because you haven't changed the value of ```ServicePointManager.SecurityProtocol```.  The .NET Framework default is SSL3 and TLSv1.0. Therefore you have to add TLSv1.2 to get a secure connection to PayPal.
