### ISSUE TITLE
Could not establish Secure connection for SSL/TLS

### ISSUE THREAD

**Issue by jlarmbruster** [paypal/PayPal-NET-SDK#147]
I've added latest certificate.

Did the setup for certificates.

Using Windows 10 which supports TLS 1.2,

What else do I need to do?

Why doesn't the sample code work?

It should contain a file that details what a developer needs to do to use the code.

**Comment by pp-randy** [comment]
Have you reviewed the .NET information located here? https://github.com/paypal/tls-update

**Comment by jlarmbruster** [comment]
Yes. I ran the test. Response is PayPal connection OK.

 

The SDK Sample code still fails to make the connection.

**Comment by ppmtscory** [comment]
Can you post your logs so that we can see the full stack trace of the error?

**Comment by jziaja** [comment]
@jlarmbruster Do you mind pulling down the latest `develop` branch and trying the samples again?  I noticed the PayPal & Newtonsoft dependencies included with the samples were pretty old and updated them to the latest release.

**Comment by Liangshunsheng** [comment]
Can you tell me where you are is to download the latest certificate?I encounter this problem: when the sand box test request has been suspended: failed to create the SSL/TLS secure channel.thank you

**Comment by jlarmbruster** [comment]
Jziaja,

I downloaded the latest code, compiled it, and yes!!! It is working.  The older dlls were the issue.

THANK YOU!  THANK YOU!

Jeff

**Comment by Liangshunsheng** [comment]
jlarmbruster,

Can you tell me where you are is to download the latest code?I encounter this problem: when the 

sand box test request has been suspended: failed to create the SSL/TLS secure channel.thank you

**Comment by jlarmbruster** [comment]
Sure,

 

1.        Get the latest code from paypal releases.

2.       Get Fiddler.

 

You need Fiddler to read the actual responses from PayPal.  Some of the responses from payPal look like a connection issue, but they are not.  PayPal is reading what you have sent, then disconnecting the connection, but f you read the response you may see that something that PayPal is expecting is missing.  So your connection is not the issue.  The data packet is missing some information.

 

If you download the code, and you have Windows 7, 8 or 10, you should have TLS 1.2 installed.  If you are using Visual Studio 10 or greater, you should be OK.  The sample code should work AS IS.  Don’t change anything in the sample code --- get it working.  Get Fiddler going.  Read the http packets.

 

You don’t have to get a certificate, or anything.

 

Use the TLS 1.2 check code on the PayPal site to make sure you have TLS 2.

 

That’s all I did.  I have Windows 10 and the Community Edition of Visual Studio 2015.



Good luck.

**Comment by jlarmbruster** [comment]
Use this link to verify that you have TLS 2 1.2 on your machine.

 

Have you reviewed the .NET information located here? https://github.com/paypal/tls-update
