### ISSUE TITLE
JSON deserialize error while creating PayPal Invoice

### ISSUE THREAD

**Issue by miikalaaksonen** [paypal/PayPal-NET-SDK#148]
I managed to create PayPal invoice with SDK:
`                var finalInvoice = ppInvoice.Create(_apiContext);
`
However, log4net shows that created invoice can't be deserialized:
`PayPal.Api.JsonFormatter	Error while deserializing JSON: Could not find member 'links' on object of type 'Invoice'. Path 'links', line 1, position 1078.`
`PayPal.Api.JsonFormatter	Error while deserializing JSON: Could not find member 'template_id' on object of type 'Invoice'. Path 'template_id', line 1, position 63.`

It seems that those elements are missing in Invoice model and JSON.NET is configured with 
`  MissingMemberHandling.Error`

[https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/JsonFormatter.cs#L54](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/JsonFormatter.cs#L54)

Could you fix the issue?

**Comment by juwlee** [comment]
Hi @miikalaaksonen thanks for pointing this out. We will investigate

**Comment by jaypatel512** [comment]
Hey @miikalaaksonen !

Sorry for replying you quite late. Do you mind helping me with testing a fix I am trying to fix. I think there are two fixes that is required in this case. 

1. Replace `PayPalResource` with [PayPalRelationObject](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/PayPalRelationalObject.cs#L11). This should fix the links issue.
2. Replace `MissingMemberHandling.Error` with `MissingMemberHandling.Ignore`. This should fix any new missing field in the SDKs.

I would really appreciate it if you could help us test this out and confirm if these two fixes resolves the issue. I will create a new branch and a PR, with these changes. Please test this out, and see if that works for you or not. 

Thanks again for helping us out with such detailed information.

**Comment by jaypatel512** [comment]
Can you please checkout the above branch and help us figure out if that fixes the issue ? https://github.com/paypal/PayPal-NET-SDK/pull/178

**Comment by jaypatel512** [comment]
Hey @miikalaaksonen !

Can you please help us verify the fix. 👍

**Comment by jaypatel512** [comment]
A new release has been made that includes this fix. https://www.nuget.org/packages/PayPal/1.7.4

Please update your sdk 👍 Thanks all.
