### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error

### ISSUE THREAD

**Issue by tkebede9** [paypal/PayPal-NET-SDK#153]
Currently, we are developing a Payment system within our website via PayPal REST API. Our system (in the development environment) was working OK; but, we are now receiving an error message: "**The remote server returned an error: (500) Internal Server Error.**"

FYI - I also received same error when I ran the samples downloaded from your website (PayPal-NET-SDK-develop.zip) as shown below:

1. Create credit card payment (Failed)

The remote server returned an error: (500) Internal Server Error.
{
  "name": "INTERNAL_SERVICE_ERROR",
  "message": "An internal service error has occurred",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
  "debug_id": "574a0e23cc1a2"
}

Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/18171358/14153991/ed2ff1b6-f67f-11e5-823c-627420f7ccb7.png)

**Comment by ppmtscory** [comment]
Hi all, sandbox appears to be experiencing some downtime. We're tracking the issue over at [paypal/PayPal-PHP-SDK#531](https://github.com/paypal/PayPal-PHP-SDK/issues/531), so I'm going to close this one as a duplicate so that we don't have multiple threads. We'll provide back information as we can there.

**Comment by tkebede9** [comment]
Great. Thanks for looking into the issue!

**Comment by ravenet** [comment]
Hi,

PayPal 1.7.4 giving internal 500 error when try to pay using sandbox. Could you please someone help to fix this issue

thanks
