### ISSUE TITLE
No shipping

### ISSUE THREAD

**Issue by dagostinone** [paypal/PayPal-NET-SDK#157]
Is it possible to make payment without shipping information ? is there any option ?

**Comment by pp-randy** [comment]
@dagostinone Yes, checkout Payment Experience

https://developer.paypal.com/docs/rest/api/payment-experience/
no_shipping: When set to 1, PayPal does not display shipping address fields whatsoever. 

https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentExperienceCreate.aspx.cs

**Comment by pp-randy** [comment]
@dagostinone closing the issue for now, but let me know if you need further help.

**Comment by Olcod** [comment]
@pp-randy Hi, thanks for the information. However, I don;t understand when and how you send the no_shipping flag...
This is the code I have, as you can see I tried to add the flag to the configuration, but the shipping information request is still showing when user clicks "Pay with Credit Card" on the paypal form.
Could you help me please with this?

`Dim sdkConfig As New Dictionary(Of String, String)()

            sdkConfig.Add("mode", Settings.Root.Attributes("mode")(0).Value) '"sandbox")
            sdkConfig.Add("account1.apiUsername", Settings.Root.Attributes("username")(0).Value)
            sdkConfig.Add("account1.apiPassword", Settings.Root.Attributes("password")(0).Value)
            sdkConfig.Add("account1.apiSignature", Settings.Root.Attributes("signature")(0).Value)
            sdkConfig.Add("no_shipping", 1)

            Dim service As New PayPalAPIInterfaceServiceService(sdkConfig)

            Dim setECResponse As SetExpressCheckoutResponseType = service.SetExpressCheckout(wrapper)

            Return setECResponse.Token`

Thanks in advance!

**Comment by Olcod** [comment]
Nevermind. Thanks to the VisualStudio's intellisence, I have found what expects the no_shipping flag.
`
Dim ecDetails As New SetExpressCheckoutRequestDetailsType()
ecDetails.PaymentDetails = paymentDetails
ecDetails.NoShipping = "1"

Dim request As New SetExpressCheckoutRequestType()
request.Version = "104.0"
request.SetExpressCheckoutRequestDetails = ecDetails
`
