### ISSUE TITLE
calling api.sandbox.paypal.com

### ISSUE THREAD

**Issue by tofutim** [paypal/PayPal-NET-SDK#163]
Hi, when I call OAuthTokenCredential, I can see (via Fiddler) that I am calling api.sandbox.paypal.com, but when I call Agreement.Get, Fiddler says I am calling api.paypal.com. What is going on there? I get 401 unrecognized.

```
            var config = new Dictionary<string, string>();
            config.Add("mode", "sandbox");
            config.Add("clientId", "AdXvFr6p3mM39nmbhaH1sn3moj2-gY3zVn_mYbSYbvHEeBPTlC2z432ExxyPEJtDvg-Bt2kM0UD7WJwC");
            config.Add("clientSecret", "EDCKvEE1O5jgDNWKIgMP_eb5tCAjszFq4imNKcXqNqVBr-kw9zppncYZ2NAIgeSSu0uDUF5i8StD0A80");
            var accessToken = new PayPal.Api.OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new PayPal.Api.APIContext(accessToken);

            try
            {
                PayPal.Api.Agreement.Cancel(apiContext, "I-UTHES9UWP5D7", new PayPal.Api.AgreementStateDescriptor { note = "No more" });
//                var agreement = PayPal.Api.Agreement.Get(apiContext, "I-xx");
                var agreement = PayPal.Api.Agreement.Get(apiContext, "I-UTHES9UWP5D7");
            }
            catch (Exception ex)
            {
                // Subscription Profiles not supported by Recurring Payment APIs
                _logger.Log(ex.Message);
            }

```

**Comment by tofutim** [comment]
looks like I actually have to set the Web.Config and use the ConfigManager so that it consistently calls sandbox. Is there away to have both at the same time?

**Comment by jaypatel512** [comment]
Hey @tofutim !

If you follow the steps mentioned [here](https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call), you would be able to fetch the Web.Config properties and inject it to `OAuthTokenCredential` properly. This will allow you to keep those properties in one place.
