### ISSUE TITLE
Test Card For SandBox

### ISSUE THREAD

**Issue by LostInZen** [paypal/PayPal-NET-SDK#165]
As of Yesterday(5/26/2016) any test cards are not passing the payment.Create() method.
The Vault is storing the cards correctly as far as i can tell.
Either way (card information/ or card token) in the payment fails with the following message:
![image](https://cloud.githubusercontent.com/assets/19613046/15615593/f2a11cda-2404-11e6-8601-05aea3e5ffec.png)
or in your sample application:
![image](https://cloud.githubusercontent.com/assets/19613046/15615695/603c82e8-2405-11e6-9cc5-8e9e88164d9f.png)

No details are provided on this issue, when i test with a live card (real card )the system seems to be working fine.
Any help on this issue would be greatly appreciated.
Thank you
LostInZen

**Comment by pp-randy** [comment]
I apologize this card stopped working for you; this can happen in the sandbox when a credit card is overused.  Don't use live numbers, you can use the Credit Card generator here on step 4 https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US.  Any credit card that passes Luhn algorithm, unless experiencing the same problem as this one should work in sandbox. 

Please try a new one and let me know if you have further issues.  

Internal Tracking: PPPLMER-14753

**Comment by LostInZen** [comment]
Thank you for your speedy response. I needed that reassurance.  I'm surprised Paypal Doesn't list that in the exception details.

**Comment by pp-randy** [comment]
The tracking id I provided is a feature request I submitted for better error messaging and some tools to better assist with this type of issue.

**Comment by pp-randy** [comment]
Further follow up is also being tracked here: https://github.com/paypal/PayPal-REST-API-issues/issues/22
