### ISSUE TITLE
How can I suppress Shipping info?

### ISSUE THREAD

**Issue by danielcamargo** [paypal/PayPal-NET-SDK#166]
How can I include NOSHIPPING=1 in payment link?

**Comment by jaypatel512** [comment]
Do you mean something like this: https://github.com/paypal/PayPal-PHP-SDK/issues/415

**Comment by danielcamargo** [comment]
I am using the example:

```
var config = ConfigManager.Instance.GetProperties();
var accessToken = new OAuthTokenCredential(config).GetAccessToken();
var apiContext = new APIContext(accessToken);

// Make an API call
var payment = Payment.Create(apiContext, new Payment
{
  (...)
};
```
And then redirecting the user to the **approval_url** from the recently created payment.

I wonder if there is a way to include the *no shipping* as part of the payment creation.


PS: Thank you for the quick response!

**Comment by jaypatel512** [comment]
Yes, you can provide noShipping. However, the way this works is, we have different set of [Payment Experience API](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentExperienceCreate.aspx.cs) that allows you to modify a lot of similar configurations using it. Once you create a Payment Experience, you will be returned an Id, that can be added to all the payments, which would use that experience accordingly. 

Here would be the steps for you:
1. Create a web-profile with noShipping set to true. (as shown in the sample).
2. Use the web-profile-id returned on step 1, and add it inside the payment object :[experience_profile_id](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Payment.cs#L79)
3. Proceed with the normal checkout flow.
4. Execute the payment as usual.

Checkout the sample explaining how to create a payment Experience ID: https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentExperienceCreate.aspx.cs

**Comment by dgandini** [comment]
Daniel, you have to create a WebExperience Profile and associate it to the Payment trough the experience_profile_id property.

WebProfile Creation:
`
var webProfileList = WebProfile.GetList(apiContext);

                    foreach (var webProfile in webProfileList)
                    {
                        WebProfile.Delete(apiContext, webProfile.id);
                    }


                    // Create the web experience profile
                    var profile = new WebProfile
                    {
                        name = "My web experience profile",
                        presentation = new Presentation
                        {
                            brand_name = "My brand name",
                            locale_code = "BR",
                            logo_image = "https://pbs.twimg.com/profile_images/2942551441/faa085438933d2d1ef06f0cf7b8aa7e3.jpeg"
                        },
                        input_fields = new InputFields
                        {
                            no_shipping = 1
                        }
                    };

                    var createdProfile = profile.Create(apiContext);`

Payment creation with a webprofile associated to it
`            // Create the payment
            var payment = new Payment
            {
                intent = "sale",
                experience_profile_id = createdProfileId,
                payer = new Payer
                {
                    payment_method = "paypal"
                },
                transactions = new List<Transaction>
                    {
                        new Transaction
                        {
                            description = "Ticket information.",
                            item_list = new ItemList
                            {
                                items = new List<Item>
                                {
                                    new Item
                                    {
                                        name = "Concert ticket",
                                        currency = "BRL",
                                        price = "20.00",
                                        quantity = "2",
                                        sku = "ticket_sku"
                                    }
                                }
                            },
                            amount = new Amount
                            {
                                currency = "BRL",
                                total = "45.00",
                                details = new Details
                                {
                                    tax = "5.00",
                                    subtotal = "40.00"
                                }
                            }
                        }
                    },
                redirect_urls = new RedirectUrls
                {
                    return_url = redirectUrl,
                    cancel_url = redirectUrl
                }
            };

            return payment.Create(apiContext);`

**Comment by danielcamargo** [comment]
Thank you guys! That solved my problem.
