### ISSUE TITLE
canceling subscription in Live, buttons

### ISSUE THREAD

**Issue by tofutim** [paypal/PayPal-NET-SDK#172]
Hi, I am working on switching everything to use the new Net-SDK. However, I am running into a couple issues.

1. I need to cancel subscriptions. I am using Agreement.Cancel and it works fine in Sandbox to cancel I-* type subscriptions. However, when I switch to live I get Unauthorized when I call .Cancel. I used new ClientId/ClientSecret just to be safe but no go. Help!

I am investigating the old API for ManageRecurringPaymentsProfileStatusRequestType, but prefer not go backwards. This from the Merchant API (old style).

2. I'm using the Button Manager SDK. Is it possible to generate buttons with the new API?

**Comment by tofutim** [comment]
I was able to cancel the subscription using the old Merchant API

```
                    var request = new ManageRecurringPaymentsProfileStatusRequestType();
                    var details = new ManageRecurringPaymentsProfileStatusRequestDetailsType();
                    request.ManageRecurringPaymentsProfileStatusRequestDetails = details;

                    details.ProfileID = subscrId;
                    details.Action = StatusChangeActionType.CANCEL;

                    var wrapper = new ManageRecurringPaymentsProfileStatusReq();
                    wrapper.ManageRecurringPaymentsProfileStatusRequest = request;

                    var configMap = GenerateConfig(isSandbox);
                    var service = new PayPalAPIInterfaceServiceService(configMap);
                    var manageProfileStatusResponse = service.ManageRecurringPaymentsProfileStatus(wrapper);

                    var responseParams = new Dictionary<string, string>();
                    responseParams.Add("API Status", manageProfileStatusResponse.Ack.ToString());

                    if (manageProfileStatusResponse.Ack.Equals(AckCodeType.FAILURE) || (manageProfileStatusResponse.Errors != null && manageProfileStatusResponse.Errors.Count > 0))
                    {
                        _logger.Log(manageProfileStatusResponse.Errors.ToString());
                        return false;
                    }
                    else
                    {
                        _logger.Log("Success");
                        return true;
                    }
```


but that doesn't explain why Agreement.Cancel does not work. :(  I prefer to use the newer API as the older is supposed to get deprecated soon. Again, using this SDK

`PayPal.Api.Agreement.Cancel(apiContext, subscrId, new PayPal.Api.AgreementStateDescriptor { note = note });
`
worked in Sandbox (canceled the subscription), but I got 401 Unauthorized when using Live. Incidentally, after canceling it with the old SDK, I noticed I still get 401 Unauthorized.

**Comment by tofutim** [comment]
Hi, it turns out this is issue #169 again. If I set apiContext.config = config (the new config), then everything works, otherwise, apiContext.config is null and it goes to Web.Config to look. If Web.Config happens to be Sandbox, then Sandbox will work otherwise Live then Live.

**Comment by ppmtscory** [comment]
@tofutim for your first question, let's continue to track that over on #169 as it's already been marked as a bug to be looked into on there.

For your second question, no, there isn't a REST equivalent to the Button Manager SDK.  I'd recommend just using the regular REST Payments API instead.  This overview can be found [here](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/).
