### ISSUE TITLE
Since 2016 Sep no webhook event in sandbox

### ISSUE THREAD

**Issue by ravenet** [paypal/PayPal-NET-SDK#188]
Hi,
Since Sep 2016, there is no webhook event from PayPal sandbox, it is status always pending.
![paypal](https://cloud.githubusercontent.com/assets/6859970/18277102/d1a0d0ea-747f-11e6-9461-2db42375617e.png)

Please someone help me to fix the issue.
Thanks

**Comment by gorillapower** [comment]
I am also getting payment sale completed, but the status is 'pending'. The webhook notification also fails to send to the webhook URL for all events (works fine on simulated webhook event caller).

**Comment by pp-randy** [comment]
I apologize that the webhooks are not working as expected in the sandbox at this time.  PayPal is aware and it working to resolve the issue. 

Internal Tracking: PPPLPAYPT-12584

**Comment by ravenet** [comment]
Dear Randy,

That's a good update and shall we know that when it will be fixed as we are planning to roll out our system to live, we  have to make sure it is working in sandbox to minimize problems.

Thanks

**Comment by pp-randy** [comment]
Hi @ravenet,

I will do my best to keep you updated.  We are working this with a very high priority. 

Updated Internal Tracking: PPBLRAC-12395

**Comment by ravenet** [comment]
Hi Guys,

It is fixed, because it was working since last Saturday. 

Thanks

**Comment by pp-randy** [comment]
Thank you for confirming @ravenet the issue appears to be resolved at this time.
