### ISSUE TITLE
Can't process a sale on sandbox, 500 INTERNAL SERVICE ERROR

### ISSUE THREAD

**Issue by mombrea** [paypal/PayPal-NET-SDK#190]
Since the beginning of September, all REST API attempts at calling Payment.Create() are failing with a 500 INTERNAL SERVICE ERROR on the sandbox API.  Nothing has changed in our API call which had been working for several months previously.

The latest response error is:

"{\"name\":\"INTERNAL_SERVICE_ERROR\",\"message\":\"An internal service error has occurred\",\"information_link\":\"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR\",\"debug_id\":\"40ef96d2bc787\"}"

We're using the SDK version 1.7.4.

I've tried using different credit card information as I've seen issues in the past with overused test cards.

**Comment by pp-randy** [comment]
This issue is currently being tracked here: https://github.com/paypal/PayPal-PHP-SDK/issues/639
