### ISSUE TITLE
Error Executing Payment - Getting PayPal.HttpException (404) Not Found

### ISSUE THREAD

**Issue by robpearson** [paypal/PayPal-NET-SDK#192]
I'm working to correct sporadic payment execution failures.  This happens seemingly randomly (roughly one in twenty payments) which is the odd part.  

- Using the latest PayPal .NET SDK (1.7.4)
- Happens in `live` environment.  Cannot reproduce it in the `sandbox` environment.
- Payment is created successfully.
- Customer is redirected to PayPal and authorizes the payment.
- Customer is redirected back to my site and then I execute the payment and it fails with the following error. 

```
PayPal.HttpException: The remote server returned an error: (404) Not Found.
   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
   at PayPal.Api.Payment.Execute(APIContext apiContext, String paymentId, PaymentExecution paymentExecution)
   ...
```

My payment code is very similar to the example source code (https://github.com/paypal/PayPal-NET-SDK/blob/77b14e19402e7ee8dfa170cbce98d4b14c8ee6b5/Samples/Source/PaymentWithPayPal.aspx.cs) and the payment execution is so simple, I'm somewhat stumped as to why it is failing.  I saw in a previous issue (https://github.com/paypal/PayPal-NET-SDK/issues/95) that a 404 is returned when the resource (Payment) is not found using the credentials passed.  I'm pretty confident that the payment id and payer_id are correct as well as the apiContext set up.  

**Is there any way to get more information on what is not found?**

**Comment by tompazourek** [comment]
@robpearson I'm also experiencing some sporadic 404 failures (probably a bit more rare than 1 in 20 payments, more like 1 in 50), but I have the same issue. **Did you eventually resolve it? How?**

Thanks

**Comment by pp-randy** [comment]
@tompazourek if this isn't happening in Sandbox and only occurs on Live; then you should reach out to PayPal Technical Support at https://www.paypal-techsupport.com.

**Comment by robpearson** [comment]
@tompazourek I was able to resolve our issue as we weren't using the SDK properly. We did some things manually that worked for ages but I updated things to do it as per the docs and we haven't had an issue since. 👍

**Comment by tompazourek** [comment]
Ok, thanks for the information. 👍
