### ISSUE TITLE
SDK api is returning wrong REDIRECT link

### ISSUE THREAD

**Issue by edhannite** [paypal/PayPal-NET-SDK#193]
Below is an extracted section from the JSON response of the Payment Create method in the sdk.
As you can see, the redirect link is supposed to be a link to sandbox paypal but today, it is reflecting a link to the live paypal site. The other links are correct. Is there an config issue with the sandbox environment at paypal side?

Extracted json:
{
  "id": "PAY-2JV20261WD419913YK7QPB5A",
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
 ........................
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-2JV20261WD419913YK7QPB5A",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-2JV20261WD419913YK7QPB5A/execute",
      "rel": "execute",
      "method": "POST"
    },
    {
      "href": "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-1VW44344TE6103403",
      "rel": "approval_url",
      "method": "REDIRECT"
    }
  ]
}

**Comment by sviluppo** [comment]
Same here!

**Comment by gorillapower** [comment]
Im also getting that.

**Comment by pp-randy** [comment]
Thank you for the report regarding this sandbox issue. We are working to resolve this.  

Internal Tracking: PPPLMER-20280

**Comment by hygkui** [comment]
same error!

**Comment by edhannite** [comment]
seems like the issue has being resolved now as i just tested it.

**Comment by pp-randy** [comment]
Thank you all for your patience while the issue was resolved.

@edhannite thank you for updating with a note of resolution.
