### ISSUE TITLE
Webhook not firing for Direct Credit Card payment

### ISSUE THREAD

**Issue by gorillapower** [paypal/PayPal-NET-SDK#194]
Ive been scouring the web for documentation on webhooks (https://developer.paypal.com/docs/integration/direct/rest/webhooks/), github and stackoverflow, but i cant find a definitive answer for the question: **Does webhooks support direct credit card payments**?

I dont see anything mentioned in the documentation about this limitation, did i miss it? I developed a solution that uses webhooks but i need the "PAYMENT.SALE.COMPLETED" event to fire for any payment as there is additional work that needs to be done that confirms a payment in our system. If paypal does not support this, what implementation should I use to solve this?

**Comment by doczoidberg** [comment]
I am also struggling with webhooks. They should work without SDK and with https://github.com/aspnet/WebHooks?
There is also no example code receiving webhook events?

**Comment by bluk** [comment]
Web hooks are only supported for PayPal payments (not direct credit card payments). See https://github.com/paypal/PayPal-PHP-SDK/issues/209 .
