### ISSUE TITLE
PayPal webhooks is not sending notifications

### ISSUE THREAD

**Issue by primalfear** [paypal/PayPal-NET-SDK#204]
I am using PayPal client 1.7.4 and am attempting to make use of the subscription api's for re-occurring billing.

I am able to create the Billing Plan and Billing Agreement, Redirect the user to the payment page, and on return to our "success page" activate the Billing Agreement.

I have setup a webhook for ALL events, but this never seams to be called.
I am able to hit my end-point via the webhook simulator.

In the Developer Portal Under Sandbox / Webhooks Events, the list has zero items.

**Comment by bluk** [comment]
Thanks for reporting the issue. PPPLMER-21955 is internally tracking this issue.

**Comment by bluk** [comment]
This should have been fixed now. I see webhook events for sandbox test apps.

If this is still an issue, please leave a comment or open a new issue. Thanks!
