### ISSUE TITLE
UWP compatibility errors.

### ISSUE THREAD

**Issue by DoruLa** [paypal/PayPal-NET-SDK#211]
I tried installing the PayPal NuGet plugin in an UWP application and I got the following output:

**PayPal 1.8.0 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.**

Is there any option other than the REST API for implementing a payment? Are you planning in releasing a fix soon?

**Comment by jaypatel512** [comment]
Hey @DoruLa !

We currently do not support UAP for this SDK. We may add this feature if UWP gets more traction and request from external community, or some help with a PR to implement it. 

In the mean time, I would recommend you calling the APIs directly to create Payments. All the REST APIs are documented well in [developer.paypal.com](https://developer.paypal.com/docs/api/payments/) website. You should be easily able to follow the steps and create your own implementation for now.

**Comment by aline-almeida** [comment]
I want this too!

**Comment by xiaoleih41** [comment]
We haven't received enough requests to add this feature therefore this will be included in the roadmap anytime soon.  Please call the APIs directly to create Payments as it was suggested earlier.

**Comment by nguyenthanhliemfc** [comment]
Please support UWP, Thank!
