### ISSUE TITLE
How to use 'option value1' and 'option name1' in REST API for .net?

### ISSUE THREAD

**Issue by Kevin-CaiYong** [paypal/PayPal-NET-SDK#216]
I am migrating existing code from traditional method to REST, but did find way to post customized value to Paypal. Any idea?

**Comment by jaypatel512** [comment]
Hey @Kevin-CaiYong !

Can you please elaborate on your question ? What action are you trying using REST API ? Can you please provide the example of your traditional request you mentioned too. That should help understand your question better.

**Comment by ppmtscory** [comment]
@Kevin-CaiYong you're referencing standard HTML variables for PayPal Payments Standard.  Payment Standard HTML is not included in this SDK.  If you want to use this SDK, and need some guidance in transitioning over to Express Checkout, then please reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team.
