### ISSUE TITLE
Integrating PayPal .NET SDK into website without using PayPal button

### ISSUE THREAD

**Issue by saf-itpro** [paypal/PayPal-NET-SDK#218]
We've implemented the above as follows:

We're integrating PayPal .NET SDK with a public website without using PayPal's built-in Buttons (Buy Now etc.). User clicks on a regular ASP.NET MVC button that calls an Action method that creates a payment object with all necessary properties set (transactions, urls, amount, quantity etc.). The clicking of this regular button calls necessary PayPal .NET SDK APIs, connects to PayPal that displays its own page where user logs in verifies the amount displays, approves it by clicking their submit button, PayPal - after approving it- sends a response back where we perform our some back-office tasks and if everything goes OK our "Payment Successful" pages gets displayed. Or code is using PayPal's [Webhook ](https://developer.paypal.com/docs/integration/direct/rest/webhooks/) functionality as well.

**Question**: We've tested the above process on PayPal's SandBox and it works fine. Are we missing something and/or PayPal's Built-in button ("Buy Now" etc.) is necessary? The application is for selling one single item (a digital download) at a time.

**Comment by billsliu** [comment]
Paypal pro must be used with Paypal express(Paypal button) together, please check the terms of service. You can see it on Bestbuy check out. Both customize credit card payment and paypal button display on same page, that is the reason you can get incredible low credit card processing rate 2%.

**Comment by jaypatel512** [comment]
Yes ! You should be `executing` the payment once you get an approval redirect from paypal, as shown here: https://developer.paypal.com/docs/integration/direct/express-checkout/execute-payments/.

**Comment by jaypatel512** [comment]
All the steps required for completing the express checkout flow in PayPal is mentioned here: https://developer.paypal.com/docs/integration/direct/express-checkout/

For any business related queries, you may have to reach out to [PayPal Merchant customer care](https://www.paypal.com/us/webapps/mpp/merchant).

**Comment by saf-itpro** [comment]
@jaypatel512 I'm using this sample [from GitHub](https://github.com/tutsplus/paypal-integration) that does not use any of the PayPal buttons. The process is explained [here ](https://code.tutsplus.com/articles/paypal-integration-part-2-paypal-rest-api--cms-22917) by the author (please see the Single PayPal Payment section of the article). When I run the sample, on the home page I click on the first link titled "Create PayPal Payment" and the whole process goes through PayPal Sandbox including approvals etc. Am I missing something here? Please help.
