### ISSUE TITLE
Currency Issue

### ISSUE THREAD

**Issue by majdee** [paypal/PayPal-NET-SDK#219]
Hi,

I'm using the Create method, to pay by credit card and I got the following exception("ILS" used as currency):
{
	"name": "DCC_PREPROCESSOR_ERROR",
	"message": "DCC_PREPROCESSOR_ERROR",
	"information_link": "https://developer.paypal.com/docs/api/#DCC_PREPROCESSOR_ERROR",
	"debug_id": "e641fcbc5da37"
}

When I changed the currency to "USD" it worked well.

So, what should I do in order to use ILS as a currency ?

Thanks.

**Comment by pp-randy** [comment]
I do not see that ILS is available for Credit Card payments, only PayPal payments.  I am using this as the source https://developer.paypal.com/docs/classic/api/currency_codes/#creditcard

Are you getting this error trying to use ILS with a Credit Card or as a PayPal payment?

**Comment by majdee** [comment]
I tried it with credit card.

**Comment by pp-randy** [comment]
Is your business located in Israel?  If so, you should reach out to the sales team shown here by clicking the Contact our sales team link.
https://www.paypal.com/il/webapps/mpp/merchant?locale.x=en_IL
![image](https://cloud.githubusercontent.com/assets/6819909/20531256/cd5a8fb4-b09b-11e6-96de-ddb83bfb4318.png)

The sales team would be more knowledgeable about Israel based integrations, and I don't want to rule out Credit Card payments that the sales team might be able to assist with.
