### ISSUE TITLE
Recurrent payment implementation for .Net 

### ISSUE THREAD

**Issue by bejaouibechir** [paypal/PayPal-NET-SDK#223]
Is there any complete recurrent payment complete implementation for .Net sample, I did a research and unfortunately I didn't found any complete and good implementation for that

**Comment by pp-randy** [comment]
The REST API that this SDK is for implements recurring payments with Billing Plans and Billing Agreements.

https://developer.paypal.com/docs/api/payments.billing-plans

https://github.com/paypal/PayPal-NET-SDK/tree/develop/Samples/Source

You create a Billing Plan and activate it, then use it to create Billing Agreements. 

Please let me know if you need further help.

**Comment by bejaouibechir** [comment]
Thank you for the information pp-randy
