### ISSUE TITLE
Payment detail information will be invalid after several hours in sandbox.

### ISSUE THREAD

**Issue by billsliu** [paypal/PayPal-NET-SDK#226]
I can view the payment detail both by calling rest api and from sandbox website after I make a payment  in sandbox, but this payment detail only exists for a short time (several hours), the payment detail will be invalid after several hours.

App name is "test"
This App use PayPal rest api and the sandbox account for this App is  billsliu4@gmail.com, this app create a payment and set payee to the third party email billsliuend@gmail.com (business accout)
the payer's email: billsliu-buyer4@gmail.com
business acount that receive the fund : billsliuend@gmail.com

The payment id is PAY-6DR97167KP011280WLBQTJRY
The sale id is 0ET30791TL2272032

Money has been deducted from buyer's account and deposited to business account successfully.

**Why does the transaction became invalid after several hours?**

Error from business account billsliuend@gmail.com that receives the fund
![error](https://cloud.githubusercontent.com/assets/5201301/21487013/3585bd46-cb8d-11e6-8e97-e0cd511fa619.jpg)

Error from buyer account billsliu-buyer4@gmail.com
![buyer](https://cloud.githubusercontent.com/assets/5201301/21487088/25fec1a4-cb8f-11e6-9333-d69f0b3d6144.jpg)

![buyererror](https://cloud.githubusercontent.com/assets/5201301/21487090/2f1c45a4-cb8f-11e6-823e-0025a55eacd0.jpg)

**Comment by ppmtscory** [comment]
Please create a ticket to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team as this error is not an issue with the SDK.  It's not that the information disappears, it's just that the sandbox environment isn't able to pull it up for whatever reason.  The MTS team will be able to assist you further with sandbox account activity issues.
