### ISSUE TITLE
Failed to connect to test-api.sandbox.paypal.com

### ISSUE THREAD

**Issue by gorgi** [paypal/PayPal-NET-SDK#228]
I'm updating the SDK for PayPal's REST API, so the project I'm working on is ready for the TLS 1.2/HTTP 1.1 transition. After the update, I set the mode to 'security-test-sandbox' and the SDK throws error on the GetAccessToken method. It is failing to connect to test-api.sandbox.paypal.com.

From the upgrade documentation web site: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1914&expand=true&locale=en_US

Their list of Sandbox Endpoints is:

    api.sandbox.paypal.com
    api-3t.sandbox.paypal.com
    api-aa.sandbox.paypal.com
    api-aa-3t.sandbox.paypal.com
    svcs.sandbox.paypal.com
    pointofsale.sandbox.paypal.com
    ipnpb.sandbox.paypal.com
    www.sandbox.paypal.com

However, for the new sandbox mode, the SDK uses this endpoint: https://github.com/paypal/PayPal-NET-SDK/blob/65590165044711549b6e4fa981c2f30b2e3c1027/Source/SDK/BaseConstants.cs#L64

which is not in the list above.

Am I doing something wrong? How should I test the new security demands?

Thanks!

**Comment by pp-randy** [comment]
Use RESTSandboxEndpoint for now. The sandbox enforces these requirements.

**Comment by gorgi** [comment]
You need to update your Readme :)

**Comment by pp-randy** [comment]
Thank you @gorgi I have submitted a pull request to do just that.
