### ISSUE TITLE
Phone number and firstname/lastname

### ISSUE THREAD

**Issue by Incognito-Nemo** [paypal/PayPal-NET-SDK#229]
In C# I use 

var payeur = new Payer
            {
                payment_method = "paypal",  
                payer_info = new PayerInfo
                {
                    first_name = "First",
                    last_name = "Last",
                    phone = "+33 612345678",
                    email = "pipo@pipo.pipo"
                }
            };

and

var payment = Payment.Create(apiContext, new Payment
            {
                intent = "sale",
                experience_profile_id = experienceProfileId,
                payer = payeur,
                transactions = transactions,
                redirect_urls = new RedirectUrls
                {
                    return_url = "http://almageste.info/PayPal/Return",
                    cancel_url = "http://almageste.info/PayPal/Cancel"
                }
            });

and I get an error message 400 bad request. If I remove the phone number, there is no problem if I remove the phone number. Same thing for phone_type parameter.

And without the phone number, firstname/lastname are not pur in the fields of the Paypal form...

Any suggestion ?

**Comment by pp-randy** [comment]
From what I can tell the phone field is read-only, but I am following up to make sure and if that is the case to get that documented.  I also found a related StackOverflow thread for how to get phone number to return http://stackoverflow.com/questions/30106041/paypal-rest-api-paymentget-doesnt-return-phone

**Comment by pp-randy** [comment]
It is read-only, so we will follow up further on the documentation.

**Comment by pp-randy** [comment]
Documentation is updated, sorry for the delay in updating.
