### ISSUE TITLE
Change Business or Company Name on the fly

### ISSUE THREAD

**Issue by ravikumarmurai** [paypal/PayPal-NET-SDK#233]
I could not find the method or property to change the Company Name or Business Name

**Comment by xiaoleih41** [comment]
Thank you for your question. To update business name, you will have to create a web experience profile first. then update the brand_name afterwards. Please check into this reference page for detail. https://developer.paypal.com/docs/api/payment-experience/#definition-presentation
Unfortunately, there's no straightforward way to update business name in REST API.  Please let me know if you have any further questions.
