### ISSUE TITLE
Cannot extract the Debug ID/ Correlation ID from the header

### ISSUE THREAD

**Issue by rajeevggupta** [paypal/PayPal-NET-SDK#234]
Cannot extract the Debug ID/ Correlation ID from the header as the json response is already serialized by the time we want to GET the Payment info.

Thanks,
Rajeev

**Comment by marlongpp** [comment]
in the REST dotnet SDK, on https://github.com/paypal/PayPal-NET-SDK, the code allows you to extract header information IF there's an error. however, we are unable to extract the debug id from the payment info.

if (ex is PayPal.PaymentsException)
                {
                    var pex = (PayPal.PaymentsException)ex;
                    jsonPayPal = "PayPal.PaymentsException : " + Environment.NewLine;
                    jsonPayPal = (pex.Details != null ? JsonConvert.SerializeObject(pex.Details) : JsonConvert.SerializeObject(pex));
                }
                else if (ex is PayPal.PayPalException)
                {
                    var pex = (PayPal.PayPalException)ex;
                    jsonPayPal = "PayPal.PayPalException : " + Environment.NewLine;
                    jsonPayPal = JsonConvert.SerializeObject(pex);
                }

It looks like the json has been serialized and raw data from header is not extractable after that.

PayPal has recommended that Debug ID be part of logging in case of errors, so please advise.

**Comment by pp-randy** [comment]
I will look into this and see what I can get figured out.

**Comment by pp-randy** [comment]
I submitted a pull request and it is being reviewed https://github.com/paypal/PayPal-NET-SDK/pull/237

It would add a `GetDebugId()` method to the resulting response object.

**Comment by rajeevggupta** [comment]
Could someone merge these changes please.

**Comment by pp-randy** [comment]
The pull request has been merged.  Can you review and see if it will work for your needs?
