### ISSUE TITLE
US address validation error

### ISSUE THREAD

**Issue by isaeed** [paypal/PayPal-NET-SDK#235]
Hi , 
for the following request ( using Payments Rest API ) 

{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "125.00",
        "details": {
          "subtotal": "100",
          "shipping": "10",
          "tax": "15"
        }
      },
      "payee": {
        "email": "asiqa63-facilitator@asicentral.com"
      },
      "description": "Transaction description.",
      "invoice_number": "766180",
      "item_list": {
        "items": [
          {
            "sku": "sku",
            "name": "Item Name",
            "quantity": "1",
            "price": "100",
            "currency": "USD"
          }
        ],
        "shipping_address": {
          "line1": "Story Avenue",
          "city": "East Bronx",
          "country_code": "US",
          "postal_code": "10473",
          "state": "NY"
        }
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://localhost:56508/PaymentWithPayPal.aspx?guid=76618",
    "cancel_url": "http://localhost:56508/PaymentWithPayPal.aspx?guid=76618&cancel=true"
  }
}

i get this error response , 
// Response 
{
  "name": "VALIDATION_ERROR",
  "details": [
    {
      "field": "city",
      "issue": "Value is invalid"
    },
    {
      "field": "state",
      "issue": "Value is invalid"
    },
    {
      "field": "zip",
      "issue": "Value is invalid"
    }
  ],
  "message": "Invalid request - see details",
  "information_link": "https://developer.paypal.com/docs/api/#VALIDATION_ERROR",
  "debug_id": "45a127cd73d88"
}

i got the address from google maps , any idea what i am doing wrong ....

**Comment by xiaoleih41** [comment]
Thank you for your question. East Bronx is not a recognized city name. Please switch to Bronx instead. This should fix the issue. Please let us know if you have any further questions.

**Comment by isaeed** [comment]
Thanks, 

it fixes the issue, but i am confused if i need to apply data cleansing rules , then what it could be? specially for US addresses.

**Comment by pp-randy** [comment]
If you are going to provide an address then yes cleansing would be advised.  I looked up the zip code here and it shows Bronx as well https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=10473&zip=

When using PayPal for the Payment though you do not need to supply the shipping address, the buyer can supply one during the checkout process and PayPal can supply it to you.  Would this work?
