### ISSUE TITLE
In sample project execution of SaleRefund request does not work

### ISSUE THREAD

**Issue by mmikirtumov** [paypal/PayPal-NET-SDK#239]
When I try to run SalesRefund request in [PayPal sample project](https://github.com/paypal/PayPal-NET-SDK/tree/develop/Samples), I receive the following error

 The remote server returned an error: (400) Bad Request.
{
  "name": "DUPLICATE_REQUEST_ID",
  "message": "PayPal-Request-Id header was already used.",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID",
  "debug_id": "98050e8e2485"
}

**Comment by pp-randy** [comment]
Thank you for the pull request.
