### ISSUE TITLE
Getting MALFORMED_REQUEST from API

### ISSUE THREAD

**Issue by isaeed** [paypal/PayPal-NET-SDK#243]
Hi,

i am trying to update note_to_payer for a payment (is it possible to update it? ),  but getting MALFORMED_REQUEST error back. here are some debug_id(s) for reference 
"debug_id":"6056bf446a663"
"debug_id": "18291ec19d74e"
"debug_id": "415216fdd722"

**Comment by pp-randy** [comment]
It is working in my testing.  Can you provide the request JSON or an example of the code you are using?

**Comment by pp-randy** [comment]
I tested in the create, I was not able to patch it.

**Comment by pp-randy** [comment]
Can you help me understand your use case for patching this value instead of including it in the create?  Usually a patch is made to update a price or an address before executing the payment.

**Comment by isaeed** [comment]
hi ,

sorry for late response , i have now changed my scenario and i want to change/update payment. at payment.execution time .  

here are my Requests and Responses 
**Create Response** 
{
  "id": "PAY-39M77760EP600530LLDABU4Q",
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "related_resources": [],
      "amount": {
        "currency": "USD",
        "total": "37.80",
        "details": {
          "subtotal": "37.80",
          "shipping": "0.00",
          "tax": "0.00"
        }
      },
      "payee": {
        "email": "isaeed-facilitator@asicentral.com"
      },
      "description": "Transaction description.",
      "invoice_number": "515552",
      "item_list": {
        "items": [
          {
            "sku": "sku",
            "name": "Item Name",
            "quantity": "1",
            "price": "37.80",
            "currency": "USD"
          }
        ],
        "shipping_address": {
          "line1": "Story Avenue",
          "city": "Bronx",
          "country_code": "US",
          "postal_code": "10473",
          "state": "NY"
        }
      }
    }
  ],
  "state": "created",
  "note_to_payer": "order id not generated",
  "create_time": "2017-03-08T14:51:30Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-39M77760EP600530LLDABU4Q",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-23D77772C71428055",
      "rel": "approval_url",
      "method": "REDIRECT"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-39M77760EP600530LLDABU4Q/execute",
      "rel": "execute",
      "method": "POST"
    }
  ]
}  

**Execute Request**
{
  "payer_id": "8EP3JY3NC5WQU",
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "34.30",
        "details": {
          "subtotal": "34.30",
          "shipping": "0",
          "tax": "0"
        }
      },
      "description": "Transaction description. after order.",
      "invoice_number": "811707",
      "item_list": {
        "items": [
          {
            "sku": "sku",
            "name": "Item Name",
            "quantity": "1",
            "price": "37.80",
            "currency": "USD"
          },
          {
            "sku": "sku_discount",
            "name": "Special Discount",
            "quantity": "1",
            "price": "-3.50",
            "currency": "USD"
          }
        ],
        "shipping_address": {
          "line1": "Story Avenue",
          "city": "Bronx",
          "country_code": "US",
          "postal_code": "10473",
          "state": "NY"
        }
      }
    }
  ]
}

**Execute Reponse**
{
  "name": "VALIDATION_ERROR",
  "details": [
    {
      "field": "purchase_units[0]",
      "issue": "Item amount must add up to specified amount subtotal (or total if amount details not specified)"
    }
  ],
  "message": "Invalid request - see details",
  "information_link": "https://developer.paypal.com/docs/api/#VALIDATION_ERROR",
  "debug_id": "899d82b1b5f55"
}

**Comment by pp-randy** [comment]
I think you need to include the discount in the create payment request as well from my testing.

**Comment by pp-randy** [comment]
If you pass in the discount with the create payment, it would display to the payer on PayPal and that is probably a good thing.
