### ISSUE TITLE
.NET Restful API Capture will access Sandbox even if mode is live

### ISSUE THREAD

**Issue by MDornian** [paypal/PayPal-NET-SDK#244]
We have tested this code in sandbox and it works correctly.  In production, when the mode is "live", according to 'PayPal.Api.PayPalResource.LastRequestDetails', the 'OAuthTokenCredential.GetAccessToken()' is directed to https://api.paypal.com/v1/oauth2/token but the 'Authorization.Capture()' is directed to https://api.sandbox.paypal.com.  

It looks like the SDK is ignoring the "mode" for the Authorization.

PayPal .NET SDK version 1.8.0

`var credential = context.Credential.Where(x => x.Identifier == "PayPalRestfulAPI").First();

            // Authenticate with PayPal
            // https://developer.paypal.com/docs/api/quickstart/environment/
            var config = new Dictionary<string, string>();
            config.Add("mode", credential.Mode);
            config.Add("clientId", credential.ClientId);
            config.Add("clientSecret", credential.ClientSecret);

            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);

            //if (credential.Mode == "live")
            //    BaseConstants.RESTSandboxEndpoint = BaseConstants.RESTLiveEndpoint;

            // https://developer.paypal.com/docs/api/quickstart/capture-payment/#capture-authorization
            // https://developer.paypal.com/docs/integration/direct/payments/capture-payment/
            var authorization = new Authorization()
            {
                id = transaction.AuthorizationId
            };

            var capture = new Capture()
            {
                amount = new Amount()
                {
                    currency = transaction.Currency,
                    total = transaction.PaymentGross.ToString()
                },
                is_final_capture = isFinalCapture
            };

            var responseCapture = authorization.Capture(apiContext, capture);`

**Comment by xiaoleih41** [comment]
Thank you for your questions.  Please make sure to follow the [.NET PayPal configuration](https://github.com/paypal/PayPal-NET-SDK/wiki/Configuration) to config your configuration file to live mode. Also, [issues169](https://github.com/paypal/PayPal-NET-SDK/issues/169) may help you solve your issue as well. Please let me know if you have any further questions.

**Comment by MDornian** [comment]
Unfortunately, we cannot setup anything in web.config as the same codebase is used for multiple environments; some of which are live and some of which are not.   It is strange that you mark it as a requirement because when we tested this, nothing was required in app.config or web.config.

**Comment by Aggravate** [comment]
Please let me know if you find a solution for this.

**Comment by pp-randy** [comment]
I think @xiaoleih41 meant  for you to try the workaround on this comment https://github.com/paypal/PayPal-NET-SDK/issues/169#issuecomment-251875150

where they are setting config again on the apiContext. 
```
var apiContext = new APIContext(accessToken);
apiContext.Config = config;
```

**Comment by MDornian** [comment]
Yes, that in fact works.  We needed to prove it worked in production before I could comment.

**Comment by pp-randy** [comment]
Thank you for confirming @MDornian. 

@Aggravate let us know if you need further help.

**Comment by Aggravate** [comment]
@pp-randy 
Sorry for the late answer. It works perfect that way :)
