### ISSUE TITLE
Cannot set company logo...

### ISSUE THREAD

**Issue by matthewrwilliams** [paypal/PayPal-NET-SDK#246]
This could be my own issue, but I cannot find where to set the company logo.  We run multiple sites and need to change the company logo for them. 

Any suggestions on how to implement this with the current SDK?

**Comment by xiaoleih41** [comment]
Please look into this [sample file](http://paypal.github.io/PayPal-NET-SDK/Samples/PaymentWithPayPalWithWebExperienceProfile.aspx.html) and create webprofile to change company logo. Please let me know if you have any further questions. thanks, Xiaolei

**Comment by matthewrwilliams** [comment]
Thank you for the response.  I am getting this to work in the sandbox, but not in production.  Do I need to remove the default logo?  I thought this code would override any logo set.  I am unable to find where the default logo is set.  It appears this has changed since the last time I was in the admin.

**Comment by matthewrwilliams** [comment]
Checking back on this... the brand name is updating just fine in production, but the logo is staying the same.  In the Sandbox, this is working with the logo and the brand name.  I am not doing anything different with the code.  Seems like this is potentially a bug as I have no code changes and Sandbox is behaving differently than Prod.  Really need to get this resolved so any help would be greatly appreciated.

**Comment by pp-randy** [comment]
What is the URL you are using for the production image? 

Since this is holding you up in your production integration I encourage you to reach out to PayPal Technical Support at https://www.paypal-techsupport.com/app/ask

**Comment by matthewrwilliams** [comment]
Technical support isn't helping unfortunately as they are asking about the SDK... I'm caught in a bit of a loop.  

I am using the same URL for Sandbox and Production.  Same code is used and only the creds are switched out based on the environment.  The Sandbox is displaying the logo perfectly.  Production is only showing the brand_name change for each of our sites and the default image which is set in PayPal directly.

Lost as to what to look at next.

**Comment by pp-randy** [comment]
What was your Technical Support ticket number?  I will do some follow up.

**Comment by pp-randy** [comment]
@matthewrwilliams can you provide the PayPal Technical Support ticket number?  
The ticket or reference number would look like 1703##-######

**Comment by pp-randy** [comment]
We did some testing and see that sandbox is allowing images that production will not.  Does your image meet the requirements here: [payment-experience/#definition-presentation](https://developer.paypal.com/docs/api/payment-experience/#definition-presentation)?

**Comment by matthewrwilliams** [comment]
Randy, sorry for the delay.  Here is my support ticket... I opened a new one earlier to see if this was the issue. (170326-000166)

My images did not meet the height and width requirements.  I updated that and I am still having the same issue.

**Comment by pp-randy** [comment]
Can you add the image URL to the support ticket?  

To clarify you are using the API [payment experience]( https://developer.paypal.com/docs/api/payment-experience/) option to do this?  I looked at the support ticket and it refers to profile changes so I want to double check.

**Comment by matthewrwilliams** [comment]
Done.  Thank you again for your help.  Yes, I am using this.  In fact I am using a lot of the code provided by xiaoleih41.

**Comment by pp-randy** [comment]
The image is working for me on a live test.  Can you view the html source of the PayPal landing page do a find for correlationId or get me token value from the URL?  

![image](https://cloud.githubusercontent.com/assets/6819909/24422244/7748475c-13be-11e7-847c-0865308b41cb.png)

**Comment by matthewrwilliams** [comment]
"correlationId": "8bf1cdb9dfbe6"

**Comment by pp-randy** [comment]
Everything looked good from what I can tell with how you are using the profile so that is good. On that note, I did more testing and set a Logo Image in the account profile I was testing with which does indeed appear to take precedence over the logo provided in the API call. 

I will follow up here shortly with a new issue in our REST API tracking repo since this is not an SDK issue at this point.

**Comment by pp-randy** [comment]
I have created https://github.com/paypal/PayPal-REST-API-issues/issues/56 for further follow up. Thank you for the help with identifying this issue.

**Comment by matthewrwilliams** [comment]
Randy, is my ticket still open?  I'd like to remove the default logo from my account so this will work.  If I could do that, it would resolve my issue for now.

**Comment by pp-randy** [comment]
This issue I closed since I am tracking the API issue here: https://github.com/paypal/PayPal-REST-API-issues/issues/56.  

I thought I saw a third party setup when reviewing your logs, so another account was the API caller.  I'm not sure which of the accounts has the picture you are seeing, but I think if you disable the logo it will work for you as a workaround.

**Comment by matthewrwilliams** [comment]
Unfortunately, I can't change the logo / disable it.  Here is what I put in the ticket.

We cannot see the Custom Payment Pages options when we choose Profile & Settings -> My Selling Tools

We have followed these directions:
https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1543&pmv=print&impressions=false&viewlocale=en_US

**Comment by pp-randy** [comment]
Yes, the Technical Support Ticket is still open. 
Try this URL:  `https://www.paypal.com/us/cgi-bin/webscr?cmd=_profile-page-styles`

If you see nothing here I will try to find out if another setting is causing this.

**Comment by matthewrwilliams** [comment]
That got me there.  I was able to drop the custom page and it's working as expected now.  I'll just pass the info for our default site so the logo is proper for them.  Thank you so much for the help!

**Comment by pp-randy** [comment]
I apologize Technical Support did not get to you sooner.  Maybe just drop them an email that this was resolved for you.

**Comment by matthewrwilliams** [comment]
Done.  Thank again for your help.  Much appreciated.

**Comment by crmb** [comment]
Thank you i had the same issue. Even though i had an old logo displaying, i had only the default "PayPal" page Style. (not custom styles).
Had to create a new one to put the logo.

**Comment by xiaoleih41** [comment]
@crmb Have you tried the link Randy has provided above? https://www.paypal.com/us/cgi-bin/webscr?cmd=_profile-page-styles
