### ISSUE TITLE
Getting back INTERNAL_SERVICE_ERROR from sandbox

### ISSUE THREAD

**Issue by battaile** [paypal/PayPal-NET-SDK#247]
Just started happening today for all requests, here's a debug_id: 947e96ea5b6ed

**Comment by pp-randy** [comment]
I'm seeing this for credit card payments when using credit_card model, but it seems to work for payment_card model.  

Are you seeing this with anything else other than credit card payments?  In the mean time, I will work on this credit_card issue further.

**Comment by battaile** [comment]
Thanks @pp-randy ,
 We've currently only got code that uses the credit_card model

**Comment by pp-randy** [comment]
I spawned a new issue in our Rest API tracking repository here: https://github.com/paypal/PayPal-REST-API-issues/issues/51.  Let use this going forward.

**Comment by battaile** [comment]
Looks like this got resolved sometime last night, no longer getting errors.
