### ISSUE TITLE
500 Error with Sale.Get in sandbox

### ISSUE THREAD

**Issue by allenjp** [paypal/PayPal-NET-SDK#248]
I receive a 500 error when trying to get a sale using Sale.Get in sandbox.  Error message: The remote server returned an error: (500) Internal Server Error.  

I've confirmed the apiContext and saleId are both populated.

Debug id 227e41afb02dc

**Comment by pp-randy** [comment]
I don't see the transaction id you are trying to look up in the sandbox.  Are you sure it was created in sandbox and not production?

**Comment by allenjp** [comment]
Hi Randy,

Thanks for looking into it, I have a suspicion you may be correct... bit of miscommunication among myself and my team here.  Can close this one out, much appreciated for investigating.
