### ISSUE TITLE
Using NGrok to test some webhooks invoice callbacks

### ISSUE THREAD

**Issue by jonasrdm** [paypal/PayPal-NET-SDK#250]
Hi!

I'm trying to use NGrok in order to test some webhooks invoice callbacks. The problem is, I keep getting :
_VALIDATION_ERROR","details":[{"field":"url","issue":"Not a valid webhook URL"}_

I've searched the docs, but I couldn't find what are the **possible causes** for this error. Do you guys have any idea? Could it have something to do with tunneling through NGrok?

Thx! :)

**Comment by pp-randy** [comment]
Are you getting this error trying to create the webhook?  Or is this an issue with actual webhook payload validation?  

Do you have a paypal-debug-id that you can provide?

**Comment by pp-randy** [comment]
The URL looks good to me and example documentation shows [NGrok examples](https://developer.paypal.com/docs/api/quickstart/create-webhook/).  I will most likely need to escalate internally for more information. 

Does it work with the webhook simulator? 

Also try going into the REST App and seeing if it works manually https://developer.paypal.com/developer/applications/

**Comment by pp-randy** [comment]
Actually, I tried the URL and got a 400 invalid host name, our logs seem to show this error as well.  Can you confirm the ngrok url is valid?

**Comment by jonasrdm** [comment]
Hey, I discovered the issue! Its was so Obvious... I'm so dumb! haha

The callback URL **HAS** to be https. I was trying to tunnel the non-secure generated url by NGrok. Just switched it to https and works like a charm.

Anyway, thank you very much for you attention to my issue! :) 

As a suggestion I think that maybe this exceptions could have some documentation listing the probable causes.

**Comment by pp-randy** [comment]
I'm glad you were able to resolve the issue.  Webhooks aside, does your URL actually work with http?

**Comment by jonasrdm** [comment]
Ngrok creates both, a http and a https tunnel. Both work, but with to Paypal it has to be https.
