### ISSUE TITLE
i am using visual studio non of any solution is working on it. guide me how to use it in vs17

### ISSUE THREAD

**Issue by UzairAshraf123** [paypal/PayPal-NET-SDK#251]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by xiaoleih41** [comment]
We haven't created VS 2017 solutions yet. The most latest solutions we have are good for VS 2013.  I am sending in this SDK enhancement request but it may take a while as VS 2017 is still pretty new.

**Comment by jphellemons** [comment]
@UzairAshraf123 what project type did you select? regular webforms or mvc web applications targetting .net full framework (4.5.x etc. ) do work.

**Comment by Telaran** [comment]
As a current workaround you'll might have a look at https://alastaircrabtree.com/cannot-open-vs-2015-web-project-in-vs-2017/

Still I would prefer a more dated version without workaround.

**Comment by bluk** [comment]
The [v2 beta of the SDK](https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta) should work with VS 2017. If there is still an issue, please leave a comment or open a new issue. Thanks.
