### ISSUE TITLE
Partner Attribute ID not present

### ISSUE THREAD

**Issue by bnelson365** [paypal/PayPal-NET-SDK#252]
### General information
There is no way to set the PayPal-Partner-Attribution-Id in the header of the token call. This is needed for all partners that are making API with 3rd party permissions. This is a fairly big issues as all partners will either have to fork their own instance or not use the SDK.
* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by pp-randy** [comment]
Is this functionality to set the value something you have already coded?  If you submit a pull request we will review it. 

If not, please let me know so we can review this further.

**Comment by xiaoleih41** [comment]
Actually, you don't have to pass it when you request an access token. You should pass it on the payments calls. The `Partner Attributes ID` is primary used to track money moving transactions.  Since `access token request` doesn't move any money, there's no reason to track it.

**Comment by pp-randy** [comment]
Closing the issue thanks to input from @xiaoleih41.

Further instructions on how to add the header can also be found here: 
[Make-Your-First-Call#2-configure-an-apicontext-object
](https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call#2-configure-an-apicontext-object)

Please let us know if further assistance is needed or if you have any additional questions.
