### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error.

### ISSUE THREAD

**Issue by thanhmcdowell** [paypal/PayPal-NET-SDK#253]
### General information

* SDK/Library version:  v1.8.0
* Environment: sandbox
* `PayPal-Debug-ID` values: 10719a52d21e4
* Language, language version, and OS: 

Here is the stacktrace I got back from the exception:

   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
   at PayPal.Api.Payment.Create(APIContext apiContext, Payment payment)

header response:
{
paypal-debug-id: 10719a52d21e4,10719a52d21e4
Content-Language: *
X-SLR-RETRY: 500
X-SLR-RETRY-API: /v1/payments/payment
Connection: close
Date: Mon, 24 Apr 2017 19:01:20 GMT
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2152463960%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Mon, 24 Apr 2017 19:31:20 GMT; domain=.paypal.com; path=/; Secure; HttpOnly,X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Server: Apache
Vary: Authorization
Content-Length: 209
Content-Type: application/json
}

**Comment by pp-randy** [comment]
Can you try updating the business account to Payments Pro in your [PayPal Developer Dashboard]( https://developer.paypal.com/developer/accounts/)? This might be a quick fix if you are able to.

Click on the account and you should have an option on the Profile tab.

**Comment by thanhmcdowell** [comment]
I forgot to mention one detail on last post.  This is for REST API.
My previous integration with NVP/SOAP API SDK is still working so I assume that account already have Payments Pro.    Am I missing something?

**Comment by pp-randy** [comment]
Yes, it appears you are missing the newer Pro package and you are attempting a Credit Card payment.  If adding Pro doesn't fix it, you may want to create a new sandbox business and REST App.  I see your current account is over 2 years old, so I am hoping you adding Pro with the profile fixes this and gets you up and running quicker.

**Comment by thanhmcdowell** [comment]
I created an REST app on existing account
here is the new debug id

{paypal-debug-id: bc6409199bfd7,bc6409199bfd7
Content-Language: *
X-SLR-RETRY: 500
X-SLR-RETRY-API: /v1/payments/payment
Connection: close
Date: Mon, 24 Apr 2017 22:45:36 GMT
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D276889176%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Mon, 24 Apr 2017 23:15:36 GMT; domain=.paypal.com; path=/; Secure; HttpOnly,X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Server: Apache
Vary: Authorization
Content-Length: 121
Content-Type: application/json
}

I'm trying to create new sandbox business acc and update to pro but having trouble confirming email from the sandbox paypal confirmation.  Do you have any suggestion how to get pass this?

**Comment by thanhmcdowell** [comment]
I created a new sandbox business account and new REST app and still receiving the same error
what am I missing here?

here is the info

{paypal-debug-id: 1367a2401c8b8,1367a2401c8b8
Content-Language: *
X-SLR-RETRY: 500
X-SLR-RETRY-API: /v1/payments/payment
Connection: close
Date: Mon, 24 Apr 2017 23:06:06 GMT
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3750035032%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Mon, 24 Apr 2017 23:36:07 GMT; domain=.paypal.com; path=/; Secure; HttpOnly,X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Server: Apache
Vary: Authorization
Content-Length: 121
Content-Type: application/json
}

**Comment by pp-randy** [comment]
I appreciate you creating the new account and REST app. Things are looking from; however,  I am having trouble reproducing.

Can you try this randomly generated card number I want to rule out an issue with the credit card you've been using `4670220796630874`.  

If this new number doesn't resolve I will escalate internally for further review.

**Comment by thanhmcdowell** [comment]
I still get the same 500 error with the card # you provided 4670220796630874.

Thank you for looking into it.

**Comment by pp-randy** [comment]
Are you able to provide the JSON request string that is generated so we can use it for further investigation?

**Comment by thanhmcdowell** [comment]
I found the issue.  My transaction was null.  However, I was hoping the error message would be something along the line of bad request instead of internal 500 error.

Thank you for the help!

**Comment by pp-randy** [comment]
Sorry for not identifying that myself, I was too concerned with trying to replicate using similar funding information that I missed the transactions being null. 

I will follow up further for a more helpful error to be provided.
