### ISSUE TITLE
JSON deserializing error when a PaymentsException is created

### ISSUE THREAD

**Issue by quynhrev** [paypal/PayPal-NET-SDK#255]
Whenever I catch a `PaymentsException` (due to duplicate batch requests), Serilog logs a JSON deserializing error. The log message is below:

`Error while deserializing JSON: Could not find member 'link' on object of type 'ErrorDetails'. Path 'details[0].link', line 1, position 283.`

This class should have a `link` property but doesn't - [ErrorDetails.cs](https://github.com/paypal/PayPal-NET-SDK/blob/65590165044711549b6e4fa981c2f30b2e3c1027/Source/SDK/Api/ErrorDetails.cs).

Below is a sample error response. It is parsed here in the constructor of [PaymentsException.cs](https://github.com/paypal/PayPal-NET-SDK/blob/65590165044711549b6e4fa981c2f30b2e3c1027/Source/SDK/Exception/PaymentsException.cs#L24):
```json
{
    "message": "User business error.",
    "debug_id": "d74e3c9f98699",
    "details": [
        {
            "field": "SENDER_BATCH_ID",
            "issue": "Batch with given sender_batch_id already exists",
            "link": [
                {
                    "href": "https://api.sandbox.paypal.com/v1/payments/payouts/U889SZFL45EUJ",
                    "method": "GET",
                    "rel": "self"
                }
            ]
        }
    ],
    "name": "USER_BUSINESS_ERROR",
    "information_link":  "https://developer.paypal.com/docs/api/payments.payouts-batch#errors"
}
```

Please look into this and update the SDK.

**Comment by xiaoleih41** [comment]
I am looking into this and will get back to you when I have an update.

**Comment by pp-randy** [comment]
We are still following up on the actual value being returned.  

I have also submitted a pull request to no longer throw an error for missing members https://github.com/paypal/PayPal-NET-SDK/pull/257.

**Comment by pp-randy** [comment]
I have migrated this to our REST API issues repository https://github.com/paypal/PayPal-REST-API-issues/issues/76.  Please follow this issue for further updates.
