### ISSUE TITLE
payflow_net SDK

### ISSUE THREAD

**Issue by githubvl** [paypal/PayPal-NET-SDK#256]
### General information

* SDK/Library version: Payflow_dotNET.dll - 4.3.3.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:  Microsoft .NET 4.5, Microsoft Windows 8.1 Enterprise

### Issue description

We are using PayflowPro Recurring Payment service (Australia) in our application. We are using API Payflow_dotNET.dll to integrate with this service. Since last 2 months we are not able to connect to the sandbox site - "pilot-payflowpro.paypal.com" through our application .NET code. We are getting error "Failed to connect to host Input Server Uri = https://pilot-payflowpro.paypal.com". Previously we were able to connect to "pilot-payflowpro.paypal.com" through our application.

We had raised ticket to Paypal support (www.paypal-techsupport.com). On 9 Apr 2017 they have replied that - "As of now, the payflow_net sdk is still not supporting TLS1.2, however the github developer will provide an update version of payflow_dotNet SDK probably in next month. Kindly check in github for any update."

Can you please provide us with an update on the updated version of payflow_dotNet SDK so that we would be able to connect to the sandbox site (pilot-payflowpro.paypal.com).

We would really appreciate your support on this.

Thanks,
Ajit

**Comment by awesmdiver** [comment]
Aijit

I have a recompiled version of the old SDK that is compatible with TLS 1.2 but I haven't released it yet as I am not 100% sure it is fully 100% backwards compatible, long story.

However, if you email me at awesmdiver+github@gmail.com I can send you can copy for your review and testing.

Todd
