### ISSUE TITLE
General Question Regarding Declined Payment

### ISSUE THREAD

**Issue by ianscarroll** [paypal/PayPal-NET-SDK#259]
Can someone please provide a complete list of what Payment.state might contain.  "Failed" isn't returned for declined payments so how do we identify a successful transaction from any failure?

        // Summary:
        //     The state of the payment, authorization, or order transaction. The value
        //     is:created. The transaction was successfully created.approved. The buyer
        //     approved the transaction.failed. The transaction request failed.
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "state")]
        public string state { get; set; }

Thanks!

**Comment by pp-randy** [comment]
The [payment_create_response](https://developer.paypal.com/docs/api/payments/#payment_create_response) shows the three values for state `created, approved, failed`.  Mainly these are used for PayPal funded payments.  If the payment execute returns INSTRUMENT_DECLINED you redirect the buyer back to the approval_url and ask them to select a different funding source.  Uncompleted payments do not remain in the system. 

State will be approved when the payment completes. Under transactions you will find related_resources, which will show you the completed transaction.

**Comment by ianscarroll** [comment]
Many thanks!

**Comment by pp-randy** [comment]
If you have other questions,  feel free to ask them.

**Comment by ianscarroll** [comment]
I'm sorry but I'm lost on how to use the Sandbox for negative testing.  Can you please explain the BEST way to test declined processing errors from PayPal?  Where and how can I generate INSTRUMENT_DECLINED when executing a payment in Sandbox mode using the REST API service?

Thanks again!

**Comment by pp-randy** [comment]
Unfortunately, the REST API does not support negative testing.  You can mock the payment execute with a mocking tool, if you want, and still redirect the buyer back to the sandbox, as a possible workaround.
