### ISSUE TITLE
mode live vs production

### ISSUE THREAD

**Issue by mnemanov** [paypal/PayPal-NET-SDK#265]
### General information

* SDK/Library version: 1.8.0
* Environment: Production
* Language, language version, and OS: .Net - Windows server

### Issue description

In my web.config for production we set mode to 'production' instead of 'live' and we were getting 401 unauthorized errors.

We are also using checkout.js on the client side which has a env variable which needs to be set to 'production'.

We were using the same value in the web.config for both places so when I changed the production value to 'live' the button would not render because checkout.js required 'production'.

I have two suggestions:
A: If the value for mode is not valid, instead of defaulting to the sandbox endpoint it should throw an exception with a message that the mode needs to be 'live' or 'sandbox'. Such an exception would have saved us countless hours.

B: The SDK should treat production' the same as 'live' to be consistent with checkout.js (or checkout.js should use 'live' to be consistent with the SDK).

**Comment by xiaoleih41** [comment]
I agree with your suggestion. Do you mind to submit a pull request on this?

**Comment by mnemanov** [comment]
Pull request #266 created

**Comment by xiaoleih41** [comment]
@mnemanov  We are evaluating different options to solve this issue. Once we reach decision, will notify you.

**Comment by mnemanov** [comment]
Even if you are not ready to accept the value 'production' for the mode, at the very least pull my change to throw an exception, developers should know they set an incorrect value I think that would be much better than falling back to sandbox silently.

**Comment by xiaoleih41** [comment]
I understand. The decision will affect all SDKs so it takes time. I will follow up again.

**Comment by Sososlik** [comment]
same problem here, will this be fixed? it was difficult to figure out what was happening...

**Comment by pymendoza** [comment]
Encountered the same issue, although it should be easy enough to add another configuration or separate translation for the SDK or checkout.js setting.

**Comment by sucithrashanu** [comment]
Hi
Currently we do not have any stipulated timeline for the New release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
