### ISSUE TITLE
Refund INTERNAL_SERVICE_ERROR response

### ISSUE THREAD

**Issue by CerosWare** [paypal/PayPal-NET-SDK#270]
### General information

* SDK/Library version: **1.8.0**
* Environment: **Sandbox**
* `PayPal-Debug-ID` values: **ca159e0a93c16**
* Language, language version, and OS: **C# 5.0/.NET Framework 4.5/Windows 10**

### Issue description

I'm getting a **_500: INTERNAL_SERVICE_ERROR_** response after calling Sale.Refund:

`RefundRequest refReq = new RefundRequest();`
`Sale.Refund(apiContext, saleID, refReq);`

I've tried setting an **Amount** object, but it also fails.

`RefundRequest refReq = new RefundRequest();`
`Amount amount = new Amount {`
`total = sale.amount.total,`
`currency = sale.amount.currency`
`};`
`refReq.amount = amount;`
`Sale.Refund(apiContext, saleID, refReq);`

My **Sandbox Business Account** settings are:
- Payment Review: **On**
- Negative Testing: **Off**

**Comment by xiaoleih41** [comment]
Please turn the payment review off.  As the payment is on hold, it has caused issue. In production environment, you should be able to log into the account to cancel the payment under review not through refund as you haven't received the money yet.

**Comment by CerosWare** [comment]
Hello:

Thanks for your response. We've contacted a **Sales Engineer**, and after analyzing the case (and considering your reply), our accounts will be configured by our **Account Manager** to stop receiving **Pending** transactions.

Cheers.
