### ISSUE TITLE
Paypal Sandbox Webhook

### ISSUE THREAD

**Issue by pavit26** [paypal/PayPal-NET-SDK#271]
Hello I am using the following setup

Created paypal merchant and customer sandbox accounts
Configured paypal REST API app
Added a webhook url to my server and have validated that it works using the webhook simulator
Used the Express Checkout javascript implementation found here
I am able to make successful payments when viewing the notifications in sandbox but no webhook is ever triggered???

**Comment by lneninger** [comment]
How it was resolved?
