### ISSUE TITLE
How do I Arrange PayPal SDK Files On An ASP.Net Website ?

### ISSUE THREAD

**Issue by mikepstuff** [paypal/PayPal-NET-SDK#272]
I have the latest PayPal-NET-SDK working fine as a project on my desktop using Visual Studio 2015.  However, it does not work on a website.  I think it has something to do with the file/folder arrangement. I can find no instructions as to how copy which files and where to do this.  When I run paymentwithpaypal.aspx it gives the error:
Request
No payload for this request.

Response
The type initializer for 'PayPal.Sample.Configuration' threw an exception.
No payload for this response.

It appears to stop at this line in paymentwithpaypal.aspx.cs 
var apiContext = Configuration.GetAPIContext();

PayPal tech support is no help.  They want more detailed error text but the SDK does not display any.

**Comment by xiaoleih41** [comment]
Did you try to use **publish** option in visual studio? It might be an issue between your hosting company and you.

**Comment by mikepstuff** [comment]
I'm not deploying it as a web app to Microsoft Azure.  I'm using ASP.net 4.xx hosting.  I want to be able to copy the files and structure via ftp to the website and run it from there.  I have everything copied but it gives me no hint of what's going wrong.  Just that generic error.
For example: I'm just trying to get their sample PaymentWithPayPal.aspx to run
I copied their same structure to the website.  see attached
![untitled](https://user-images.githubusercontent.com/29930411/27932475-e07b66ea-626b-11e7-8fba-909e0cd9951a.png)

**Comment by mikaey** [comment]
Hi @mikepstuff -- FYI, Visual Studio's "publish" function will give you the option to publish via FTP -- you just have to click on the "Custom" option when it asks you to select a publish target.

**Comment by mikepstuff** [comment]
Hello mikaey.  Thanks much for your reply.  I tried that and get this error when I try to publish;
The target "GatherAllFilesToPublish" does not exist in the project.	PayPal.SDK.Sample.VS.2013
I have Googled this and seem to get dozens of recommendations which I cant seem top get to work.  Any ideas?

**Comment by pp-randy** [comment]
I do not advise publishing the samples to a public facing web server; more so, if you've added your own credentials.   With that said this is what I did to resolve the issue locally, I believe the problem stems from using a VS 2013 project with VS 2015. 

Unloaded the project by right clicking the project in the solution explorer:
![image](https://user-images.githubusercontent.com/6819909/28023483-a5e62836-6553-11e7-9944-8bffe9daf0dc.png)

I removed the Condition parameter on the `MSBuildExtensionsPath32` line.  
![image](https://user-images.githubusercontent.com/6819909/28025985-6e35257a-655a-11e7-95d4-3b460d01db0a.png)

After reloading the project Visual Studio made additional modifications; however, the publish began to work.

The other solution I've seen is to add the Target tag below the lines above, but that appears to move all files even the .CS ones during publish. 
`<Target Name="GatherAllFilesToPublish"></Target>`

**Comment by mikepstuff** [comment]
Randy:  Thanks much.  I will try this and report back:-)

**Comment by mikepstuff** [comment]
Randy;  That fixed the web publishing error.  It copied everything to the website into the same folders as before.  Still the same generic error....
![untitled2](https://user-images.githubusercontent.com/29930411/28037947-2ea51a10-658b-11e7-83f9-2d0f0f2b9479.png)

**Comment by pp-randy** [comment]
If you haven't enabled logging, can you try and see if we can get a more specific error?  
https://github.com/paypal/PayPal-NET-SDK/wiki/Configuration#log4net-config-settings-optional

Also I did find this on Remote Debugging: https://msdn.microsoft.com/en-us/library/y7f5zaaa.aspx, I have never tried it but it might be a second option.

**Comment by mikepstuff** [comment]
Randy:  I think you may be onto something.  That PayPal.SDK.Sample.log file never updates on the web.  It only gets modified on my desktop.  Here's the web.config file:
<?xml version="1.0"?>
<configuration>
  <configSections>
    
    <section name="paypal" type="PayPal.SDKConfigHandler, PayPal"/>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net"/>
  </configSections>
  
  <paypal>
    <settings>
      
      <add name="mode" value="sandbox"/>
      <add name="connectionTimeout" value="360000"/>
      <add name="requestRetries" value="3"/>
        
      <add name="clientId" value="NOTE: I HAVE THE REAL WORKING ONE IN HERE"/>
      <add name="clientSecret" value="ENOTE: I HAVE THE REAL WORKING ONE IN HERE"/>
           
    </settings>
  </paypal>
  
  <log4net>
    <appender name="FileAppender" type="log4net.Appender.FileAppender">
      <file value="PayPal.SDK.Sample.log"/>
      <appendToFile value="true"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] %message%newline"/>
      </layout>
    </appender>
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="FileAppender"/>
    </root>
  </log4net>
  
  <appSettings>
    
    
    <add key="PayPalLogger" value="PayPal.Log.Log4netLogger"/>
  </appSettings>
  
  <system.web>
    <compilation debug="true" targetFramework="4.5.1"/>
   
  </system.web>
  <system.webServer>
    <defaultDocument enabled="true">
      <files>
        <add value="~/Default.aspx"/>
      </files>
    </defaultDocument>
  </system.webServer>
</configuration>

**Comment by pp-randy** [comment]
Most likely you don't have access to write the log file is my guess.  I will see if I can replicate if that is creating a larger issue.

**Comment by mikepstuff** [comment]
I'll build a page that will manually update the file to make sure it's not a permissions issue....

**Comment by mikepstuff** [comment]
I just tested a simple file input output from a webpage in the same folder.  It successfully appended a line to the file

**Comment by pp-randy** [comment]
I was looking over https://stackoverflow.com/questions/4398334/the-type-initializer-for-myclass-threw-an-exception

The Static constructor is only looking for clientId and clientSecret
https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/Utilities/Configuration.cs#L15-L16

You have both of those. 

Maybe update here to write out more details of the inner exception 
https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/BaseSamplePage.cs#L24

**Comment by pp-randy** [comment]
I changed the name of clientSecret in my Web.config and this is what the InnerException looks like

![image](https://user-images.githubusercontent.com/6819909/28190122-df441ae6-67ee-11e7-8e69-52ba5dfbfc88.png)

So I think this will be the next piece of data to capture.

**Comment by mikepstuff** [comment]
It looks like the log file is getting locked up somewhere.  It's trying to write the normal events on one page and then the error page (configuration.cs) doesn't have access to it.  I experimented with this.  If you write any code with syntax errors you get the same result "no payload".  I'm going to try writing to a separate log file to trap which line it's failing on.

**Comment by pp-randy** [comment]
This seems like a lot of effort on your end for an issue that could be with just the sample app on your server.  You might want  considering using the SDK outside of the sample app at this point, in new simple web app to see if it works on your server.

**Comment by mikepstuff** [comment]
It is a lot of trouble.  I have dedicated an entire domain and site for testing.  I'm simply trying to process a simple one item payment like using the PaymentsWitPayPal.aspx page.   PayPal offers no simple solution other than the ENTIRE SDK which relies on thousands of lines of code.  They offer no other example other than this.  I have talked to several people at tech support.  They keep referring me back to the SDK.

**Comment by pp-randy** [comment]
I apologize you have been having these issues. 

Have you seen our JavaScript library [Checkout JS](https://github.com/paypal/paypal-checkout)?   It can be integrated without server requests.  

Any of the REST calls for PayPal can be made without an SDK.   You are either submitting a GET or a POST for most things and its all in JSON.  https://developer.paypal.com/docs/integration/direct/make-your-first-call/

**Comment by mikepstuff** [comment]
I was trying to stay in the .Net family.  But I'll do anything to make this thing work.  I'll check those out.  Thank you Randy!

**Comment by pp-randy** [comment]
Hey I found this at the Demo Site https://demo.paypal.com/us/demo/navigation?merchant=bigbox&page=shoppingCart

I'm looking over this now   https://demo.paypal.com/us/demo/download?capability=checkOutWithPaypal&lang=CSharp&api=rest

**Comment by pp-randy** [comment]
@mikepstuff so this doesn't use the SDK, maybe check it out https://demo.paypal.com/us/demo/download?capability=checkOutWithPaypal&lang=CSharp&api=rest

**Comment by mikepstuff** [comment]
I remember I tried that one too and couldn't get it to work.  But I think I have the missing files that were giving me a problem now.  I'll let you know.  Thank you again Randy!

**Comment by mikepstuff** [comment]
I got this demo working on my desktop in Visual Studio 2015:  https://demo.paypal.com/us/demo/download?capability=checkOutWithPaypal&lang=CSharp&api=rest
However, when I publish it to a website it stops when it posts to PayPal.  See attached.

![error](https://user-images.githubusercontent.com/29930411/28292462-12c36a30-6b1d-11e7-9630-8db75d9dc493.png)

**Comment by mikepstuff** [comment]
Application.log file:
2017-07-17 18:04:34,940 INFO  Index.Page_Load 
Sandbox Environment: True
CSRF Token : F66127F9B99E2D4B208F08E088F17B549C325E2D182E07814AEAE5C8D6DB859A

2017-07-17 18:04:44,134 INFO  PayPalMethods.getAccessToken 
Service URL: https://api.sandbox.paypal.com/v1/oauth2/token
Request: grant_type=client_credentials
Response: 
{
  "scope": "https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.*",
  "nonce": "2017-07-17T22:04:44ZXx9jnRGI6AnvIubAJVrSGYBdsnRxF_TpxQc0dkDitQY",
  "access_token": "A21AAGrhUZ8lq23dXLYt6msZVeA1RRgCYpGNxyL-s5rQ0xM-yVAmYSV-CUd-D2K1JOLq1giX0CNkAEZiQINy000h98nNgLtBQ",
  "token_type": "Bearer",
  "app_id": "APP-80W284485P519543T",
  "expires_in": 32400
}

2017-07-17 18:04:44,942 INFO  PayPalMethods.getApprovalUrl 
Service URL: https://api.sandbox.paypal.com/v1/payments/payment
Request: {
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "320",
        "details": {
          "shipping": "2.00",
          "subtotal": "300",
          "tax": "5",
          "insurance": "10",
          "handling_fee": "5",
          "shipping_discount": "-2"
        }
      },
      "description": "Creating a payment",
      "custom": "",
      "item_list": {
        "items": [
          {
            "name": "camera2",
            "quantity": "1",
            "price": "300",
            "sku": "1",
            "currency": "USD"
          }
        ],
        "shipping_address": {
          "recipient_name": "Jane Doe",
          "line1": "55 East 52nd Street",
          "line2": "21st Floor",
          "city": "New York",
          "state": "NY",
          "postal_code": "10022",
          "country_code": "US"
        }
      }
    }
  ],
  "payer": {
    "payment_method": "paypal"
  },
  "intent": "sale",
  "redirect_urls": {
    "cancel_url": "http://localhost:53594/Cancel.aspx",
    "return_url": "http://localhost:53594/Pay.aspx"
  }
}
Response: 
{
  "id": "PAY-03J0880342866442LLFWTI7I",
  "intent": "sale",
  "state": "created",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "amount": {
        "total": "320.00",
        "currency": "USD",
        "details": {
          "subtotal": "300.00",
          "tax": "5.00",
          "shipping": "2.00",
          "insurance": "10.00",
          "handling_fee": "5.00",
          "shipping_discount": "-2.00"
        }
      },
      "description": "Creating a payment",
      "custom": "",
      "item_list": {
        "items": [
          {
            "name": "camera2",
            "sku": "1",
            "price": "300.00",
            "currency": "USD",
            "quantity": 1
          }
        ],
        "shipping_address": {
          "recipient_name": "Jane Doe",
          "line1": "55 East 52nd Street",
          "line2": "21st Floor",
          "city": "New York",
          "state": "NY",
          "postal_code": "10022",
          "country_code": "US"
        }
      },
      "related_resources": []
    }
  ],
  "create_time": "2017-07-17T22:04:45Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-03J0880342866442LLFWTI7I",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-1EY77385J6711893J",
      "rel": "approval_url",
      "method": "REDIRECT"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-03J0880342866442LLFWTI7I/execute",
      "rel": "execute",
      "method": "POST"
    }
  ]
}

**Comment by pp-randy** [comment]
It looks like things are going in the right direction.  The failure appears to be at the PayPal site now.  You had no issues other than logging with the Payment Create?  

Try a buyer account instead of guest checkout to see if that works.   You can create a sandbox buyer account on the Developer site here after logging in https://developer.paypal.com/developer/accounts/.

**Comment by mikepstuff** [comment]
I get the same results regardless which button I press.  I don't get a chance to enter CC or Paypal buyer account info.
![error2](https://user-images.githubusercontent.com/29930411/28323411-b607f86c-6ba6-11e7-8263-6bf58b905e98.png)

**Comment by pp-randy** [comment]
Your previous post had an API response for `PAY-4YG484187F7773232LFWSTGQ` in the logs, was that from the server deployment?  If so, to be clear you are redirected to PayPal when the error occurs?  What is the initial page you see at PayPal?

**Comment by mikepstuff** [comment]
The transactions won’t match because the log file locks up every time I try it.  I get the same result.  But I used a screenshot from another transaction.

 

Here’s where I loaded the demo:

 

http://www.stuffsoftware.net/index.aspx

 

You can try it yourself.

**Comment by mikepstuff** [comment]
Now it's giving me an error:


The remote server returned an error: (500) Internal Server Error. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.

Source Error: 



Line 97:         var approvalUrl = "";
Line 98: 
Line 99:         var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
Line 100:        using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
Line 101:        {
  

 Source File:  e:\web\stuffsof\App_Code\PayPalMethods.cs    Line:  99

**Comment by mikepstuff** [comment]
Then I try it again and I get the PayPal we're sorry page.  Doesn't seem to be consistent.

**Comment by mikepstuff** [comment]
Definitely appears to be intermittent.  I got it to work once then it goes from the paypal we're sorry page to this:
![error3](https://user-images.githubusercontent.com/29930411/28329886-8f692678-6bb9-11e7-848e-bb5f60b2cf6f.png)

**Comment by pp-randy** [comment]
What .NET Framework version are you using locally?

https://github.com/paypal/tls-update#net

**Comment by pp-randy** [comment]
Just ran a test on your URL and it was working for me.  Did you make changes since your last update?

![image](https://user-images.githubusercontent.com/6819909/28334347-76c36410-6bc0-11e7-8417-aaf2b767dc2d.png)

**Comment by mikepstuff** [comment]
No.  I made no change.  It appears to be intermittent.  Sometimes I get this too:
![error4](https://user-images.githubusercontent.com/29930411/28334588-92ea514a-6bc9-11e7-894b-b5041988692f.png)

**Comment by mikepstuff** [comment]
Everything, website, web.config and project are all setup as .Net version 4.5

**Comment by pp-randy** [comment]
That image shows a payment decline, you might want to try a smaller amount and/or a different funding source.

If you are using Guest Checkout use a randomly generated card on step 4 of this FAQ just click the button https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413

**Comment by mikepstuff** [comment]
Yeah.  You're right.  I think since it's intermittent, I'll assume it's set up correctly.  I'll start tweeking it for my specific needs.   I think you got me far enough along with all your help.  I want you to know I really appreciate your attention to this!

**Comment by pp-randy** [comment]
No problem, sorry the SDK didn't work out.  Glad we found a way forward.
