### ISSUE TITLE
Refund Payment giving 401 Not Authorized

### ISSUE THREAD

**Issue by alwydl** [paypal/PayPal-NET-SDK#273]
I'm trying to use the Refund in Sandbox, but it is giving me a Not Authorized response.
My code:

     `try
            {
                var config = ConfigManager.Instance.GetProperties();
                var accessToken = new OAuthTokenCredential(config).GetAccessToken();
                var apiContext = new APIContext(accessToken);

                var payment = new PaypalPaymentREP().GetProfile(payID);
                
                var refund = new RefundRequest()
                {
                    //amount = new Amount()
                    //{
                    //    currency = "BRL",
                    //    total = "50.00"
                    //}
                };
                var response = Sale.Refund(apiContext, payment.SaleID, refund);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest("Bad Request:" + ex.ToString());
            }`

The Response I get: 
{"name":"PERMISSION_DENIED","message":"Permission denied.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#PERMISSION_DENIED","debug_id":"c3c1d477d3981"}

Although my config for payment review is off, all my payments test appear as pending. Don't know if this might be  the issue.

Any thoughts?

**Comment by xiaoleih41** [comment]
I don't see any transaction in this account. Where did you get the `saleId`?

**Comment by alwydl** [comment]
I made a payment from andre-buyer@shappa.com.br to andre@shappa.com.br. 
The paymentID is

**Comment by xiaoleih41** [comment]
andre@shappa.com.br is not a confirmed email address therefore PayPal won't recognize it is linked to a PayPal account. Please create a brand new business account under developer.paypal.com and the email address should be confirmed by default.

**Comment by alwydl** [comment]
Ok, Done it. Now the payments are directly approved. Or when created as a Brazilian acc in Sandbox.paypal.com the email is not directly confirmed, or something else happened when I came from my live account to sandbox.

But I still get the 401, not authorized.

Payment from alwydl-buyer@gmail.com to alwydl-facilitator@gmail.com
Response => information_link\":\"https://developer.paypal.com/webapps/developer/docs/api/#PERMISSION_DENIED\",\"debug_id\":\"e71cb51ccb594\"}"

PaymentID: PAY-31M282349R8089048LFR3EUQ
saleID: 2XY34989VB1957120

**Comment by pp-randy** [comment]
@alwydl would you be able to provide another debug_id?  Unfortunately, I was not able to find the logs on our end.

**Comment by alwydl** [comment]
Hi @pp-randy,

I tried the same payment as before (PaymentID: PAY-31M282349R8089048LFR3EUQ saleID: 2XY34989VB1957120) and got this debug_id bac083b237734.

However, when I tried a new payment and refund, from scratch, it is working now. Same code I had before. An example PaymentID: PAY-7GW494062G926433RLFXCQRY saleID: 2XA054396J317351T.
If it appears again, I'll post it here.

**Comment by pp-randy** [comment]
I appreciate you looking. Yeah, let us know if this comes up again.
