### ISSUE TITLE
SDK Ignores Mode Set In Code

### ISSUE THREAD

**Issue by jamesmundy** [paypal/PayPal-NET-SDK#274]
### General information

* SDK/Library version: 1.8.0
* Environment: Production and Sandbox
* Language, language version, and OS: .NET 4.5.2 (in a console app)

### Issue description
The SDK says you can configure the Paypal SDK via a dictionary object rather than the config file setting values.

```
var config = ConfigManager.Instance.GetProperties();
            var liveConfig = new Dictionary<string, string>
                                  {
                                      {"mode", "live"},
                                      {"clientId", "XXXXXXXXXXXXXXXXXXX"},
                                      {"clientSecret", "XXXXXXXXXXXXXXX"}
                                  };
            _liveToken = new OAuthTokenCredential(liveConfig).GetAccessToken();
            _liveContext = new APIContext(_liveToken);
```
instead of:

```
<paypal>
    <settings>
      <add name="mode" value="live" />
      <add name="clientId" value="XXXXXXXXXXXXXXXXXXXXXXXXXX" />
      <add name="clientSecret" value="XXXXXXXXXXXXXXXXXXXXXXXXXX" />
    </settings>
  </paypal>
```

Creating the OAuth token goes to the correct API endpoint based on the mode value but later on when making a payment using the context we created it sends the request to the mode set in the app's config file, not the mode set when creating the context.

If you remove the mode from the config file all requests are sent to sandbox as that is the default.

**Comment by jamesmundy** [comment]
After a little investigation and downloading the source I've managed to solve the issue with this code:
```var liveConfig = new Dictionary<string, string>
                                  {
                                      {"mode", "live"},
                                      {"clientId", "XXXXXXXXXXXXXXXXXXXXX"},
                                      {"clientSecret", "XXXXXXXXXXXXXXXX"}
                                  };
            _liveToken = new OAuthTokenCredential(liveConfig).GetAccessToken();
            _liveContext = new APIContext(_liveToken);
            _liveContext.Config = liveConfig;
```
I needed to set the config of my `_liveContext` to the same value as I proved to `OAuthTokenCredential`.
Unless I missed something it was definitely not clear I had to do that. It's not what you do on [this page](https://github.com/paypal/PayPal-NET-SDK/wiki/Quick-Start).

Inside `OAuthTokenCredential` there is a config property which is used to get the AccessToken. It might be good if APIContext had a constructor that took an `OAuthTokenCredential` (with a public config property) rather than a token and used it something like this:

```
public APIContext(OAuthTokenCredential credential) : this(credential.GetAccessToken())
        {
            this.Config = credential.Config;
        }
```

You could then use the SDK like this:

```
var liveConfig = new Dictionary<string, string>
                                  {
                                      {"mode", "live"},
                                      {"clientId", "XXXXXXXXXXXXXXXXXXXXXXXX"},
                                      {"clientSecret", "XXXXXXXXXXXXXXXXXXXXXXXXXXX"}
                                  };
            var credential = new OAuthTokenCredential(liveConfig);
            _liveContext = new APIContext(credential);
```
To me this seems nicer but I've only taken a quick look at the SDK so I'm sure there may be some reasons that this isn't possible 😄

**Comment by pp-randy** [comment]
There is an open bug issue for the need to set `.Config` again https://github.com/paypal/PayPal-NET-SDK/issues/169.

**Comment by pp-randy** [comment]
Thank you for the suggestion.  If you want to submit a pull request, we would be happy to review it.

**Comment by jamesmundy** [comment]
Thanks Randy, I'll try and get around to do that this week.

**Comment by pp-randy** [comment]
Closing in favor of existing bug https://github.com/paypal/PayPal-NET-SDK/issues/169.
