### ISSUE TITLE
Generated link in Sandbox seems invalid

### ISSUE THREAD

**Issue by JPVenson** [paypal/PayPal-NET-SDK#275]
### General information

* SDK/Library version: 1.8.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: Test Id: PAY-1TE629799B063322ELFRVISY
* Language, language version, and OS: Windows, Englisch, Asp.net call

### Issue description

After the call of payment.Create i got an valid object with 3 links. When i tried to redict to the approval url, the server sends a ERR_CONNECTION_RESET.

**Comment by JPVenson** [comment]
Generated Link:
https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-6MP71306HE720420R

**Comment by xiaoleih41** [comment]
I clicked on the link. it let me to log in with my sandbox account and after that is finished, I was redirected to your site to log in to your site account. It works for me. What exact page, did you get that error?

**Comment by JPVenson** [comment]
On the sandbox page, but it seems to work after i have cleared all cookies from the www.paypal.com domain ... but not the sandbox one's. Strange.

Can be closed

**Comment by xiaoleih41** [comment]
Close the ticket per request.
