### ISSUE TITLE
 "payee_metadata_info" object doesn't actually exist

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-NET-SDK#277]
Original Issue: https://github.com/paypal/PayPal-REST-API-issues/issues/118

### General information
The REST API documentation details a "payee_metadata_info" object, however, that object doesn't seem to exist in the actual API.

* Environment: Production (probably Sandbox as well)
* `PayPal-Debug-ID` values: Not applicable
* Language, language version, and OS: PayPal .NET SDK 1.8.0

### Issue description
The "payee_metadata_info" is detailed in the documentation ( https://developer.paypal.com/docs/api/payments/#definition-payee_metadata_info ) however, that object does not actually seem to exist in the API.

We have downloaded and installed the PayPal .NET SDK (version 1.8.0) into Visual Studio. So far, every object in the API documentation is available in the API, except for the "payee_metadata_info" object. 

I also downloaded the source code for the API, and nowhere in that source could I find any mention of the "payee_metadata_info" object.

Though the API documentation contains the "payee_metadata_info" object, that object just simply does not seem to exist in the API.

Am I missing something? How do we use the "payee_metadata_info" object?

**Comment by pp-randy** [comment]
@dsyno I have moved your issue here.

**Comment by dsyno** [comment]
Thank you, Randy. What's your idea on an ETA for this actually being fixed and available in the SDK?

**Comment by pp-randy** [comment]
I do not have an ETA, but will ask the team to give it some priority.

**Comment by pp-randy** [comment]
We are following up still on an SDK update.  The object will be https://developer.paypal.com/docs/api/payments/#definition-payee_display_metadata instead of payee_metadata_info.

**Comment by dsyno** [comment]
Thank you, Randy. ETA for when it should be available?

**Comment by dsyno** [comment]
Paging Randy. ETA for when it should be available?

**Comment by bluk** [comment]
The `PayeeDisplayMetadata` is released in [v1.9.1](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.9.1). Thanks for your patience.
