### ISSUE TITLE
Create payout page 

### ISSUE THREAD

**Issue by aviyi** [paypal/PayPal-NET-SDK#278]
The  Redirect to PayPal to approve the payment... link not shown after making request

**Comment by xiaoleih41** [comment]
Can you please provide more detail on which link did not show and where was it expected. Please also provide the `DebugId` associated with the API call.

**Comment by aviyi** [comment]
In the Payout section in the Create a payout link . when i am clicking on try it button , I expect the link(The Redirect to PayPal to approve the payment...)  to appear , in the PayoutCreate.aspx

**Comment by pp-randy** [comment]
Payouts send money from your account to another account.  Can you explain what you are wanting to do and I will try to guide you to the correct solution.  Are you wanting to send or receive money?

**Comment by aviyi** [comment]
Ok Thanks , i want a serivce like adaptive payment ,I realized that now
this service is not supported, what is the replacement of it?


2017-08-08 17:56 GMT+03:00 Randy <notifications@github.com>:

**Comment by pp-randy** [comment]
Adaptive Payment can do many things.  Can you provide more details?  

The Orders API, part of are newer Marketplace offering is worth looking at if you are looking to capture partner fees https://developer.paypal.com/docs/api/orders/.

I would need to know more about what your expected payment flow would be before being able to suggest which APIs to use.

**Comment by aviyi** [comment]
Ok, I want to do something like that, once the customer pays me money, I
want to transfer part of the sum to several different vendors, how can I do
that?

2017-08-09 17:50 GMT+03:00 Randy <notifications@github.com>:

**Comment by pp-randy** [comment]
If you want to be the initial receiver, you can accept the payment then out Payouts. 
https://developer.paypal.com/docs/api/payments.payouts-batch

**Comment by pp-randy** [comment]
Here is more details on the Markeplaces as well https://developer.paypal.com/docs/marketplaces/orders/integration-guide/.

If you choose this, then I would highly encourage you will need to visit the contact us link to get approval before you do any development work.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
