### ISSUE TITLE
NuGet Package is outdated

### ISSUE THREAD

**Issue by tomkerkhove** [paypal/PayPal-NET-SDK#279]
The latest official release was [v1.8.0](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.8.0) in **november 2016**.

Are there plans to ship a new release since the current version is broken, but fixed in this repo.
Example of this is #185.

**Comment by pp-randy** [comment]
We are following up on a new release.

**Comment by tomkerkhove** [comment]
Thank you, would be great since I know have to create "hacks" that are fixed here already..

**Comment by jphellemons** [comment]
@pp-randy is that new release compatible with .net Core? And is there an ETA?  👍

**Comment by pp-randy** [comment]
We have the new release https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.9.0

@jphellemons this is still version 1.  A version 2 in the works should support .net core.

**Comment by pp-randy** [comment]
Closing the issue now that I see the updated version on NuGet.

**Comment by tomkerkhove** [comment]
This is awesome, thanks @pp-randy!
