### ISSUE TITLE
Payment List Pagination

### ISSUE THREAD

**Issue by julpane** [paypal/PayPal-NET-SDK#280]
### General information

* SDK/Library version: 1.8.0
* Environment: Sandbox
* Language, language version, and OS: C#, windows 10

### Issue description
Pagination get payment list with start_index param return same with some previous data .
First call start_index = 0, next call start_index +=10.
count param = 10

Method used: 
![paypal query](https://user-images.githubusercontent.com/26126973/29104318-eef4a554-7cee-11e7-8ea6-729ec637f0c2.PNG)

Return payment list for first call and next call:
![paypal 1](https://user-images.githubusercontent.com/26126973/29104278-b924f29e-7cee-11e7-9d04-7ffc4377d440.PNG)
![paypal 2](https://user-images.githubusercontent.com/26126973/29104279-b92b36ae-7cee-11e7-8a62-816109201b0b.PNG)

**Comment by pp-randy** [comment]
For Payment List, it appears start_index should start at 1. 
https://developer.paypal.com/docs/api/payments/#payment_list

This only explains 1 of the duplicate values but not both.  I will do some additional testing on my end and follow up further.

**Comment by pp-randy** [comment]
Appears the documentation is incorrect from my testing so start_index would be 0.

**Comment by pp-randy** [comment]
Since this is not an SDK issue, I have created a new issue for follow up here https://github.com/paypal/PayPal-REST-API-issues/issues/125
