### ISSUE TITLE
[Question] Fraud prevention activities

### ISSUE THREAD

**Issue by vdecristofaro** [paypal/PayPal-NET-SDK#283]
### General information

* SDK/Library version: 1.8.0
* Environment: sandbox and production
* Language, language version, and OS: ASP.NET MVC 5, C#

### Issue description

We are using Express Checkout and our objective is to prevent frauds and expecially in these cases:
1. Recognize an account from one country (e.g. "IT") which added, as a funding instrument, a credit card issued in a different country.
2. Recognize an account which added, as a funding instrument, a credit card and is still in the UNVERIFIED state (this issue is also described in another issue here #281) 

Also a quick question: Suppose I create an account with Paypal and add a credit card. Then I will verify my account. After some time, when my account is already in a verified status, I add another credit card. Does the account goes again in an unverified status while the second ownership of the card is verified? More generally is there any way to exclude unverified credit cards from processing payments?

Thanks

**Comment by xiaoleih41** [comment]
This is more of a risk rule question built inside of the product. Please contact customer service number listed on your PayPal account for the detail answer. As PayPal payment is funded by mixed funds. the detail info such as the issuing country or the verified status of the card will not be disclosed to the 3rd party.
