### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by okankocyigit** [paypal/PayPal-NET-SDK#285]
Will you release a new version to nuget, there are some critical bugs which has been fixed after v1.8.0?

**Comment by tomkerkhove** [comment]
Duplicate of #279 but they are going to ship a new one soon.
Can you confirm this @pp-randy?

**Comment by pp-randy** [comment]
I will follow up on getting this updated.  I will use https://github.com/paypal/PayPal-NET-SDK/issues/279 for tracking.
