### ISSUE TITLE
Funding Instrument Details are missing or Funding instrument not supported. Only credit-card is supported.

### ISSUE THREAD

**Issue by engmarconi** [paypal/PayPal-NET-SDK#286]
Hello 
I'm trying to add new billing agreement using saved credit card (credit card token), but I got this exception
{"name":"VALIDATION_ERROR","details":[{"field":"payer","issue":"Funding Instrument Details are missing or Funding instrument not supported. Only credit-card is supported."}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"3d9ca7fb824b2"}

Is there anyway to used save credit card without re-enter it?
This is my agreement JSON
{
  "name": "Farm supply plan",
  "description": "Agreement for Farm supply plan",
  "start_date": "2017-08-28T19:04:08Z",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card_token": {
          "credit_card_id": "CARD-0EY318144L0683617LGQ2WTI",
          "expire_month": 6,
          "expire_year": 2022
        }
      }
    ]
  },
  "plan": {
    "id": "P-10N14331YF8025037FI4NLWQ"
  }
}

Regards

**Comment by xiaoleih41** [comment]
Unfortunately, you cannot use vaulted card with billing agreement. We are in the processing of removing credit card feature from REST API SDK. I would highly recommend you use the SDK from braintreepayments.com if you are looking to do recurring payments using credit cards.

**Comment by engmarconi** [comment]
Will you remove credit card feature from REST API SDK also for one time
order and through saved card?







* Marco M.S. KaldasResearcher & Software EngineerFaculty of Engineering ,
Minia UniversityMob : +201207639589Viber : +201207639589WhatsApp :
+201207639589*

On Mon, Aug 28, 2017 at 10:15 PM, Xiaolei Wheelock <notifications@github.com

**Comment by xiaoleih41** [comment]
Yes , we are moving all features to braintreepayments going forward.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been provided.
