### ISSUE TITLE
How to specify Sale as a Service instead of Product?

### ISSUE THREAD

**Issue by rahul8blitz** [paypal/PayPal-NET-SDK#287]
Hello, 

In Paypal Merchant SDK we specify Item Category as Physical or Digital. See below. 

PaymentDetailsItemType itemDetails = new PaymentDetailsItemType();
itemDetails.ItemCategory = "Digital"

How we can do same while using this PayPal-NET-SDK?? 
Paypal.Api.Item does not have property for specifying category. 

Please help 

Thank you

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by xiaoleih41** [comment]
This issue is being tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/144. Please follow that thread going forward for any updates.
