### ISSUE TITLE
Nice documentation but ...

### ISSUE THREAD

**Issue by Yothri** [paypal/PayPal-NET-SDK#288]
Hi,

I am currently developing an application in C# / WinForms and I want to provide a feature unlock with this SDK.

I read the API reference how to get an access token... Prerequisites, how to create a payment thats all no problem. How its done in the technical way is well documented. But I simply dont get how it works ....
For example, I dont know if the payment creation is done in my application or on my server.
I dont understand when the payment is created, how does the approval work. I would need something like that: My customer presses a button in my application, this button creates a payment with the custom field set to his username (he authenticated with in my application). Then after the payment was created and the response came into the application the application should start the browser with the approval link.. The customer logs into his paypal approves the payment and while the payment is being waited for approvement my application listens for the approval. And once it knows the customer approved, it sends the payment execution. Due to this being a payment to my account I setup an IPN listener with php which notifies the database of the successful payment setting the username that was passed in the custom field to "yes he bought the unlock". In my application I want another button to refresh profile details which then returns to have the features unlocked because the username was set in the table for unlocked features.

Can it work like that?

**Comment by xiaoleih41** [comment]
You can pass the **user Id** in the **custom** field or any identifier in the **reference_id** field of the the [transactions](https://developer.paypal.com/docs/api/payments/#definition-transaction) object when you create the payment. After you execute the payment, you do a GetPayment,  and the **state** of **sale** is **completed**, you can direct your member to the unlocked feature page.

**Comment by Yothri** [comment]
Sorry, I forgot to mention here that I found a solution.
I am not using the NET SDK anymore, I am using the PHP SDK, create the payment server sided and provide the approval link with a small REST API endpoint. And so on.. The important stuff is now server sided and should be secure.
