### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by ShanthiSenguttuvan** [paypal/PayPal-NET-SDK#291]
I need to show the correct message to the user if the payment gets failure. I need to save the payment details in my back end. So only i can tell the user what was the error. How can i get payment id for failed payments.

**Comment by xiaoleih41** [comment]
You can conduct negative testing to decide what type of message you want to show to your customer. Please check here on how to conduct [negative testing](https://developer.paypal.com/docs/classic/lifecycle/sb_error-conditions/).

**Comment by xiaoleih41** [comment]
Also, **paymentId** won't be returned of the payment is not created successfully. The negative testing should help you decide the error message. Close this issue as the requested information has been provided.
