### ISSUE TITLE
Get My Paypal Transactions from Account (Live?)

### ISSUE THREAD

**Issue by Marcus101RR** [paypal/PayPal-NET-SDK#292]
### General information
* SDK/Library version: 1.7.4
* Environment: Live (Both)
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: English, Windows 7 64 Bit

### Issue description

I am trying to get my Transactions from Paypal automatically into a MySQL DB, but first I need to make sure LIVe works and Transactions can be fetched at any time! Right now, that does not work! I aksed everywhere, there are no help guidelines and literally none of the WIKI pages or Documentations explain even with proper samples how to obtain your transactions. This is what I ended up with, and the result is STILL 0, to prove I have transactions on my account I screenshot is below.

			```var config = new Dictionary<string, string>();
			config.Add("mode", PayPal.Api.BaseConstants.LiveMode);
			config.Add("clientId", "Ady0Bn6kdJ5E-rTbDYGKaQIY");
			config.Add("clientSecret", "EDSRVBBBUWnXHjJgWJ");
			config[PayPal.Api.BaseConstants.HttpConnectionTimeoutConfig] = "30000";
			config[PayPal.Api.BaseConstants.HttpConnectionRetryConfig] = "3";

			string accessToken = new PayPal.Api.OAuthTokenCredential(config).GetAccessToken();
			args.Player.SendInfoMessage("Access Token Obtained");
			var apiContext = new PayPal.Api.APIContext(accessToken) { Config = config };
			args.Player.SendInfoMessage("Access Token Successful");

			var payments = PayPal.Api.Payment.List(apiContext);
			args.Player.SendInfoMessage("Found: {0}", payments.count);```

Screenshot of Transactions on my account:

![image](https://user-images.githubusercontent.com/8344293/30665921-b4dae452-9e20-11e7-89d9-08089a7455e0.png)

Am I using the wrong SDK? Am I using the wrong function? Or am I completely in the wrong locations in  whole? It can't be this difficult to get the same list of transactions that I see in this picture, into a C# .NET DLL code!? Please assist properly.

**Comment by xiaoleih41** [comment]
Are you looking for payment notification? Will [webhooks](https://developer.paypal.com/docs/integration/direct/webhooks/) work for your situation?

**Comment by Marcus101RR** [comment]
What I need is my server-sided Database needs to be updated if the transaction ids that come in, specifically, unique id (primary id) column is the email address of the payee (the person who buys/donates), this information should be updated server-sided as well because if there is downtime, or outages the information in my database by end up skipping any "POSTS" that come in during a period. So I prefer to collect this information based on a time stamp (using DateTime.Now) to determine when the last transaction was collected at what time.

The detailed information I need from each transaction is: The Payee Email Address, the Amount, the the date of the purchase/donation when it was finalized by Paypal itself, as some people will donate with echecks that can take time to clear!

So essentially, my code once I can obtain the transactions that were last collected (stored in a json file perhaps), will be using that date to DateTime.Now, to get the remaining transactions (if there are any since then). By checking the Payee's email (the unique ID used in our database to identify the buyer or donator. If it exists in our database, add the amount to this row, otherwise, if the Payee Email doesn't exist, create a new entry.

However, before I can get to this detail, I need to know what API would work well for this to obtain such information. So no, I am not looking fora payment notification, because that can be unreliable if paypal is down, or if my server is down. I need something that can just store the last check in a word/json file and update that as it proceeds to obtain the next check.

**Comment by xiaoleih41** [comment]
Are all the transactions processing through the same REST API credentials? This will only work with REST API transactions not any other PayPal transactions.

**Comment by Marcus101RR** [comment]
Now, they are processing through a button here: http://left6dead.wixsite.com/home/donate

I need to get these from here: https://user-images.githubusercontent.com/8344293/30665921-b4dae452-9e20-11e7-89d9-08089a7455e0.png

**Comment by xiaoleih41** [comment]
It looks like PayPal website payment standard integration. It's not REST API integration, therefore you cannot use this REST SDK to retrieve the transaction detail.

**Comment by Marcus101RR** [comment]
So how do I get these transaction on my database? without manual operation.

**Comment by xiaoleih41** [comment]
Instant payment notification (IPN) will be the only option.  We also have an option called [Payment Date Transfer (PDT)](https://developer.paypal.com/docs/classic/products/payment-data-transfer/) for website payment standard product. I will not recommend PDT because the reason listed [here](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNPDTAnAlternativetoIPN/)

**Comment by Marcus101RR** [comment]
and how would I integrate IPN into my DLL Library with the code I have already provider, the IPN sounds to me like if one of us is down, the transactions get skipped.

**Comment by xiaoleih41** [comment]
With IPN, delivery of order confirmations is virtually guaranteed since IPN resends a confirmation until your site acknowledges receipt. The code you have provided above will only work for REST API transaction. Please follow the [IPN guide](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNPDTAnAlternativetoIPN/).

**Comment by Marcus101RR** [comment]
IPN doesn't cover any guides/examples for C# .Net Library DLLs, which is a problem.

**Comment by xiaoleih41** [comment]
We welcome you to submit pull request and help us enhance that SDK. I am closing this ticket this is not .NET SDK issue.
