### ISSUE TITLE
I can not create a webhook

### ISSUE THREAD

**Issue by kmr299** [paypal/PayPal-NET-SDK#293]
* SDK/Library version: 1.9.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 4172f7dad935c
* Language, language version, and OS: .NET 4.6.1 - Windows 10

I can not create a webhook, every time I try to create one, I get the following error:
```{"name":"VALIDATION_ERROR","details":[{"field":"url","issue":"Not a valid webhook URL"}],"debug_id":"4172f7dad935c","message":"Invalid data provided","information_link":"https://developer.paypal.com/docs/api/webhooks/#errors"}```

My code:
```
try
            {
                var apiContext = await PayPalUtil.GetAPIContextAsync();

                var isHttps = Request.IsHttps;

                var urlBase = Request.Host.ToUriComponent();

                var subscriptionUrl = new Uri($"http{(isHttps ? "s" : "")}://{urlBase}/api/paypal/webhook/subscription");

                var subscriptionWebhook = new Webhook()
                {
                    url = subscriptionUrl.ToString(),
                    event_types = new List<WebhookEventType>()
                {
                    new WebhookEventType() { name= "BILLING.SUBSCRIPTION.CANCELLED"       },
            new WebhookEventType() { name = "BILLING.SUBSCRIPTION.CREATED" },
            new WebhookEventType() { name = "BILLING.SUBSCRIPTION.RE-ACTIVATED" },
            new WebhookEventType() { name = "BILLING.SUBSCRIPTION.SUSPENDED" },
            new WebhookEventType() { name = "BILLING.SUBSCRIPTION.UPDATED" }
        }
                };

                Webhook.Create(apiContext, subscriptionWebhook);
            }
            catch(Exception e)
            {

            }
```

**Comment by mickaelperrin** [comment]
Check that your URL is using https. By using the [webhook simulator](https://developer.paypal.com/developer/webhooksSimulator/), I discovered that it is mandatory.

**Comment by xiaoleih41** [comment]
@kmr299  Has your issue solved?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when you have additional information.
