### ISSUE TITLE
Is it possible to change an "override_charge_model" of a billing agreement?

### ISSUE THREAD

**Issue by kmr299** [paypal/PayPal-NET-SDK#294]
SDK/Library version: 1.9.0
Environment: Sandbox
PayPal-Debug-ID values: 876326e5bdbb4
Language, language version, and OS: .NET 4.6.1 - Windows 10

I'm trying to change a billing agreement, but it returns me the following error:
`{"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"validation_error","issue":"Invalid Path provided."}],"message":"Validation Error.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"876326e5bdbb4"}`
I want to know if it is possible to change the value of an agreement.

My code:
```
var val = new List<object>() {
            new {
                amount = PayPalUtil.GetCurrency(_planBusiness.CalculateExtraProfileValues(planBase, profileLimits)),
                charge_id = planPP.payment_definitions.First().charge_models.First().id
            }
        };
var reqChargeModels = new PatchRequest()
{
    new Patch()
    {
        op="replace",
        path=$"/override_charge_models",
        value = val
    }
};
Agreement.Update(apiContext, activeCompanyAgreement.ExternalId, reqChargeModels);
```

**Comment by xiaoleih41** [comment]
You can override charge models when you create the agreement from a billing plan but you won't be able to patch the charge models once it's  executed.

**Comment by kmr299** [comment]
Thank you. So there is no way to change the values of a billing agreement?

**Comment by xiaoleih41** [comment]
No, not the amount part. You can change shipping address and other but not the amount. Do you also do direct credit card processing? Will you be interested in Braintree SDK from Braintreepayments.com. The Braintree subscription  is flexible and it supports both direct credit cards and PayPal.

**Comment by xiaoleih41** [comment]
Close the ticket as the issue has been addressed.
