### ISSUE TITLE
Is there a way to send third-party Paypal invoices with the PayPal-NET-SDK & invoice-sdk-dotnet?

### ISSUE THREAD

**Issue by Sel19** [paypal/PayPal-NET-SDK#296]
### General information

* SDK/Library version: 1.9.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: C#, .NET 4.6.1, Windows 10

### Issue description

There seems to be third-party Paypal invoicing support in the Paypal-PHP-SDK (at least from the sample). However, I'm unable to find equivalent documentation/function in the Paypal-NET-SDK and Paypal invoice-sdk-dotnet.

I've gone as far as getting the permission and refresh/access token from the third-party through Paypal Log In. But using the third-party merchant email address, Paypal returns Unauthorized error whenever sending the invoice request either directly with Paypal.api.APIContext created from our REST API App credentials or a new Paypal.api.APIContext using the third-party access token. It seems like we are missing a step to associate the third-party access token with the REST API app APIContext; possibly something like the magic in Invoice.updateAccessToken() method called the PHP SDK sample?

Has anyone successfully implemented this integration in .NET? If so, I would appreciate all the details you can provide.

If not, would anyone be able to at least provide a method to do this with the REST API directly? 

Last resort might be to look through the source code for the Invoice.updateAccessToken() method and see if we can reverse engineer it in .NET. Although, the Invoice.updateAccessToken() method appears to be missing in the source Invoice.php file.

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by Sel19** [comment]
Hello xiaoleih41,  

Thank you very much for looking into this issue.

Here's how worked around the problem. The issue was probably in the request header handling of the APIContext. Since Paypal Log In already returns the third-party access and refresh tokens, we really just needed a way to create/update the APIContext so that it did not pass token from our ClientId and Secret. Instead, it should just pass the third-party bearer token. I hope this helps someone as the issue took a day or two to get past.

`private void MakeThirdPartyApiContext()
        {
            // Create a new APIContext using the third-party access token
            ThirdPartyPaypalApiContext = new APIContext($"Bearer {GetThirdPartyAccessToken()}")
            {
                HTTPHeaders = new Dictionary<string, string> { { "Content-Type", "application/json" } },
                Config = new Dictionary<string, string> { { "mode", ConfigManager.Instance.GetProperties()["mode"] } }
            };
        }

        private string GetThirdPartyAccessToken()
        {
            return DateTime.UtcNow < Job.SentDateUtc.AddSeconds(Job.PaypalTokenExpiry)
                ? Job.PaypalThirdPartyAccessToken
                : RefreshPaypalAccessToken();
        }

        private string RefreshPaypalAccessToken()
        {
            //Obtain access token with app APIContext and third-party refresh token
            Tokeninfo tokenInfo = new Tokeninfo
            {
                refresh_token = Job.PaypalThirdPartyRefreshToken
            };
            Tokeninfo thirdPartyTokenInfo = tokenInfo.CreateFromRefreshToken(AppPaypalApiContext, new PayPal.Api.CreateFromRefreshTokenParameters());
            return thirdPartyTokenInfo.access_token;
        }`

**Comment by xiaoleih41** [comment]
This is great.  Close this issue as the original issue has been solved and the SDK sample request has been submitted and queued.
