### ISSUE TITLE
Managed Onboarding Integration (asp.net core 1.1 + angular2) 

### ISSUE THREAD

**Issue by AlexOliinyk1** [paypal/PayPal-NET-SDK#298]
I have a platform (asp.net core 1.1 + angular2), where users have the ability to sell and buy goods.

When selling, the money for the purchase must be transferred to the seller (after confirmation of delivery).

I need to register a paypal merchant, I'm follow the Managed Onboarding Guide (Managed because sellers do not need to create a business account) - with "v1/customer/partners/merchant-accounts", but this returns a 'Unauthorized' error when I'm create a PayPal Bearer Token.

This is example of 'scope' which I got with token
 Scope:
https://uri.paypal.com/services/subscriptions
https://api.paypal.com/v1/payments/.*
https://api.paypal.com/v1/vault/credit-card
https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts
https://api.paypal.com/v1/vault/credit-card/.*

Where was the error? Why I can not connect user by address POST: "v1/customer/partners/merchant-accounts"

Thanks

**Comment by xiaoleih41** [comment]
This is a limited release product.  Please make sure to reach out to your account manager to get applied feature before start integrating this product.
