### ISSUE TITLE
Please use C# naming conventions

### ISSUE THREAD

**Issue by jolleekin** [paypal/PayPal-NET-SDK#303]
### General information
* Language, language version, and OS: C#

### Issue description
Since this SDK is written in C#, it should use [C# naming conventions][1]. To be specific
- Use *PascalCase* instead of *snake_case* for property names
- Abbreviations should be treated as English words. Examples:
    - Sdk instead of SDK
    - Api instead of API
    - Http instead of HTTP
    - Uri instead of URI
    - Id instead of ID
    - Db instead of DB

[1]: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members

**Comment by pp-randy** [comment]
Thank you for the information. I have provided this feedback to our engineers working on the next version of the SDK.

**Comment by jaypatel512** [comment]
Hey @jolleekin !

We just released our first 2.0.0-beta which has better syntax format. I would encourage you to take a quick look at the branch, and let us know if you find something that is not correct. We will be able to make all the changes, considering it is still in beta.

Thank you so much for pointing this out. I will go ahead and close this issue for now.
