### ISSUE TITLE
Getting "MODIFY_USER_DATA_RETURNED_NO_MATCHING_ADDRESS" error recently.

### ISSUE THREAD

**Issue by weechard** [paypal/PayPal-NET-SDK#304]
### General information

* SDK/Library version:  1.9.0
* Environment:  Sandbox
* `PayPal-Debug-ID` values: 90e977eea6362 & "eda39d5a8828e"
* Language, language version, and OS:  C# MVC5

### Issue description

Was getting "MODIFY_USER_DATA_RETURNED_NO_MATCHING_ADDRESS" error recently and no detailed explanation was found on the internet. did not change the data sent to paypal. Would like to know what could cause this issue ?

Thank you. !

**Comment by pp-randy** [comment]
Can you try with a new credit card and vault token to see if it clears up the issue? 

You can get a generated one here: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413.  Just skip to the bottom and select what type you want 
![image](https://user-images.githubusercontent.com/6819909/32448499-aa927d88-c2d4-11e7-9fc6-aea8042011ff.png)

**Comment by weechard** [comment]
Hi Randy,

It gives different error right now and i can't really understand what it means.
The combination of payer and payee settings mean that this buyer can't pay this seller.
Used a newly generated AppID & Secret and various credit card number generated via the link given.


SDK/Library version: 1.9.0
Environment: Sandbox
PayPal-Debug-ID values: d4b1bed047643, 1a495f5e136c6
Language, language version, and OS: C# MVC5

Thank you.

**Comment by pp-randy** [comment]
Did you add the credit card to your merchant account?  You are using Vault with Guest Checkout is what it looks like.  If this is the case can you just skip the other steps and try with a new credit card?  I apologize for the back and forth on this.

**Comment by weechard** [comment]
Hi Randy,

It's ok. will need to get this solve as we're not sure if the production will produce the same issue.
I did previously added the only credit card into the merchant account but also removed after you've mentioned. 
Also tried different combination of credit cards but in the end still getting the same results.

the Debug ID after i removed the only credit card added to the the sandbox merchant account.

Debug ID : e3a6a2c4d14f8
Error Message : The combination of payer and payee settings mean that this buyer can't pay this seller
Credit Card Used : Ends with 5794
Environment : Sandbox.

 Debug ID : 7d4d5abcb8149
Error Message : The combination of payer and payee settings mean that this buyer can't pay this seller
Credit Card Used : 4111 111111111111
Environment : Sandbox.

Debug ID : 141483d35e36f
Error Message : The combination of payer and payee settings mean that this buyer can't pay this seller
Credit Card Used : Ends with 1277
Environment : Sandbox.

Thank you.

**Comment by pp-randy** [comment]
Can you provide the Payment JSON?  I think the issue might be related to currency and country https://developer.paypal.com/docs/classic/api/adaptive-payments/Currency_Restictions/.

**Comment by pp-randy** [comment]
Can you test with MYR currency?  Here is the REST API link about currency https://developer.paypal.com/docs/integration/direct/rest/currency-codes/.  However, both indicate you need to use MYR for  Malaysia sender and receiver.

**Comment by weechard** [comment]
Changed from USD to MYR. 
The reason I put USD previous was whenever i change to MYR it wouldn't allow me to get through the transaction.

Test set #1
Payment Request JSON : https://pastebin.com/60R9g2kE
Payment Response JSON : https://pastebin.com/cduApiuG

Test set #2 (Using different RESP API Apps)
Payment Request JSON :https://pastebin.com/hVSfeG2v
Payment Response JSON : https://pastebin.com/VwmNkjVT

it now gives back the "MODIFY_USER_DATA_RETURNED_NO_MATCHING_ADDRESS" when i change the currency to MYR.

**Comment by xiaoleih41** [comment]
Please make sure first last name to be letters, phone number in the right format for your region so is the address and zip code to be in the right format and try again.

**Comment by xiaoleih41** [comment]
Close it due to inactivity. Please resubmit when you have additional information.
