### ISSUE TITLE
Upgrading to 1.9

### ISSUE THREAD

**Issue by MLyons10** [paypal/PayPal-NET-SDK#305]
Hello,

I am trying to upgrade my solution from 1.7.2 to 1.9 and there appears to have been changes that require a rework of the code.  I was trying to find an example of what needed to be changed, but haven't been able to find it.  Is there something available?

Thanks!

**Comment by pp-randy** [comment]
What types of transactions are you creating or what is your usage of the SDK?  
Are you getting any errors? 

Looking over changes here what stands out https://github.com/paypal/PayPal-NET-SDK/releases
is v 1.8 `Use PaymentCard instead of CreditCard`, but this would only involve Direct Credit Card payments.

**Comment by MLyons10** [comment]
Thank you for your response.  I did change CreditCard to PaymentCard, but when I try to test the code I get an error that:

Exception: (Amount: 10)  System.ArgumentNullException: accessToken cannot be null
Parameter name: accessToken
   at PayPal.Api.APIContext..ctor(String accessToken)
   at ProjectDesk1.CPayments.ProcessWithPayPal(String _CCNumber, String _CCType, String _CCCVV, String _CCExpiration, String _FName, String _LName, String _email, String _Address1, String _Address2, String _City, String _State, String _Zip, String _Amount) in C:\Users\Matthew L\Documents\Visual Studio 2017\Projects\ProjectDesk1\ProjectDesk1\CPayments.cs:line 354

I'm trying to trouble shoot the error, but it appears to be thrown when it attempts to process the transaction.

**Comment by MLyons10** [comment]
The code does work with 1.7.2, but I want to try to keep the API version up to date as much as possible.

**Comment by jaypatel512** [comment]
Looking at the code difference between 1.7.2 and 1.9.1, there has been no significant code change for ApiContext constructor with `accessToken`. We always check if accessToken is null or not. 

It looks like the place where you are fetching the `accessToken` is returning back `null`, causing this error. 

Can you please check how are you fetching this accessToken, and share the steps/code that you are doing? This should help us identify the breaking change.

**Comment by MLyons10** [comment]
Sure thing.  This code worked with 1.7.2.  I am open to revisions as needed for the update.

        public static List<string> ProcessWithPayPal(string _CCNumber, string _CCType, string _CCCVV, string _CCExpiration, string _FName, string _LName, string _email, string _Address1, string _Address2, string _City, string _State, string _Zip, string _Amount)
        {
            //Error Handling
            string ErrorFileString = @"\SHSolutions\ProjectDesk\Error Logs\ErrorLog.txt";
            string appdata = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            string directoryString = appdata + ErrorFileString;
            string ErrorLogString = "";

            //https://developer.paypal.com
            //Sandbox
            //app.config - <add name="mode" value="sandbox"/>
            //string PaypalClientID = "XXXX";
            //string PaypalSecret = "XXXX";

            //Live
            //app.config - <add name="mode" value="live"/>
            string PaypalClientID = "XXXX";
            string PaypalSecret = "XXXX";

            string PaypalAccessToken = "";

            List<string> ResultList = new List<string>();

            string CCNumber = _CCNumber;
            string CCType = _CCType.ToLower();
            string CCCVV = _CCCVV;
            string CCExpiration = _CCExpiration;
            string CCExpMonth = "";
            string CCExpYear = "";
            string FName = _FName;
            string LName = _LName;
            string Address1 = _Address1;
            string Address2 = _Address2;
            string City = _City;
            string State = _State;
            string Zip = _Zip;
            string AmountString = _Amount.Replace("$", "").Replace(" ", "");
            decimal AmountDecimal = Convert.ToDecimal(AmountString);

            //Handle dashes and spaces in the card number
            CCNumber = CCNumber.Replace("-", "").Replace(" ", ""); ;

            //Split Expiration
            int ExpMonth = 0;
            int ExpYear = 0;
            string[] expiration = CCExpiration.Split('/');
            foreach (string word in expiration)
            {
                if (CCExpMonth == "")
                {
                    CCExpMonth = word.ToString();
                }
                else
                {
                    CCExpYear = word.ToString();
                }
            }
            try
            {
                ExpMonth = Convert.ToInt32(CCExpMonth);

                ExpYear = Convert.ToInt32(CCExpYear);
            }
            catch
            {

            }

            //EMail Address
            string emailaddress = "";
            if (_email != "")
            {
                emailaddress = _email;
            }
            else
            {
                emailaddress = "";
            }

            //Format State
            if (State.Count() != 2)
            {
                State = CAddress.GetStateShort(State);
            }

            //Record Values in ErrorString
            ErrorLogString = "----NEW TRANSACTION----" + Environment.NewLine;
            ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
            ErrorLogString += "Field Values" + Environment.NewLine;
            ErrorLogString += "CCNumber: " + CCNumber + Environment.NewLine;
            ErrorLogString += "CCType: " + CCType + Environment.NewLine;
            ErrorLogString += "CCCVV: " + CCCVV + Environment.NewLine;
            ErrorLogString += "CCExpiration: " + CCExpiration + Environment.NewLine;
            ErrorLogString += "CCExpMonth: " + CCExpMonth + Environment.NewLine;
            ErrorLogString += "INTExpMonth: " + ExpMonth.ToString() + Environment.NewLine;
            ErrorLogString += "CCExpYear: " + CCExpYear + Environment.NewLine;
            ErrorLogString += "INTExpYear: " + ExpYear.ToString() + Environment.NewLine;
            ErrorLogString += "FName: " + FName + Environment.NewLine;
            ErrorLogString += "LName: " + LName + Environment.NewLine;
            ErrorLogString += "Address1: " + Address1 + Environment.NewLine;
            ErrorLogString += "Address2: " + Address2 + Environment.NewLine;
            ErrorLogString += "City: " + City + Environment.NewLine;
            ErrorLogString += "State: " + State + Environment.NewLine;
            ErrorLogString += "Zip: " + Zip + Environment.NewLine;
            ErrorLogString += "AmountString: " + AmountString + Environment.NewLine;
            ErrorLogString += "AmountDecimal: " + AmountDecimal.ToString() + Environment.NewLine;

            //Process Payment
            string ResultString = "";

            try
            {
                DataTable AccessTokenTable = GetPayPalAccessTokenTable(PaypalClientID, PaypalSecret);

                //PaypalAccessToken = GetPayPalAccessToken(PaypalClientID, PaypalSecret);
                PaypalAccessToken = AccessTokenTable.Rows[0]["AccessToken"].ToString();
                ErrorLogString += AccessTokenTable.Rows[0]["Response"].ToString();

                var apiContext = new APIContext(PaypalAccessToken);

                // A transaction defines the contract of a payment - what is the payment for and who is fulfilling it. 
                var transaction = new Transaction()
                {
                    amount = new Amount()
                    {
                        currency = "USD",
                        total = AmountString,
                        details = new Details()
                        {
                            shipping = "0",
                            subtotal = AmountString,
                            tax = "0"
                        }
                    },
                    description = "",
                    item_list = new ItemList()
                    {
                        items = new List<Item>()
                            {
                                new Item()
                                {
                                    name = "Services",
                                    currency = "USD",
                                    price = AmountString,
                                    quantity = "1"
                                }
                            },
                        shipping_address = new ShippingAddress
                        {
                            city = City,
                            country_code = "US",
                            line1 = Address1,
                            postal_code = Zip,
                            state = State,
                            recipient_name = FName + " " + LName
                        }
                    },
                    invoice_number = ""
                };

                // A resource representing a Payer that funds a payment.
                var payer = new Payer()
                {
                    payment_method = "payment_card",
                    funding_instruments = new List<FundingInstrument>()
                        {
                            new FundingInstrument()
                            {
                                payment_card = new PaymentCard()
                                {
                                    billing_address = new Address()
                                    {
                                        city = City,
                                        country_code = "US",
                                        line1 = Address1,
                                        postal_code = Zip,
                                        state = State
                                    },
                                    cvv2 = CCCVV,
                                    expire_month = ExpMonth,
                                    expire_year = ExpYear,
                                    first_name = FName,
                                    last_name = LName,
                                    number = CCNumber,
                                    type = CCType
                                }
                            }
                        },
                    payer_info = new PayerInfo
                    {
                        email = emailaddress
                    }
                };

                // A Payment resource; create one using the above types and intent as `sale` or `authorize`
                var payment = new Payment()
                {
                    intent = "sale",
                    payer = payer,
                    transactions = new List<Transaction>() { transaction }
                };

                // Create a payment using a valid APIContext
                var createdPayment = payment.Create(apiContext);

                //var saleId = payment.transactions.Select(x => x.related_resources).Select(resource => resource.First().sale.id).First();
                //var saleId = payment.transactions[0].related_resources[0].sale.id;
                var transactionID = createdPayment.transactions[0].related_resources[0].sale.id;
                var payID = createdPayment.transactions[0].related_resources[0].sale.parent_payment;

                ResultString += transactionID.ToString();

                ResultList.Add("Success");
                ResultList.Add(transactionID.ToString());
                ResultList.Add(payID.ToString());

                //Add to Error Log
                ErrorLogString += "-----------" + Environment.NewLine;
                ErrorLogString += "Success" + Environment.NewLine;
                ErrorLogString += "Transaction ID: " + transactionID.ToString() + Environment.NewLine;
                ErrorLogString += "Pay ID: " + payID.ToString() + Environment.NewLine;
            }
            catch (PayPalException ex)
            {
                string response = ((PayPal.ConnectionException)ex.InnerException).Response;
                //string ErrorCode = ((PayPal.Exception.ConnectionException)ex.InnerException).Message;
                //jsonObject json = new jsonObject

                ResultList.Add("Failed");
                ResultList.Add(response);

                //Add to Error Log
                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Failed" + Environment.NewLine;
                ErrorLogString += "A general exception was thrown from the SDK." + Environment.NewLine;
                ErrorLogString += response + Environment.NewLine;
            }
            catch (Exception ex)
            {
                //ResultString = "RUNTIME EXCEPTION" + e;
                ResultList.Add("Failed");
                ResultList.Add(ex.ToString());

                //Add to Error Log
                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Failed" + Environment.NewLine;
                ErrorLogString += "A general exception was thrown." + Environment.NewLine;
                ErrorLogString += ex.ToString() + Environment.NewLine;
            }

            //Save Error Log
            if (ResultList[0].ToString() == "Failed")
            {
                using (System.IO.StreamWriter file = new System.IO.StreamWriter(directoryString, true))
                {
                    file.WriteLine(ErrorLogString);
                }
            }

            return ResultList;
        }

        private static DataTable GetPayPalAccessTokenTable(string _ClientID, string _Secret)
        {
            DataTable AccessTokenTable = new DataTable();
            AccessTokenTable.Columns.Add("AccessToken", typeof(string));
            AccessTokenTable.Columns.Add("Response", typeof(string));

            string AccessToken = "";
            string ErrorLogString = "";

            try
            {
                OAuthTokenCredential tokenCredential = new OAuthTokenCredential(_ClientID, _Secret);
                AccessToken = tokenCredential.GetAccessToken();

                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Success" + Environment.NewLine;
                ErrorLogString += "Access Token: " + AccessToken + Environment.NewLine;
            }
            catch (PayPal.IdentityException ex)
            {
                // ex.Details provides quick access to the API error information.
                string ErrorString = ex.ToString();

                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Failed" + Environment.NewLine;
                ErrorLogString += "ex.Details provides quick access to the API error information." + Environment.NewLine;
                ErrorLogString += ErrorString + Environment.NewLine;
            }
            catch (PayPal.HttpException ex)
            {
                // Some other error occurred when attempting to send the request to PayPal.
                // ex.Response contains the full response from the API which should highlight the error encountered.
                string ErrorString = ex.ToString();

                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Failed" + Environment.NewLine;
                ErrorLogString += "Some other error occurred when attempting to send the request to PayPal." + Environment.NewLine;
                ErrorLogString += "ex.Response contains the full response from the API which should highlight the error encountered." + Environment.NewLine;
                ErrorLogString += ErrorString + Environment.NewLine;
            }
            catch (PayPal.PayPalException ex)
            {
                // A general exception was thrown from the SDK.
                string ErrorString = ex.ToString();

                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Failed" + Environment.NewLine;
                ErrorLogString += "A general exception was thrown from the SDK." + Environment.NewLine;
                ErrorLogString += ErrorString + Environment.NewLine;
            }
            catch (System.Exception ex)
            {
                // Some other general exception occurred.
                string ErrorString = ex.ToString();

                ErrorLogString += "-----------" + DateTime.Now + Environment.NewLine;
                ErrorLogString += "Failed" + Environment.NewLine;
                ErrorLogString += "Some other general exception occurred." + Environment.NewLine;
                ErrorLogString += ErrorString + Environment.NewLine;
            }

            AccessTokenTable.Rows.Add(AccessToken, ErrorLogString);

            return AccessTokenTable;
        }

**Comment by MLyons10** [comment]
I just wanted to follow up on this.  Does anyone have any idea what the breaking change between 1.7.2 and 1.9 is?

Thanks!

**Comment by MLyons10** [comment]
I hope everyone had a Happy Thanksgiving!

I spent the weekend working on this some more and I haven't been able to find what exactly was changed between 1.7.2 and 1.9  

I tried to move from CreditCard to PaymentCard, but payments still don't go through.  I'm not sure if the structure of the request changed somewhere...?

**Comment by jaypatel512** [comment]
Can you please double check and see if you are not getting `null` back for `PaypalAccessToken` in your code here. Also, can you print and make sure the `ErrorLogString` contains a success message:

```csharp
DataTable AccessTokenTable = GetPayPalAccessTokenTable(PaypalClientID, PaypalSecret);

            //PaypalAccessToken = GetPayPalAccessToken(PaypalClientID, PaypalSecret);
            PaypalAccessToken = AccessTokenTable.Rows[0]["AccessToken"].ToString();
            ErrorLogString += AccessTokenTable.Rows[0]["Response"].ToString();

            var apiContext = new APIContext(PaypalAccessToken);
```

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional info.
