### ISSUE TITLE
Echeck Payment using Bank Account number and Bank Routing Number

### ISSUE THREAD

**Issue by sujanmah062** [paypal/PayPal-NET-SDK#307]
Hi All,
I'm currently using **paypal .Net SDK version 1.9.0** and Environment : **Sandbox**

How to make payment with payment method "echeck" using Bank Account Number and Bank Routing Number , without using payment method "paypal, credit card".

I  don't want the user to go **paypal** site but give the user an ability to choose bank account and give the **Bank Account number and routing number** and the details and post the payment. 
Is this feature available in c#

Thank in advance

**Comment by xiaoleih41** [comment]
This is a deprecated feature, you cannot have people put bank info to pay without adding to a PayPal account and complete a bank verification process.

**Comment by mhranimesh** [comment]
Hi @xiaoleih41 ,
Is there any way around that could slove the problem.
Thanks

**Comment by xiaoleih41** [comment]
I don't think so. PayPal account will be the only way to support bank funded transaction. You can also consider to integrate [Braintree ACH direct debit](https://www.braintreepayments.com/features/ach-direct-debit). I believe it's a limited release, you will have to apply and see if you can get approved for it.

**Comment by xiaoleih41** [comment]
Close as answer has been given.
