### ISSUE TITLE
.Net SDK Create() method always return remote server error 401 no authorize

### ISSUE THREAD

**Issue by HEHEMonster** [paypal/PayPal-NET-SDK#310]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I used  paypal .net sdk ver.1.91 now, i configure live  clientID, client secret, and mode is live,but it dont work for me( get accessToken is success ),i try sanbox and configure with sandbox ,it create payment successfully, but i change to live  then debug alway return me 401 error,  i dont know what's wrong with my code.please help me... T_T

**Comment by HEHEMonster** [comment]
Environment: VS2017 and .net 4.61

**Comment by HEHEMonster** [comment]
![image](https://user-images.githubusercontent.com/16699173/33538567-ff9f9156-d8fc-11e7-8f94-63cca2afaf86.png)

**Comment by pp-randy** [comment]
This could happen if your sandbox credentials are still being used.  Make sure you are using the live credentials for your REST API Application. 

Open your App and click the Live toggle.
![image](https://user-images.githubusercontent.com/6819909/33561185-9d849360-d8d7-11e7-96d8-603b76a34c78.png)

You can get to your Applications here: https://developer.paypal.com/developer/applications

**Comment by HEHEMonster** [comment]
![image](https://user-images.githubusercontent.com/16699173/33585295-7ef75776-d99e-11e7-9e27-e7b272f61270.png)
all right, I'm sure  really  used the live clientID and Secret, but it's wrong when i  call the payment.creat(apiContext);  I really don't know what the problem...

**Comment by HEHEMonster** [comment]
![image](https://user-images.githubusercontent.com/16699173/33585573-e7f1d7aa-d99f-11e7-9341-13b858c02463.png)
it's my paypal settings.  I'm sorry there's mosaics

**Comment by HEHEMonster** [comment]
![image](https://user-images.githubusercontent.com/16699173/33586801-20b9c4fc-d9a6-11e7-9bbe-dd87311ceada.png)
Today I download paypal samples and check my code again, this step is missing... but when i test the sandbox it's no problem.. Now it's run successfully, thanks for your help ! ^_^

**Comment by pp-randy** [comment]
I'm glad you were able to resolve, thank you for posting the solution.
