### ISSUE TITLE
.NET SDK would like to not show the shipping address on the payment interface of PayPal. What should I do

### ISSUE THREAD

**Issue by Sir-hu** [paypal/PayPal-NET-SDK#311]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by Sir-hu** [comment]
How should I set up to not display the delivery address

**Comment by xiaoleih41** [comment]
You will have to create a web profiles and set `no_shipping` to **1**

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given
