### ISSUE TITLE
List Payments Comes Back Empty

### ISSUE THREAD

**Issue by adamfisher** [paypal/PayPal-NET-SDK#312]
### General information

* **SDK/Library version:** 1.9.1
* **Environment:** Production
* **Language, language version, and OS:** .NET 4.6.1 on Windows 10

### Issue description

I created a PayPal payment button and I have transactions in my PayPal account but when I attempt to query for them via the REST API, nothing comes back. 

The button ID is: `55AMG5AW5ENEY`

Here is how I am calling it:

```
var config = ConfigManager.Instance.GetProperties();
var accessToken = new OAuthTokenCredential(config).GetAccessToken();
var apiContext = new APIContext(accessToken);
var paypalPayments = Payment.List(apiContext).payments;
```

I verified my config settings are set to live mode and match the client ID and secret from the dashboard. I get no errors and just an empty response:

```
{PayPal.Api.PaymentHistory}
    count: 0
    next_id: null
    payments: Count = 0
```

**Comment by pp-randy** [comment]
The Payment API will only return Payments created by the API.  We have a feature request opened up to support a transaction search https://github.com/paypal/PayPal-REST-API-issues/issues/9, please follow here for updates.

**Comment by pp-randy** [comment]
You could use the Classic API for your needs https://developer.paypal.com/docs/classic/api/merchant/TransactionSearch_API_Operation_NVP/.

**Comment by x011** [comment]
It's 2999 and everyone died of corona virus and waiting the "feature request". PayPal sucks in every aspect.

**Comment by NoctuaD15** [comment]
> It's 2999 and everyone died of corona virus and waiting the "feature request". PayPal sucks in every aspect.

Can't agree more with you!
