### ISSUE TITLE
PayPalPayment.Execute INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by MaximShchukin** [paypal/PayPal-NET-SDK#314]
### General information

* SDK/Library version: 1.9.0
* Environment: Sandbox 
* `PayPal-Debug-ID` values: fe1543a6da5f4
* Language, language version, and OS: .net 4.7, C#7, asp.net mvc 

### Issue description

Sometimes when i try to execute payment PayPal sdk throws HttpException
`   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
   at PayPal.Api.Payment.Execute(APIContext apiContext, String paymentId, PaymentExecution paymentExecution)`

**Comment by xiaoleih41** [comment]
I will report this issue.

**Comment by pp-randy** [comment]
@MaximShchukin are you still seeing this issue?

**Comment by MaximShchukin** [comment]
Not anymore. Seems to work fine right now.

**Comment by xiaoleih41** [comment]
Close the issue as it appears to be solved.

**Comment by HoneyShyam** [comment]
I am still getting the same issue on webhook.
Message: The remote server returned an error: (404) Not Found. Source: PayPal Inner Excepption: StackTrace: at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest) at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader) at PayPal.Api.WebhookEvent.Get(APIContext apiContext, String eventId) at SAM.Presentation.Controllers.IpnController.Index() PayPal jsonObject: {"id":"WH-02567324DK3319522-22444371MN9804117","event_version":"1.0","create_time":"2018-04-14T05:39:57.255Z","resource_type":"Agreement","event_type":"BILLING.SUBSCRIPTION.CREATED","summary":"A billing subscription was created"

**Comment by xiaoleih41** [comment]
@HoneyShyam This appears to be a different error. Can you submit a new issue with debugId included?
