### ISSUE TITLE
Creating Invoice with discount by amount fails with (400) Bad Request

### ISSUE THREAD

**Issue by ksavosteev** [paypal/PayPal-NET-SDK#316]
* SDK/Library version:  .NET SDK 1.8.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 4da8cbb49a90b
* Language, language version, and OS: .NET SDK 1.8.0

### Issue description

Call to invoice.Create(context) with 'discount.amount' = some Cost object and 'discount.percent' = 0 fails with the following response: 
{  
   "name":"VALIDATION_ERROR",
   "message":"Invalid request - see details.",
   "information_link":"https://developer.paypal.com/docs/api/invoicing/#errors",
   "debug_id":"4da8cbb49a90b",
   "details":[  
      {  
         "field":"discount.percent",
         "issue":"minimum value allowed is 0.001."
      },
      {  
         "field":"discount",
         "issue":"either percent or, amount is required."
      }
   ]
}

**Comment by jaypatel512** [comment]
You do not need to pass `discount.percent` as well. Do not set that value at all.

**Comment by ksavosteev** [comment]
@jaypatel512 unfortunately `discount.percent` is not nullable float

**Comment by xiaoleih41** [comment]
Can you remove this field completely?

**Comment by xiaoleih41** [comment]
Close due to inactivity.  Please resubmit if you have additional information.

**Comment by fschon** [comment]
This issue still exists in java rest api client version:
        <dependency>
            <groupId>com.paypal.sdk</groupId>
            <artifactId>rest-api-sdk</artifactId>
            <version>LATEST</version>
        </dependency>

It is not possible to set an amount discount because the percentage discount is not nullable and if omitted will default to 0.0. Trying to set both an amount discount and a percentage discount results in an error saying that only one or the other is allowed.

**Comment by skykharkov** [comment]
Confirm this issue when using PayPal .NET SDK v 1.9.1
Unable to set discount value, only percent.
`{
	"name": "VALIDATION_ERROR",
	"message": "Invalid request - see details.",
	"information_link": "https://developer.paypal.com/docs/api/invoicing/#errors",
	"details": [{
			"field": "discount",
			"issue": "either percent or, amount is required."
		}, {
			"field": "discount.percent",
			"issue": "minimum value allowed is 0.00."
		}
	]
}`

**Comment by altriak** [comment]
Ran into this issue. As a workaround, you can use an override to create a nullable float in place of the normal float

public class DerivedCost : Cost
    {
        public new float? percent;
    }
