### ISSUE TITLE
Date ToString

### ISSUE THREAD

**Issue by Minx-SigEp** [paypal/PayPal-NET-SDK#318]
### General information

* SDK/Library version: 2.0.0-beta0
* Environment: Sandbox
* PayPal-Debug-ID: cd251c14e3a53
* Language, language version, and OS: .Net Core 2 on Windows 10 -->

### Issue description
If I am understanding the ISO 8601 standard correctly (https://tools.ietf.org/html/rfc3339#section-5.8) and Microsoft's documentation (https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier) a date string returned by the following code should conform to the ISO 8601 standard but the API is having an issue with it. Is this due to the additional accuracy .Net includes when formatting the date? If so it would be nice to have that documented and the proper format string provided so we know which format the API requires since MS appears to not be conforming.

`DateTimeOffset.UtcNow.ToString("o", System.Globalization.CultureInfo.InvariantCulture),`

BraintreeHttp.HttpException: {"name":"VALIDATION_ERROR","details":[{"field":"create_time","issue":"Can not construct instance of java.util.Date from String value '2017-12-29T01:37:55.7625677+00:00': not a valid representation (error: Failed to parse Date value '2017-12-29T01:37:55.7625677+00:00': Unparseable date: \"2017-12-29T01:37:55.7625677+00:00\")"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"cd251c14e3a53"}

**Comment by jaypatel512** [comment]
Hey @Minx-SigEp !

We just added the test for BillingAgreementsCreateRequest, and you can use this one line code to generate the date with proper format. Note that we have created a date which is 24hours ahead of current time.

```cs
var date = DateTime.UtcNow.AddDays(1).ToString("yyyy-MM-ddTHH\\:mm\\:ssZ");
```

Read [here](https://github.com/paypal/PayPal-NET-SDK/blob/2.0-beta/Test/BillingAgreements/BillingAgreementssCreateTest.cs#L19-L21)
