### ISSUE TITLE
Webhooks not triggered in sandbox mode when payment done from Ionic2 app

### ISSUE THREAD

**Issue by csimone86** [paypal/PayPal-NET-SDK#319]
Hi everyone,
I have asked on [stackoverflow](https://stackoverflow.com/questions/47927500/notify-paypal-payment-done-from-ionic2-app) but no answer in 2 weeks... I need to solve this problem...
I have seen [this issue](https://github.com/paypal/PayPal-Ruby-SDK/issues/186) but it is not clear if it has been solverd or not yet (I have this doubt just because it is not working to me)...

We are doing an app with Ionic 2. I do not have access to the client code but just to the server side code, so I cannot copy and paste here the app code. However the payment seems to work but I do not receive any notification in my Webhook. I am in a `sandbox environment`.

My collegue is using the native paypal component for the app. He simply calls my back end, and I give him the usefull information to do the payment... this is the json I return him when he prepares the view for doing the payment:

```
{
    "init": {
        "clientId_sandbox": "...",
        "clientId_live": "...",
        "env": "..."
    },
    "payment": {
        "amount": "...",
        "currency": "...",
        "description": "...",
        "intent": "sale",
        "custom": "..."
    }
}
```

So... he make the payment. I can see the payment in my paypal developer account:

> payment receipt notification

But my webhook is not triggered. I have configured it from

> My Apps & Credentials -> <MyApp> -> SANDBOX WEBHOOKS -> Add Webhook... 

Here I have selected all event types...

If I test the webhook from `Webhooks Simulator`, it works... so the url is correct... But if I do a test from the app the webhook is not triggered, but i can see the payment... What I am doing wrong? Perhaps should I use IPN instead of Webhook? But in this case how can I give paypal which is the url of my IPN? it seems that the native paypal component of Ionic 2 does not have a property to set that url...

Thank you

**Comment by xiaoleih41** [comment]
Has the payment been executed?

**Comment by csimone86** [comment]
yes, has been executed.... I see it on [Notification page of Paypal](https://developer.paypal.com/developer/notifications/)

**Comment by pp-randy** [comment]
Do you the Webhook events in your dashboard? https://developer.paypal.com/developer/dashboard/webhooks/sandbox  

Are you using PayPal payment method?  Credit Card payments won't trigger webhooks.

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional information.
