### ISSUE TITLE
"Invalid Fields passed in plan. Pass only a valid plan-id."

### ISSUE THREAD

**Issue by KlaasjanM** [paypal/PayPal-NET-SDK#326]
### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 77ee5bca3d4d
* Language, language version, and OS: Windows 10, VS17 vb.net

### Issue description
I created an example for and billing agreement. I followed the example.
But when i create the agreement. i get an error about the ID of the plan : "Invalid Fields passed in plan. Pass only a valid plan-id."

What i did, i create a plan and uses the code agreement.plan = createdplan.

I don't know what i do wrong.

Hope someone can help me.

Best Regards
Klaasjan

**Comment by xiaoleih41** [comment]
After you create a plan, you will need to [activate](https://developer.paypal.com/docs/api/payments.billing-plans) it by update the plan. After that, you can create a billing agreement based on the billing plan.

**Comment by KlaasjanM** [comment]
Hi Xiaoleih41,
I followed the code from the C# examples

 Dim plan As New Plan
        plan.name = "Name of the plan"
        plan.description = "Descripton of the plan"
        plan.type = "FIXED"

 Dim createdplan = plan.Create(apiContext)

Dim agreement As New Agreement
        agreement.name = "Name Agreement"
        agreement.description = "Descripion Agreement"
        agreement.start_date = DateTime.UtcNow.AddDays(1).ToString("yyyy-MM-ddTHH:mm:ssZ")
        agreement.payer = payer
        agreement.plan = createdplan
        agreement.shipping_address = shippingaddress

 Dim createdAgreement = agreement.Create(apiContext)

What is wrong with this approach?

Regards
Klaasjan

**Comment by xiaoleih41** [comment]
Which C# code did you follow Did you follow [this sample code](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/BillingAgreementCreateAndExecute.aspx.cs).  Before you create a billing agreement  you have to create a billing plan and [activate it](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/BillingAgreementCreateAndExecute.aspx.cs#L61). For more information on how this API works, please read [here](https://developer.paypal.com/docs/api/payments.billing-plans#billing-plans_create).

**Comment by KlaasjanM** [comment]
Hi Xiaoleih41, 

Thanks mate, i found the missing line. I started that example, but the missing line was collapsed.

Regards,
Klaasjan
