### ISSUE TITLE
Paypal Marketplace .NET API

### ISSUE THREAD

**Issue by Masuzu** [paypal/PayPal-NET-SDK#327]
Hello,
I was just wondering whether it was on the roadmap to add support for Paypal Marketplace API calls (https://developer.paypal.com/docs/marketplaces/pp4mp/) or whether developers interested in using this feature should be responsible to implement their own API?

**Comment by pp-randy** [comment]
It is on the roadmap but will most likely only be added to version 2, which is in the works https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta.

**Comment by pp-randy** [comment]
I have additional clarification on this, so the Orders and Sync API we will try to get added some time today if all goes well.  

Which APIs from Marketplace solution are you looking for?

**Comment by bluk** [comment]
The Orders and Sync API are available on the [v2 branch](https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta). If there are other APIs you are looking for, please open a new issue or leave a comment. Thanks!
