### ISSUE TITLE
Is there a guide to migrate from 1.9.x to 2.0 beta?

### ISSUE THREAD

**Issue by jphellemons** [paypal/PayPal-NET-SDK#328]
### General information

* SDK/Library version: I had 1.9.x and updated to 2.0beta
* Environment: does not matter

### Issue description

I just updated the nuget and have so many broken namespaces now. Moving from 1.9 to 2.0 breaks everything. Is there a guide with breaking changes and how to resolve them? There are also a lot of new namespaces available.

**Comment by jphellemons** [comment]
For instance, following https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call
Where is the `OAuthTokenCredential` now? Visual Studio normally gives suggestions about which namespace to use, but cannot locate it in the 2.0 nuget.

**Comment by xiaoleih41** [comment]
You will have to have a PayPal account to sign up a billing agreement as it's not one time payment. The billing will be done through a saved payment method which has to be saved in an account.

**Comment by pp-randy** [comment]
Some details are here https://github.com/paypal/PayPal-NET-SDK/blob/2.0-beta/docs/Migrating.md, it covers the `OAuthTokenCredential` piece.

**Comment by pp-randy** [comment]
I encourage you to file issues, submit pull requests, or provide any other feedback on the 2.0 branch.
