### ISSUE TITLE
Missing PayPal Sync API support

### ISSUE THREAD

**Issue by haukepribnow** [paypal/PayPal-NET-SDK#329]
For my app, I need to retrieve information on past transactions. This is where the [PayPal Sync API](https://developer.paypal.com/docs/api/sync/) seems to come into play. Unfortunately, this API does not seem to be supported by PayPal-NET-SDK as of the current version.

On first glance, adding support for Sync to PayPal-NET-SDK does not seem to be very hard. I could do that. But before I start working on it: Could a pull request be possibly successful? Or is there a specific reason why Sync was left out of this repository so far?

**Comment by pp-randy** [comment]
We are looking into trying to get these added to the 2.0 beta branch https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta.  We will attempt to have Sync and Orders available later today if all goes well.

**Comment by haukepribnow** [comment]
Ah, really cool. Thank you for the quick reaction. I'm happy to test (and to contribute if you still have any missing parts).

**Comment by xiaoleih41** [comment]
Thank you, we will keep you posted.

**Comment by pp-randy** [comment]
The Pull for Sync is here if you want to take a look https://github.com/paypal/PayPal-NET-SDK/pull/331

**Comment by haukepribnow** [comment]
Tested it. The parts that I did test worked perfectly. (Also the beta API is much nicer.) Thanks a lot.

In the context of the Sync API, I got a related, but not .NET SDK-specific question: Can you tell me who I would need to address this topic to: https://stackoverflow.com/questions/48443992/paypal-sync-rest-api-how-to-retrieve-list-of-related-transactions-by-main-trans

In terms of the .NET SDK, I would be looking for something like this:
`new SearchGetRequest().PayPalReferenceId("AAAAAAAA")`

I would expect this request to give me all the transactions whose `PayPalReferenceId` field is set to `AAAAAAAA`.

Are you working both on the SDK and the API itself? Or would I need to open up a technical support request to address this feature request to the API developers?
