### ISSUE TITLE
BILLING.PLAN.UPDATED Incorrect Amount (Possible Serialization/CultureInfo Error)

### ISSUE THREAD

**Issue by uclaitsscott** [paypal/PayPal-NET-SDK#330]
PayPal Nuget package 1.8

### Issue description

I've created subscriptions and redirect to the PayPal site. Unfortunately the PayPal site still doesn't show you anything more than the description field and not the amount you're being charged, but that's another issue. So, I authorize the payment and get redirected back to my site to get the users acceptance and execute the agreement, however; I noted the webhook BILLING.PLAN.UPDATED gets sent directly after the BILLING.PLAN.CREATED and the amounts are multiplied by 100. In our case, the plan is 83.99, but the UPDATED webhook returns it as 8399 and instead of a tax of 7.77, it shows 777. I don't know if this is an issue with the API returning bad data or if the SDK is not properly serializing the data given globalization settings.

Actually I recorded the raw json data coming in and its definitely the API. Feel free to close.

**Comment by xiaoleih41** [comment]
It's a known issue. Please track this at https://github.com/paypal/PayPal-REST-API-issues/issues/182
