### ISSUE TITLE
Example Approvment and execute paypal payment

### ISSUE THREAD

**Issue by UltWolf** [paypal/PayPal-NET-SDK#336]
* Paypal v.2.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: cbbd181f87eb5
* Language, language version, and OS:  C#, NET CORE v 2.0 , Windows 10

Hello, everybody,  i have controller for create payment : {

     [HttpGet("create-payment")]
        public async Task<string> ConfirmAsync()
        {
            var environment = new SandboxEnvironment("Acc2-UPp-z25_Olh73h5VZB3XjR16eUKtL2lHoIc27IJn8-2f5R8-Kish229pYjzdy18KR8khHJRQO5Q", "EIb_0hbZQPAEioCGLAzVpn87zRswB7zLAoRtda06Oc4IhrDAmtGYAI2z6xYplX6TdARnsuVh2TC3tHNM");
            var client = new PayPalHttpClient(environment);
            var payment = new Payment()
            {
                Intent = "sale",
                Transactions = new List<Transaction>()
                {
                    new Transaction()
                    {
                        Amount = new Amount()
                        {
                      Total = "100.00",
                       Currency = "USD",
                      Details = new AmountDetails() 
                    {
                       Tax = "25",
                        Subtotal = "75"
                    }
                        },
                        ItemList = new ItemList()
                        {
                            Items = new List<Item>()
                            {
                                 new Item()
                                 {
                                     Name="SonyHeadPhones",
                                     Currency = "USD",
                                     Price = "15",
                                     Quantity = "5",
                                     Sku = "Sku",
                                     Tax  = "25",
                                     Description = "ITS ITEM!!!!!"
                                 }   
                            }
                             
                        }, Description = "JustSimplePayment",
                            
                    }
                },
                RedirectUrls = new RedirectUrls()
                {
                    CancelUrl = "http://paypal.com/cancel",
                    ReturnUrl = "http://paypal.com/return"
                },
                 Payer = new Payer()
                {
                    PaymentMethod = "paypal"
                }, 
                  NoteToPayer ="Please pay"
            };

            PaymentCreateRequest request = new PaymentCreateRequest();
            request.RequestBody(payment);
            
           
            try
            {
                HttpResponse response = await client.Execute(request);
                var statusCode = response.StatusCode;
                Payment result = response.Result<Payment>();
                return result.Id;
            }
            catch (HttpException httpException)
            {
                var statusCode = httpException.StatusCode;
                var debugId = httpException.Headers.GetValues("PayPal-Debug-Id").FirstOrDefault();
                return debugId;
            }

        }
 and execute :  

       [HttpGet("execute-payment")]
        public async void Execute([FromBody]string id)
        {
            var environment = new SandboxEnvironment("Acc2-UPp-z25_Olh73h5VZB3XjR16eUKtL2lHoIc27IJn8-2f5R8-Kish229pYjzdy18KR8khHJRQO5Q", "EIb_0hbZQPAEioCGLAzVpn87zRswB7zLAoRtda06Oc4IhrDAmtGYAI2z6xYplX6TdARnsuVh2TC3tHNM");
            var client = new PayPalHttpClient(environment);
            PaymentExecuteRequest request = new PaymentExecuteRequest(id);
                

            try
            {
                HttpResponse response = await client.Execute(request);
                var statusCode = response.StatusCode;
                Payment result = response.Result<Payment>();

            }
            catch (HttpException httpException)
            {
                var statusCode = httpException.StatusCode;
                var debugId = httpException.Headers.GetValues("PayPal-Debug-Id").FirstOrDefault();

            }

        }
but i cant aprovment my app, and finishing my transition, because i don`t know how, if i use example from previos versions it`s doesn`t work. Do  you have doc or example for this version paypal?
It`s very helpfull and nice for me.
With regards Vitaliy

**Comment by bluk** [comment]
First, you should update the RedirectUrls in the payment creation request:

```
RedirectUrls = new RedirectUrls()
            {
                CancelUrl = "http://yoursite.example.com/cancel",
                ReturnUrl = "http://yoursite.example.com/execute-payment"
            },
```
to point to a URL on your site (whatever URL your `execute-payment` is).

Second, after creating the payment, you should get the approval URL:

```
            HttpResponse response = await client.Execute(request);
            var statusCode = response.StatusCode;
            Payment result = response.Result<Payment>();
            LinkDescriptionObject approvalLink = findApprovalLink(result.Links);
            // HTTP Redirect the user to approvalLink.Href so they can approve the payment
```

with a helper method.

```
        private static LinkDescriptionObject findApprovalLink(List<LinkDescriptionObject> links) {
            foreach (var link in links) {
                if (link.Rel.Equals("approval_url")) {
                    return link;
                }
            }
            return null;
        }
```

Finally, in your `Execute` method, you will need to parse the query parameters for the `PayerId` and `paymentId` (not in the message body). So pseudocode would be something like:

```
public async void Execute(string PayerId, string paymentId) {
...
        PaymentExecuteRequest request = new PaymentExecuteRequest(paymentId);
        request.RequestBody(new PaymentExecution()
        {
            PayerId = PayerId
        });
...
}
```

Thanks for trying the beta. We will be updating the documentation as we finalize the API. If you have further questions, please feel free to leave a comment.

**Comment by UltWolf** [comment]
Yes, thx, it`s worked.)
Have a nice day,
With regards, Vitaliy

**Comment by Smithy80** [comment]
Hi guys, so glad I found this. There are several solutions out there that don't work!

**Comment by geno333** [comment]
Thanks @bluk , thanks to your code snippet i can now complete the sales  :)
But that leaves me with one question (i realize you wrote this two years ago, but ...)
I need to get the buyers email address so that i can build a registration key and send it to them. 
How do i pull the buyers info?
Thanks in advance, if you're still out there
