### ISSUE TITLE
Migration guide for 2.x

### ISSUE THREAD

**Issue by jphellemons** [paypal/PayPal-NET-SDK#337]
I have read https://github.com/paypal/PayPal-NET-SDK/blob/2.0-beta/docs/Migrating.md
and was wondering if `PayPalEnvironment` is for the live environment and the `SandboxEnvironment` is for testing and why the two have different signature. Sandbox only needs a secret key and client id.

And why is the HttpResponse in the Braintree namespace? `BraintreeHttp.HttpResponse` while everything else is in the `PayPal` namespace? 

Is there also a small guide or sample for `GetApprovalUrl` in 2.0? Or confirm transaction?

**Comment by jaypatel512** [comment]
Hey @jphellemons ! Thanks a lot for your feedback.

- About Environments, you have `SandboxEnvironment` and `LiveEnvironment`. PayPalEnvironment is super class of these environments and allows developers to create a new environment (Hint: MockEnvironment for testing) for their needs. I have updated the Migrating docs to have both Sandbox and Live comments.

- This SDK uses a BraintreeHttp Core library that provides the basic infrastructure for doing HTTP operations, including HttpClient, HttpRequest, HttpResponse. I agree that it feels a bit weird to use `BraintreeHttp` namespace in the project. We will try to find a better alternative if possible.

- That's an absolutely good idea to have that. We will try to add a Util class to fetch approvalUrl from Links. (PRs are welcome here if you feel excited).

**Comment by jphellemons** [comment]
I have forked the repo and am searching for the .net Core stuff. I have found the branch. Will try some commits and hopefully some pr's

**Comment by jphellemons** [comment]
I have another question. The guide catches an HttpException. But it's not `System.Web.HttpException`
https://msdn.microsoft.com/en-us/library/system.web.httpexception%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396
It's `BraintreeHttp.HttpException` What is the benefit of that HttpException compared to the frameworks version? When I read the migration code, I expected the frameworks version. Same for `BraintreeHttp.HttpResponse`. Is it an idea to update the migration guide to include `BraintreeHttp.` to make it more clear that it's not the frameworks default class which is being used?

**Comment by jaypatel512** [comment]
About your question for HttpClientFactory, we do use the base library functions of dotnet library, but encapsulate them to provide some extra features including serialization and deserialization of data, gzipping, ability to add injectors (to modify request on the fly). 

About `HttpException`, yes, we extend the IOException base class, and allow the ability to pass the `Headers` that came back as a part of response. This is important for merchants to figure out the `PayPal-Debug-Id`.

Do let us know if you have any further questions. We are absolutely loving your comments/suggestions, and will continue to improve/discuss them.

**Comment by bluk** [comment]
Closing this issue as it seems the questions have been answered. If there is any other feedback, please open an issue and let us know. Thanks!

**Comment by jphellemons** [comment]
Sorry to bother you guys, but is there more documentation about the GetApprovalUrl which was there in the 1.x version? 

> That's an absolutely good idea to have that. We will try to add a Util class to fetch approvalUrl from Links. (PRs are welcome here if you feel excited).

**Comment by bluk** [comment]
@jphellemons Can you open a new issue for this enhancement?
