### ISSUE TITLE
Is there any  IPN  available for PayFlowPro ?

### ISSUE THREAD

**Issue by iDarshn** [paypal/PayPal-NET-SDK#341]

**Comment by xiaoleih41** [comment]
If PayPal is the processor then yes, if the IPN is enabled on the PayPal account. It's not a feature that this SDK handles. You can check developer.paypal.com/support and confirm on the PayflowPro feature.

**Comment by bluk** [comment]
Closing this issue as this is not directly related to this SDK. [PayPal Technical Support](https://developer.paypal.com/support/) can help on Payflow Pro issues.
