### ISSUE TITLE
Order.Authorize() method is missing required parameter

### ISSUE THREAD

**Issue by dsyno** [paypal/PayPal-NET-SDK#342]
### General information

* SDK/Library version: 1.9.1
* Environment: Not applicable
* `PayPal-Debug-ID` values: Not applicable
* Language, language version, and OS: Not applicable

### Issue description

The Order.Authorize() method is supposed to take an APIContext object, and an Amount object (as detailed in the API docs: https://developer.paypal.com/docs/api/payments/#orders_authorize ).

However, the PayPal-NET-SDK only has the following two methods:
Order.Authorize(APIContext apiContext, Order order)
Order.Authorize(APIContext apiContext) <-- The Amount parameter is missing. (The Summary of the method even mentions that the Amount object should be there.)

The correct method should be:
Order.Authorize(APIContext apiContext, Amount amount)

I'm curious how something so fundamental being broken, yet no one has noticed it.

**Comment by dsyno** [comment]
Actually, it's missing more than that. The Order.Authorize() method also missing the "Order ID" parameter.

In the meantime, I'm going to try this workaround: Manually create an Order object, containing nothing but the "id" and "amount" variables, then pass that to Order.Authorize(APIContext apiContext, Order order).

**Comment by dsyno** [comment]
I was able to create a temporary workaround:
Manually create an Order object, containing nothing but the "id" and "amount" variables, then pass that to Order.Authorize(APIContext apiContext, Order order).

It's not ideal, since it's inconsistent with how your other methods work (especially it's sister method, Order.Capture()), and inconsistent with the API docs, and also few may figure out this workaround is possible.

Please include the fix in your next release. i.e. correcting the method to: Authorize(APIContext apiContext, string orderId, Amount amount)

Thank you,
Doug

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by xiaoleih41** [comment]
Could you please kindly submit a pull request for us to review? Thanks!

**Comment by dsyno** [comment]
Huh?

At any rate, here is what I believe the issue is:

You currently have the Authorize method as:
Order.Authorize(APIContext apiContext, Order order)
According to the API documentation, that should be:
Authorize(APIContext apiContext, string orderId, Amount amount)

Also, it appears the Refund method is similarly incorrect.
You currently have the Refund method as:
Capture.Refund(APIContext apiContext, string captureId, RefundRequest refundRequest)
According to the API documentation, that should be:
Capture.Refund(APIContext apiContext, string captureId, Amount amount)

Yes, it is possible to workaround these issues by using the objects you're requesting, however, that does not following the API documentation, it's confusing, and requires unnecessarily creating mostly empty objects.

So either the API documentation is incorrect, or your code is incorrect.

**Comment by bluk** [comment]
The Order parameter is used in cases where other fields are required beyond the Amount parameter as you discovered. The code was generated using internal schemas. There have been instances where some requests optionally allow individual fields present in the main body of the object (like this case), and it has been easier to allow the serialization of the object like Orders instead of requiring new methods with a new version of the SDK. I agree that it is potentially confusing and we'll try to document that better in the v2 SDK. Since you have a working solution for the v1 SDK, I'll close this issue.
