### ISSUE TITLE
GetApprovalUrl in 2.x core version of the SDK

### ISSUE THREAD

**Issue by jphellemons** [paypal/PayPal-NET-SDK#345]
As suggested here: https://github.com/paypal/PayPal-NET-SDK/issues/337#issuecomment-363197114

> We will try to add a Util class to fetch approvalUrl from Links. (PRs are welcome here if you feel excited).

So that there is a full payment sample for the new .Net Core Nuget package :)

Here is the referenced migration guide:
https://github.com/paypal/PayPal-NET-SDK/blob/2.0-beta/docs/Migrating.md

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by sucithrashanu** [comment]
@jphellemons  

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
