### ISSUE TITLE
WebhookEvent deserialization and validation

### ISSUE THREAD

**Issue by m0r6aN** [paypal/PayPal-NET-SDK#346]
I've created a Webhook for a few events. I'm able to tunnel to localhost and send an event from the simulator, but the entire object doesn't deserialize. I'm only able to navigate down to webhookEvent.resource, at which point it is just a json string. I've tried to deserialize the resource object, but nothing works. I need to be able to get the payers email address. ("coolbuyer@example.com" in the example below).  Additionally, payer information isn't sent with PAYMENT_SALE_COMPLETED so I need to know how to get the payers email address for those.

Also, every event from the simulator fails validation. 

`APIContext apiContext = GetApiContext();
            var requestheaders = HttpContext.Request.Headers;
            var requestBody = string.Empty;
            using (var reader = new StreamReader(HttpContext.Request.InputStream))
            {
                requestBody = reader.ReadToEnd();
            }

            var webhookEvent = JsonConvert.DeserializeObject<WebhookEvent>(requestBody);

            var json = webhookEvent.resource.ToString();

            json = json.Replace("\r\n", "");
            json = Regex.Unescape(json);
            var resource = JObject.Parse(json);

            // Ensure this event was genuinely sent by PayPal
            var isValid = WebhookEvent.ValidateReceivedEvent(apiContext, requestheaders, requestBody, "0UA38107XU1798338"); 

            if (!isValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Event was not valid");
            }   `

`{
"id": "WH-19973937YW279670F-02S63370HL636500Y",
"create_time": "2016-04-28T11:29:31Z",
"resource_type": "Agreement",
"event_type": "BILLING.SUBSCRIPTION.CREATED",
"summary": "A billing subscription was created",
"resource": {
    "agreement_details": {
        "outstanding_balance": {
            "value": "0.00"
        },
        "num_cycles_remaining": "5",
        "num_cycles_completed": "0",
        "final_payment_due_date": "2017-11-30T10:00:00Z",
        "failed_payment_count": "0"
    },
    "description": "desc",
    "links": [
        {
            "href": "https://api.paypal.com/v1/payments/billing-agreements/I-PE7JWXKGVN0R",
            "rel": "self",
            "method": "GET"
        }
    ],
    "id": "I-PE7JWXKGVN0R",
    "shipping_address": {
        "recipient_name": "Cool Buyer",
        "line1": "3rd st",
        "line2": "cool",
        "city": "San Jose",
        "state": "CA",
        "postal_code": "95112",
        "country_code": "US"
    },
    "state": "Pending",
    "plan": {
        "curr_code": "USD",
        "links": [],
        "payment_definitions": [
            {
                "type": "TRIAL",
                "frequency": "Month",
                "frequency_interval": "1",
                "amount": {
                    "value": "5.00"
                },
                "cycles": "5",
                "charge_models": [
                    {
                        "type": "TAX",
                        "amount": {
                            "value": "1.00"
                        }
                    },
                    {
                        "type": "SHIPPING",
                        "amount": {
                            "value": "1.00"
                        }
                    }
                ]
            },
            {
                "type": "REGULAR",
                "frequency": "Month",
                "frequency_interval": "1",
                "amount": {
                    "value": "10.00"
                },
                "cycles": "15",
                "charge_models": [
                    {
                        "type": "TAX",
                        "amount": {
                            "value": "2.00"
                        }
                    },
                    {
                        "type": "SHIPPING",
                        "amount": {
                            "value": "1.00"
                        }
                    }
                ]
            }
        ],
        "merchant_preferences": {
            "setup_fee": {
                "value": "0.00"
            },
            "auto_bill_amount": "YES",
            "max_fail_attempts": "21"
        }
    },
    "payer": {
        "payment_method": "paypal",
        "status": "verified",
        "payer_info": {
            "email": "coolbuyer@example.com",
            "first_name": "Cool",
            "last_name": "Buyer",
            "payer_id": "XLHKRXRA4H7QY",
            "shipping_address": {
                "recipient_name": "Cool Buyer",
                "line1": "3rd st",
                "line2": "cool",
                "city": "San Jose",
                "state": "CA",
                "postal_code": "95112",
                "country_code": "US"
            }
        }
    },
    "start_date": "2016-04-30T07:00:00Z"
},
"links": [
    {
        "href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-19973937YW279670F-02S63370HL636500Y",
        "rel": "self",
        "method": "GET",
        "encType": "application/json"
    },
    {
        "href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-19973937YW279670F-02S63370HL636500Y/resend",
        "rel": "resend",
        "method": "POST",
        "encType": "application/json"
    }
],
"event_version": "1.0"`

**Comment by xiaoleih41** [comment]
I am looking into this.

**Comment by xiaoleih41** [comment]
what's your complete JSON return?

**Comment by m0r6aN** [comment]
Here's the JSON for BILLING PLAN CREATED. 

`{
	"id": "WH-19973937YW279670F-02S63370HL636500Y",
	"create_time": "2016-04-28T11:29:31Z",
	"resource_type": "Agreement",
	"event_type": "BILLING.SUBSCRIPTION.CREATED",
	"summary": "A billing subscription was created",
	"resource": {
		"agreement_details": {
			"outstanding_balance": {
				"value": "0.00"
			},
			"num_cycles_remaining": "5",
			"num_cycles_completed": "0",
			"final_payment_due_date": "2017-11-30T10:00:00Z",
			"failed_payment_count": "0"
		},
		"description": "desc",
		"links": [
			{
				"href": "https://api.paypal.com/v1/payments/billing-agreements/I-PE7JWXKGVN0R",
				"rel": "self",
				"method": "GET"
			}
		],
		"id": "I-PE7JWXKGVN0R",
		"shipping_address": {
			"recipient_name": "Cool Buyer",
			"line1": "3rd st",
			"line2": "cool",
			"city": "San Jose",
			"state": "CA",
			"postal_code": "95112",
			"country_code": "US"
		},
		"state": "Pending",
		"plan": {
			"curr_code": "USD",
			"links": [],
			"payment_definitions": [
				{
					"type": "TRIAL",
					"frequency": "Month",
					"frequency_interval": "1",
					"amount": {
						"value": "5.00"
					},
					"cycles": "5",
					"charge_models": [
						{
							"type": "TAX",
							"amount": {
								"value": "1.00"
							}
						},
						{
							"type": "SHIPPING",
							"amount": {
								"value": "1.00"
							}
						}
					]
				},
				{
					"type": "REGULAR",
					"frequency": "Month",
					"frequency_interval": "1",
					"amount": {
						"value": "10.00"
					},
					"cycles": "15",
					"charge_models": [
						{
							"type": "TAX",
							"amount": {
								"value": "2.00"
							}
						},
						{
							"type": "SHIPPING",
							"amount": {
								"value": "1.00"
							}
						}
					]
				}
			],
			"merchant_preferences": {
				"setup_fee": {
					"value": "0.00"
				},
				"auto_bill_amount": "YES",
				"max_fail_attempts": "21"
			}
		},
		"payer": {
			"payment_method": "paypal",
			"status": "verified",
			"payer_info": {
				"email": "coolbuyer@example.com",
				"first_name": "Cool",
				"last_name": "Buyer",
				"payer_id": "XLHKRXRA4H7QY",
				"shipping_address": {
					"recipient_name": "Cool Buyer",
					"line1": "3rd st",
					"line2": "cool",
					"city": "San Jose",
					"state": "CA",
					"postal_code": "95112",
					"country_code": "US"
				}
			}
		},
		"start_date": "2016-04-30T07:00:00Z"
	},
	"links": [
		{
			"href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-19973937YW279670F-02S63370HL636500Y",
			"rel": "self",
			"method": "GET",
			"encType": "application/json"
		},
		{
			"href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-19973937YW279670F-02S63370HL636500Y/resend",
			"rel": "resend",
			"method": "POST",
			"encType": "application/json"
		}
	],
	"event_version": "1.0"
}`

**Comment by m0r6aN** [comment]
Sorry, not sure how to maintain the formatting here

**Comment by xiaoleih41** [comment]
This is a valid JSON. You should try `JObject.Parse(requestBody);` instead. You cannot validate the simulator generated events. Please take a look at https://developer.paypal.com/docs/integration/direct/webhooks/simulator/ where it explicitly states that you cannot verify the simulator generated events.

**Comment by xjijies** [comment]
@m0r6aN , Do you need any help further on this or shall I close this issue?
