### ISSUE TITLE
Payouts in 2.0

### ISSUE THREAD

**Issue by peter-bozovic** [paypal/PayPal-NET-SDK#347]
I'm testing 2.0 and it looks very good so far !
Thing that is missing hower are API for Payouts, which I will need for my project.
I saw that readme.md states that Payouts are not inclued, but It's not clear if they will be implemented for final release of 2.0 ?

Should I wait for final version to be able to use Payouts API, or look for some custom manual implementation for this part ?

**Comment by bluk** [comment]
We are waiting for an update to the Payouts internal API spec before generating the code for payouts in the 2.0 SDK. If your product needs to use payouts today, you will currently need to use some custom manual implementation or the 1.x version of the SDK.

**Comment by peter-bozovic** [comment]
Thank you for the reply.
So if I understand correctly, new Paypal Rest API v2 will be released soon, and then the Payouts API will be included in the SDK ?
This also explains the change between SDK 2.0 beta and RC where namespaces got additional v1 level.

Any timeline for this new API or SDK update ? If it will take too much time for v2 to come out, isn't it worth to implement Payouts for v1 in the meantime ?

**Comment by xiaoleih41** [comment]
We are trying to push this in a couple of weeks.

**Comment by buraktamturk** [comment]
Is there any update on this?

**Comment by CodeFuriate** [comment]
+1

**Comment by aeslinger0** [comment]
@xiaoleih41, What do you consider "a while"? Could we get an update on this please? Thanks.

**Comment by marcusbooyah** [comment]
Also would like an update on this. Is this project dead?

**Comment by sucithrashanu** [comment]
@peter-bozovic  

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
