### ISSUE TITLE
Rest API VoidAuthorization - Internal Server Error

### ISSUE THREAD

**Issue by jonathansyncsoft** [paypal/PayPal-NET-SDK#351]
### General information

* SDK/Library version: 2.0.0-rc2
* Environment: Sandbox
* `PayPal-Debug-ID` values: 6c897778c16c1
* Language, language version, and OS: .Net, WIN10

### Issue description
All Rest APIs are working fine for me, except `authorization void`.
```
var request = new AuthorizationVoidRequest(authId);
var response = await client.Execute(request);
            
```
> "Message": "",
> "StackTrace": "   at BraintreeHttp.HttpClient.<Execute>d__10`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n 

It always return an empty exception message. Is it an issue from the API or am I missing something in the code.
It would be helpful if anyone can help me on this.

**Comment by xiaoleih41** [comment]
Can you try again. We had some 500 error recently. It appears to be solved. Can you test it again?

**Comment by HoneyShyam** [comment]
Thank you, I'll check tonight and confirm.

**Comment by jonathansyncsoft** [comment]
I tested again, it is still returning an empty exception message.
Here is another debug-id: 9f3445c89bb67

**Comment by xiaoleih41** [comment]
What's the transI don't see any recent pending authorization. all of them are captured.

**Comment by jonathansyncsoft** [comment]
I just run another transaction today.
Authorization Id: 6S646985HK5582248
debug-id: a3d732ccbce0c

**Comment by trainerbill** [comment]
@jonathansyncsoft it looks like the authorization is pending due to a hold so you must have either payment review or fraud filters on your sandbox account.  You need to disable that, otherwise the easier option is to just generate a new sandbox seller account and REST App.

**Comment by jonathansyncsoft** [comment]
I checked and they are disabled. I tried creating new sandbox account and REST App, and result are the same. I don't think the authorization is in pending state, because I can capture and refund without any problem.
The only problem is the void authorization API. In any scenario, it will always failed and return empty exception message. Shouldn't it return some form of error message?

**Comment by xiaoleih41** [comment]
You cannot void a pending authorization. You can only void a completed authorization.

**Comment by xiaoleih41** [comment]
Can you provide a new debugId and the code you sent for capture? I cannot reproduce the issue.

**Comment by jonathansyncsoft** [comment]
DebugID : b9d66d9868c48

First, I create the payment
```
var request = new PaymentCreateRequest();
request.RequestBody(payment);
 
var response = await client.Execute(request).ConfigureAwait(false);
var payment = response.Result<Payment>();
```
Then, I execute the payment
```
var execution = new PaymentExecution{ PayerId = payerId };
var executeRequest = new PaymentExecuteRequest(paymentId);
executeRequest.RequestBody(execution);

var response = await client.Execute(executeRequest).ConfigureAwait(false);
var payment = response.Result<Payment>();
```
Then, I use the authorizationId provided from the execute payment response to void authorization. At this point the authorization state is **authorized**.
```
var request = new AuthorizationVoidRequest(cmd.AuthorizationID);
var response = await client.Execute(request).ConfigureAwait(false);
```
It throw an exception on **client.Execute(request)**

For SDK version 1.9, if I do capture first and then void authorization, it will return an error message like "captured payment cannot be void". However, in the new SDK version 2.0, it throw an exception.

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by jonathansyncsoft** [comment]
I figure out what cased the problem.
When I run the API with Postman, it will return success.
But when I use the SDK, it will return HTTP 500 because "Content-Type: application/json" in "Headers" is missing.
Please take a look on this bug.

**Comment by trainerbill** [comment]
@jonathansyncsoft are you saying the sdk is not sending the header as application/json?

https://github.com/paypal/PayPal-NET-SDK/blob/8edf8daa79da740fb79f0cc1d9082d0d8c17a49d/Source/SDK/Api/PayPalResource.cs#L163

**Comment by sveinumy** [comment]
Any update on this. Having the same problem. Only getting Internal server error back.

**Comment by salim7** [comment]
Ensure you have correct headers (like content-type).

**Comment by jonathansyncsoft** [comment]
Content-type is what causing this error, but you cannot edit the headers with PayPal API. Only getting internal server error on VoidAuthorization, which is strange..

**Comment by syunakh** [comment]
solution:
`
var voidReq = new AuthorizationVoidRequest(order.TransactionId);
voidReq.Content = new StringContent("{}");
voidReq.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
var executedPayment = (await ExecuteAsync(voidReq).ConfigureAwait(false)).Result<Authorization>();
`

**Comment by sucithrashanu** [comment]
@jonathansyncsoft 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community](https://www.paypal-community.com ) and  [MTS](https://paypal.com/mts) 
Thanks!
