### ISSUE TITLE
Getting "DUPLICATE_REQUEST_ID" - PayPal-Request-Id header was already used.

### ISSUE THREAD

**Issue by tjhackzy** [paypal/PayPal-NET-SDK#352]
> For internal tracking PPPLMER-50150

### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox (RestAPI)
* `PayPal-Debug-ID` values: "b8652476d439f","d5aba651d8ed7","a7a24cb889187"
* Language, language version, and OS:  Win10, c#

### Issue description

For sandbox Rest API direct payment, I am using PayPalPro sdk implemented in REST API.

I have checked and can confirm that the request which I am sending is totally okay. I have also used ResetRequestId() and manual guid() too but the sandbox environment keeps on saying  this error only.

I have provided debug IDs and it would be very helpful if you could tell me exactly what is happening here. 

Here's the request : {
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card": {
          "number": "",
          "type": "visa",
          "expire_month": ,
          "expire_year": ,
          "cvv2": "",
          "first_name": "JayVardhsdf",
          "last_name": "tri",
          "billing_address": {
            "phone": "9898989898",
            "line1": "maurayansh elanza",
            "line2": "",
            "city": "Ahmedabad",
            "country_code": "SV",
            "postal_code": "380015",
            "state": "Gujarat"
          }
        }
      }
    ],
    "payer_info": {
      "email": "Jay_c_tkkg_0@gmail.com"
    }
  },
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "149.65",
        "details": {
          "subtotal": "149.65",
          "shipping": "0",
          "tax": "0"
        }
      },
      "description": "SSL Certificates purchase from comodosslstore.com",
      "invoice_number": "COR82910405M70623",
      "item_list": {
        "items": [
          {
            "sku": "COR82910405M70623",
            "name": "SSL Certificates",
            "description": "SSL Certificates purchase from comodosslstore.com",
            "quantity": "1",
            "price": "149.65",
            "currency": "USD",
            "tax": "0"
          }
        ]
      }
    }
  ]
}

I have removed CC details here for security purposes and I am using  "payment_method": "credit_card" as I do not want to use BrainTree or other SDK at all.

Kindly provide me the solution asap as the support team here is directly closing this issue by saying "You need to use BrainTree SDK"  "Solution is provided and closing this ticket now".

Hope you guys understand this issue and help me solve this thing.

**Comment by xiaoleih41** [comment]
I have noted this. someone will be looking into this for you.

**Comment by tjhackzy** [comment]
@xiaoleih41 Any updates? I'm still getting the exact same error.

**Comment by prakash-gangadharan** [comment]
Hi @tjhackzy can you help us with the more context on this issue?

**Comment by prakash-gangadharan** [comment]
@tjhackzy , is this still an issues?

**Comment by prakash-gangadharan** [comment]
@tjhackzy, am closing this for now and please feel free to reopen if this is still an issue.
