### ISSUE TITLE
Webhook body re-serialization invalidates the webhook

### ISSUE THREAD

**Issue by yegorpetrov** [paypal/PayPal-NET-SDK#353]
### General information

* SDK/Library version: 2.0.0-rc2
* Environment: Sandbox
* `PayPal-Debug-ID` values: a0d23a3e30297 (success), 35800b1f389b6 (failure)

### Issue description

Unable to verify webhooks using `VerifyWebhookSignature`/`WebhookVerifySignatureRequest`. The result is always "FAILURE". The problem seems to be caused by re-ordering of webhook body's members when it's re-serialized as part of the `VerifyWebhookSignature<>`. The following comment mentions the same issue with the Python SDK: https://github.com/paypal/PayPal-Python-SDK/issues/175#issuecomment-265420813

    // this order has to be preserved: id, event_version, ...
    var webhookBody = "{\"id\":\"WH-SOME-ID\",\"event_version\":\"1.0\",...";

    var headers = default(IDictionary<string, string>);

    var verifyWebhookSignature = new VerifyWebhookSignature<Sale>
    {
        AuthAlgo = headers["paypal-auth-algo"],
        CertUrl = headers["paypal-cert-url"],
        TransmissionId = headers["paypal-transmission-id"],
        TransmissionSig = headers["paypal-transmission-sig"],
        TransmissionTime = headers["paypal-transmission-time"],
        WebhookId = "YOUR_WEBHOOK_ID",

        // we lose the original order by de-deserializing to this model
        /*
                public class Event<T>
                {
                    public string CreateTime;
                    public string EventType;
                    public string EventVersion;
                    public string Id;
                    ...
                }
        */
        WebhookEvent = JsonConvert.DeserializeObject<Event<Sale>>(webhookBody)
    };
    var request = new WebhookVerifySignatureRequest<Sale>()
        .RequestBody(verifyWebhookSignature);
    var result = new PayPalHttpClient(default(PayPalEnvironment))
        .Execute(request)
        .Result
        .Result<VerifyWebhookSignatureResponse>();

    // result.VerificationStatus is "FAILURE" 

I didn't really check in Wireshark or something, but I don't see anything to preserve the original order and deserializing things only to have them serialized back and checked against the original string is asking for trouble.

![image](https://user-images.githubusercontent.com/10397442/39366365-29b491fa-4a4d-11e8-8539-b9ee8898d9e4.png)

![image](https://user-images.githubusercontent.com/10397442/39366399-4081edce-4a4d-11e8-9a6d-8ebf47e46bf7.png)

This sounds more like a problem with the SDK rather than REST API issue (i.e. it can be resolved within the SDK). Just let users pass webhook's body as a string for verification, perhaps?

But in general, it feels super awkward to have JSON members follow some order. May be it really is a server-side issue.

**Comment by xiaoleih41** [comment]
The SDK team is looking into this.

**Comment by kspearrin** [comment]
Any news?

**Comment by sucithrashanu** [comment]
@yegorpetrov 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.
Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS](https://paypal.com/mts) 

Thanks!
