### ISSUE TITLE
Creating Payment - Can't Specify Shipping Preference - MALFORMED_REQUEST

### ISSUE THREAD

**Issue by sipi41** [paypal/PayPal-NET-SDK#356]
I'm trying to create a payment on SDK 2.0.0-rc2, please check my code as follow:

[Code Sample - Payment.txt](https://github.com/paypal/PayPal-NET-SDK/files/2023061/Code.Sample.-.Payment.txt)

Now, when I run this code it returns an error saying it was a **MALFORMED_REQUEST**, I checked my code twice and found no errors, at least not reported by intelli-sense or compilation, so I started removing some parts and at the end I did notice the problem is caused by the following piece of code: **ShippingPreferences = "NO_SHIPPING",** inside the ApplicationContext object.

Is this a bug? has anybody used this option in their code? or am I doing something wrong? Please advise.  As a final note, if I remove the shipping option, it creates the payment as expected...

**Comment by xiaoleih41** [comment]
Can you try `ShippingPreference` instead and see if it will solve the issue?

**Comment by sipi41** [comment]
If I try to use ShippingPreference an error is displayed saying the member does not exist, because I'm not building the json object directly but using the properties of the sdk object class, in this case Paypal.V1.Payments.Payment, so if I try to use a property that does not exist, it will throw an error and will not compile.

I think this should be reported as a bug, what do you think? would you please try to run my code? Thank you for your answer :-)

**Comment by aitiu** [comment]
I am facing same issue. it's a bug. following is the fix.

namespace PayPal.v1.Payments
{
    [DataContract]
    public class ApplicationContext
    {
        [DataMember(Name = "brand_name", EmitDefaultValue = false)]
        public string BrandName;
        [DataMember(Name = "landing_page", EmitDefaultValue = false)]
        public string LandingPage;
        [DataMember(Name = "locale", EmitDefaultValue = false)]
        public string Locale;
        **[DataMember(Name = "shipping_preference", EmitDefaultValue = false)]
        public string ShippingPreference;**
        [DataMember(Name = "user_action", EmitDefaultValue = false)]
        public string UserAction;

        public ApplicationContext() { }
    }
}

**Comment by carlosmorcerf** [comment]
Any solution?

**Comment by sucithrashanu** [comment]
@sipi41  

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
