### ISSUE TITLE
billing_agreement_id cannot be specified as a FundingInstrument when creating a reference transaction payment

### ISSUE THREAD

**Issue by ajbeaven** [paypal/PayPal-NET-SDK#357]
* SDK/Library version: 1.9.1.0

[The documentation](https://developer.paypal.com/docs/limited-release/reference-transactions/#use-a-reference-transaction-to-make-a-payment) for reference transaction via REST API state that you should be able to supply a `billing_agreement_id` as a funding instrument when creating a `PayPal.Api.Payment`.

It doesn't look like the SDK supports this as `PayPal.Api.FundingInstrument` does not have a `billing` property so you cannot specify a `billing_agreement_id`. Is there a separate nuget package that is used for limited-release features like REST API reference transactions or something?

I note that the PHP SDK does look like it supports this.

**Comment by ajbeaven** [comment]
So is this likely to be in 2.0 RTM or sometime after that? Any indication of when we could expect it?

**Comment by xiaoleih41** [comment]
There's no set timeline at this time. Please pay close look at the SDK updates.

**Comment by ajbeaven** [comment]
Sorry, why was this closed? This issue is not just a question - it's reporting a discrepancy between the documentation and the featureset of the SDK. 

It's a lot easier to follow this issue than continually review any changes to the SDK. Please consider leaving this open until this functionality exists within the SDK.
