### ISSUE TITLE
Getting constant UNKNOWN_ERROR in Production environement.

### ISSUE THREAD

**Issue by tjhackzy** [paypal/PayPal-NET-SDK#358]
### General information

* SDK/Library version: latest
* Environment:  Production
* `PayPal-Debug-ID` values: 857691f16e545,c4be3f0744e05,b940434c56307 AND MANY MORE
* Language, language version, and OS:  C#, WINDOWS SERVER

### Issue description
In production environment for paypal pro payment, we are getting
{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "5dcac643c3b07"
}

{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "a866085daaac4"
}

{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "9107dae2c1dd8"
}

{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "851e80cdecbc8"
} {
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "ae92dabdbd8e9"
} {
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "e5d2b4d02bedf"
} {
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "bfd9fa80c141"
} {
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "b940434c56307"
}

{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "c4be3f0744e05"
} {
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "857691f16e545"
}

Since last 3 hours.

Please see these debug IDs as this is production .

**Comment by trainerbill** [comment]
Is this still happening?  We had issues with some credit card processors around this time.

**Comment by xiaoleih41** [comment]
Close the issue as it is supposed to be solved.
