### ISSUE TITLE
Webhook verification is successful, what information should be returned?

### ISSUE THREAD

**Issue by bbhxwl** [paypal/PayPal-NET-SDK#363]
Webhook verification is successful, what information should be returned?
Response.Write("VERIFIED");
                Response.End();
The code I entered above doesn't seem to work. Or will always give me push events

**Comment by prakash-gangadharan** [comment]
A successful request returns the HTTP 200 OK status code and a JSON response body that shows the verification status (Possible values: **SUCCESS**, **FAILURE**). 
Developer API Reference link : https://developer.paypal.com/docs/api/webhooks/v1/#verify-webhook-signature-post-response

Sample Code : https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/VerifyWebhookSignature.aspx.cs
