### ISSUE TITLE
Invalid Sample Code

### ISSUE THREAD

**Issue by raupes** [paypal/PayPal-NET-SDK#369]
### General information
Your sample Code is invalid. For example:
`await client().Execute(request); // Remove brackets after client`

The current Code from the nuget package doesn't provide the Namespace 
`using PayPal.Payment;
`only
```
using PayPal.Core;
using PayPal.v1.Payments;
```
You should describe what to do with the result. For example:
```
                Payment result = response.Result<Payment>();

                string approvalLink = null;
                foreach (LinkDescriptionObject link in result.Links) {
                    if (link.Rel.Equals("approval_url")) {
                        approvalLink = link.Href;
                        break;
                    }
                }
Redirect(approvalLink);
```
And How do I get other payment Methods like creditcard? What to set in the PaymentMethod-Property?

* SDK/Library version: 2.0.0 Beta
* Environment: Sandbox
* Language, language version, and OS: .net core 2.0, EN, Windows10

**Comment by sucithrashanu** [comment]
@raupes 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
