### ISSUE TITLE
When will v2 be out of RC status

### ISSUE THREAD

**Issue by dwhaas82** [paypal/PayPal-NET-SDK#370]
When will 2.0 be released and out of Release Candidate status?

is v2.0.0-rc2 stable enough to be used in a production environment?

**Comment by AGelly** [comment]
I am also interested in when v2 will be fully released

**Comment by seraphx2** [comment]
Is anyone alive at PayPal?
It's been so long since V2 has been in RC, I hate to start in 1.9 and then V2 released onto NuGet a few days later.

**Comment by AGelly** [comment]
Man, its been 3 months since this was asked.

**Comment by g2petter** [comment]
I'm also interested in knowing this. We want to use the SDK for an application where modifying the `Web.Config` file is best avoided, and [according to this thread](https://github.com/paypal/PayPal-NET-SDK/issues/386) that will only be supported in V2.

**Comment by richsch** [comment]
@g2petter Ran into similar issue and have replied to that thread with details on how I'm setting my config.

**Comment by coultonluke** [comment]
Also interested..... where is the documentation?

**Comment by coultonluke** [comment]
I just created a thread on the community boards about this. https://www.paypal-community.com/t5/SDKs/Paypal-SDK-for-NET-core-is-dead/m-p/1733639

Feel free to message on there I wonder if we can get some eyes on it.

**Comment by KoanLeeroy** [comment]
Same old PayPal story as always. Surely the worst developer progress and relations in the FinTech industry... It's why we'll be dropping support for them.

**Comment by sucithrashanu** [comment]
@dwhaas82  

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
