### ISSUE TITLE
Cannot Execute a Billing Agreement (SDK 2.0.0-beta)

### ISSUE THREAD

**Issue by khively** [paypal/PayPal-NET-SDK#371]
### General information

* SDK/Library version: 2.0.0-beta
* Environment: Sandbox
* `PayPal-Debug-ID` values: f020ab6bcb71e
* Language, language version, and OS: C#, .Net Core 2.0, Win 10

### Issue description

I'm trying to setup a recurring billing agreement/subscription. I created a Plan, updated it to ACTIVE, successfully created the Billing Agreement, the customer approves it, and then when it returns to my URL so I can "execute" the agreement I have this code which always returns an error:

```
var client = GetPayPalClient(); // the client is working perfectly for the other calls
AgreementExecuteRequest aer = new AgreementExecuteRequest(token); // token is correct
BraintreeHttp.HttpResponse response = client.Execute(aer).Result;
```

An AggregateException is thrown which contains an HttpException, Internal Server Error. The paypal debug id is f020ab6bcb71e if that helps.

Is anyone else able to execute a billing agreement with the 2.0.0-beta SDK?

**Comment by jretchko** [comment]
I'm also receiving this error, after following the same steps. Everything has been successful and worked up until this point.

Running identical setup language/os/sdk wise.

**Comment by jackhardy1** [comment]
In order to fix this, when calling "client.Execute(agreementExecuteRequest)", you need to pass an empty JSON object in the body

**Comment by alirizaadiyahsi** [comment]
When do you intend to solve this issue?

**Comment by coultonluke** [comment]
Is anything good about using this library? :(

**Comment by sucithrashanu** [comment]
@khively  

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
