### ISSUE TITLE
.NET Restful API Capture will access Sandbox even if mode is live

### ISSUE THREAD

**Issue by Slipoch** [paypal/PayPal-NET-SDK#379]
This issue is still occurring:
[https://github.com/paypal/PayPal-NET-SDK/issues/244](https://github.com/paypal/PayPal-NET-SDK/issues/244)
[https://github.com/paypal/PayPal-NET-SDK/issues/169#issuecomment-251875150](https://github.com/paypal/PayPal-NET-SDK/issues/169)

Verified today that the workaround in the [second](https://github.com/paypal/PayPal-NET-SDK/issues/169#issuecomment-251875150) link still works, PayPal please update your documentation or fix this issue!

**Comment by sucithrashanu** [comment]
@Slipoch 
Do you still see this instances of this issue around? if yes please share us the recent PayPal-Debug-IDs to check further.

Thanks,

**Comment by Slipoch** [comment]
@sucithrashanu 
I never saw a resolution from PayPal. I haven't used paypal in some time now, so no idea if it is still occurring.
