### ISSUE TITLE
Refund Method is Obsolete. But where is the replacement 

### ISSUE THREAD

**Issue by anticoagulant** [paypal/PayPal-NET-SDK#381]
### General information

* SDK/Library version: 1.9.1.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: NA
* Language, language version, and OS: c# .NET

### Issue description

I'm attempting to make a payment refund. 

The sample code calls the Refund ([%ApiContext%], [%RefundObj%]) function on the Sale object. However this gives the warning:
    'PayPal.Api.Sale.Refund is obsolete: Please use Refund(ApiContext, string, RefundRequest) instead

Where is the function we are intended to use? I can't see this method anywhere in the sdk. Could you please let me know where it is located?

Also could you update the sample code to show the intended current usage?

Thanks

**Comment by koyfo** [comment]
Use PayPal.Api.**RefundRequest** object insead of PayPal.Api.Refund

**Comment by anticoagulant** [comment]
> Use PayPal.Api.**RefundRequest** object insead of PayPal.Api.Refund

Thanks for your reply. That's exactly what I tried as soon as I saw the obsolete message. 

My problem is that once I create a RefundRequest object I don't know what to do with it. The refund method only takes a refund object. I'm assuming there's a method somewhere that takes the request object but I can't find anything. I was really hoping to get a pointer as to what to do with that object once created (sorry if my question wasn't clear on this).

**Comment by koyfo** [comment]
```cs
Sale.Refund(apiContext, saleID, redundRequest); // for captured payments
Capture.Refund(apiContext, captureID, redundRequest); // for authorized payments
```

**Comment by adenke** [comment]
I'm running into this exact problem right now. My program just recently started failing on every refund, so I just switched over to the RefundRequest object. I'm no longer getting the warning about using an obsolete method, but I can't get the exact syntax correct to process the refund. I keep getting a "The remote server returned an error: (400) bad request.

Here's my relevant code:

```
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);
            Sale CheckTheSale = new Sale();

            //Refund refundforreal = new Refund();
            DetailedRefund refundforreal = new DetailedRefund();

            CheckTheSale = Sale.Get(apiContext, lblRelatedOrder.Text);
            string MaxAmountToRefund = CheckTheSale.amount.total;
            //MaxAmountToRefund is the original amount and will not include any refunds to date
            string SalesStatus = CheckTheSale.state;
            //SalesStatus will show if it is partially refunded
            Amount refundAmount = new Amount();
            decimal NumericTotal = Convert.ToDecimal(lblTotal.Text) * -1;
            refundAmount.total = NumericTotal.ToString();
            string RefundCurrency = "USD";
            refundAmount.currency = RefundCurrency;
            RefundRequest refund = new RefundRequest();
            refund.description = "Returned items.";
            refund.reason = "";
            foreach (DataGridViewRow r in grdOrderItems.Rows)
            {
                if (r.Cells[1].Value != null)
                {
                    refund.reason = refund.reason + r.Cells[1].Value.ToString() + " ";
                }
            }
            refund.amount = refundAmount;
            string saleId = lblRelatedOrder.Text;
            Sale sale = new Sale();
            sale.id = saleId;

            try
            {
                // Refund sale
                refundforreal =  Sale.Refund(apiContext, saleId, refund);

            }

```
This fails every time. What am I missing?

**Comment by adenke** [comment]
If nothing else, I could use a method to get to more specifics on what is failing - the 400 error just isn't that helpful. I know that I have valid authorization - the apiContext variable contains everything  believe it should. This was working up until a couple of days ago using the obsolete Refund object rather than the RefundRequest object. I'm just completely stuck and can't find documentation anywhere that shows how to do this - this thread is my best hope right now.

**Comment by adenke** [comment]
All right. I finally got this to work. But I'm a bit confused. I've always been able to set the refund reason to our product description, which may have characters like "/" in it (or other things). As soon as I set the refund reason to "returned items", the refund processed normally. Has there been some change to the properties of the reason field?
