### ISSUE TITLE
Payment Issue

### ISSUE THREAD

**Issue by ghost** [paypal/PayPal-NET-SDK#382]
### General information
* SDK/Library version: 1.9.1
* Environment: Sandbox 
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: C# .NET

### Issue description
Sandbox checkout was working fine in the last Six months but the last two weeks showing this error "Sorry, we can’t complete your purchase at this time, Please return to the merchant and choose another way to pay."
![capture](https://user-images.githubusercontent.com/43513155/45926285-62f74b80-bf21-11e8-8e30-841009fc9c28.JPG)

**Comment by prakash-gangadharan** [comment]
@ghost this issue still exists?

**Comment by prakash-gangadharan** [comment]
@ghost, am closing this for now and please feel free to reopen if this is still an issue.
