### ISSUE TITLE
The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by ghost** [paypal/PayPal-NET-SDK#383]
### General information
* SDK/Library version: 1.9.1
* Environment: Production
* `PayPal-Debug-ID` values: b60bfde1e17c1,b60bfde1e17c1
* Language, language version, and OS: C# .NET

### Issue description
Live mode checkout returns this authentication error "The remote server returned an error: (401) Unauthorized" and kindly be informed that I have checked client id and secret key and I am sure it is valid.

**Comment by koyfo** [comment]
It is a bug. You must set again the configuration after getting token.

`var config = new Dictionary<string, string> { { "mode", "live" } };

var accessToken = new OAuthTokenCredential("ClientID", "Secret", config);
var apiContext = new APIContext(accessToken.GetAccessToken());
apiContext.Config = config;`

**Comment by ost1m1ron** [comment]
//hey dude i am newbie, but i find that code from tutorial
// craete in paypal site create app and take clientId and secret
// create web.config or app.config

            get a reference to the config
             var config = configmanager.instance.getproperties();

            // use oauthtokencredential to request an access token from paypal
            var accesstoken = new oauthtokencredential(config).getaccesstoken();

            var apicontext = new apicontext(accesstoken);

            // initialize the apicontext's configuration with the default configuration for this application.
            apicontext.config = configmanager.instance.getproperties();

            // define any custom configuration settings for calls that will use this object.
            apicontext.config["connectiontimeout"] = "3000"; // quick timeout for testing purposes

            // define any http headers to be used in http requests made with this apicontext object
            if (apicontext.httpheaders == null)
            {
                apicontext.httpheaders = new dictionary<string, string>();
            }


            // apicontext.httpheaders["accept"] = "application/json";
            apicontext.httpheaders["accept-language"] = "en_us";

            var payment = payment.get(apicontext, "pay-0xl713371a312273yke2gcni");

**Comment by prakash-gangadharan** [comment]
Hi @ghost and @ost1m1ron , take a glimpse at the below links to make you first call using the PayPal-NET-SDK.
**Configuration**:
https://github.com/paypal/PayPal-NET-SDK/wiki/Configuration
**Make Your First Call**:
https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call
