### ISSUE TITLE
i have error 401 (i am newbie)

### ISSUE THREAD

**Issue by ost1m1ron** [paypal/PayPal-NET-SDK#384]
//this is app.config

 <configSections>
      <section name="paypal" type="PayPal.SDKConfigHandler, PayPal" />
    </configSections>

    
    <paypal>
      <settings>
        <add name="mode" value="sandbox" />
        <add name="clientId" value="Aa9qsyiAd6asLaGeY3wsJ_xw8p_I2L2xjIdwA-pd2CfcN12K9OEBtGDXlP6_skasagdevosjKqbatavekEJ2" />
        <add name="clientSecret" value="ECSl38asdG_ZDsazS396MEW2zzK9idy-Iu_aglRZD3a8BYsMC8JStcbYaP8b_rpxkUZxDCc9zdPab9Epdn2l" />
      </settings>
    </paypal>

//this is c# code
// Get a reference to the config
            var config = ConfigManager.Instance.GetProperties();

            // Use OAuthTokenCredential to request an access token from PayPal
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();

            var apiContext = new APIContext(accessToken);

            // Initialize the apiContext's configuration with the default configuration for this application.
            apiContext.Config = ConfigManager.Instance.GetProperties();

            // Define any custom configuration settings for calls that will use this object.
            apiContext.Config["connectionTimeout"] = "1000"; // Quick timeout for testing purposes

            // Define any HTTP headers to be used in HTTP requests made with this APIContext object
            if (apiContext.HTTPHeaders == null)
            {
                apiContext.HTTPHeaders = new Dictionary<string, string>();
            }

            apiContext.HTTPHeaders["Content-Type"] = "application/json";

            var payment = Payment.Get(apiContext, "PAY-0XL713371A312273YKE2GCNI");

my t

**Comment by ost1m1ron** [comment]
I try to change https headers but it cant help.
i see in debug i take acces token, but when i get payment goes exception (sorry english not my first languest)

**Comment by koyfo** [comment]
```cs
var config = new Dictionary<string, string> { { "mode", "sandbox" } };

var accessToken = new OAuthTokenCredential("__YourClientID__", "__YourSecret__", config);
var apiContext = new APIContext(accessToken.GetAccessToken());
apiContext.Config = config;

var ch = Payment.Create(apiContext, new Payment
{
	intent = "sale",
	payer = new Payer() { payment_method = "paypal" },
	redirect_urls = new RedirectUrls
	{
		cancel_url = "http://google.com",
		return_url = "http://google.com"
	},
	transactions = new List<PayPal.Api.Transaction> {
		new PayPal.Api.Transaction
		{
			amount = new Amount
			{
				currency = "USD",
				total = "50"
			},
			item_list = new ItemList
			{
				items = new List<Item>{new Item
				{
					quantity = "2",
					name = "Chairs",
					description = "",
					price = "25",
					currency = "USD"
				}}
			}
		}
	}
});

var chargeID = ch.id;
```

**Comment by ost1m1ron** [comment]
i have in sandbox account how i can do transactions account to account ?
and how to use bulk upload(he is only in site) i use simple console project
need in console app create account un sandbox can you help me please

**Comment by prakash-gangadharan** [comment]
@ost1m1ron , You can create test accounts in sanbox via https://developer.paypal.com/ by logging in to the developer dashboard.
