### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by tschneideriii** [paypal/PayPal-NET-SDK#386]
Is there an option to not use the app.config or web.config ?

**Comment by Onikiro** [comment]
As I know, in version 2.0-beta you will not need config files to initialization. But stable version and 2.0-beta are very different. 
[More about 2.0 version](https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta)

**Comment by richsch** [comment]
I'm using v1.9.1 (but having other issues around setting `no_shipping` etc) and can set config outside of web.config. (I don't have any `PayPal` section in my web.config) I've added these helper methods (`App.Common.Configuration` is my access point to web/app.config - you could use something similar to get the settings from wherever):

```
        public static APIContext GetApiContext()
        {
            var config = ConfigManager.GetConfigWithDefaults(GetConfig());

            // Use OAuthTokenCredential to request an access token from PayPal
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);
            apiContext.Config = config;
            return apiContext;
        }

        private static Dictionary<string, string> GetConfig()
        {
            return new Dictionary<string, string>
            {
                ["mode"] = App.Common.Configuration.PayPal.UseSandbox ? "sandbox" : "live",
                ["clientId"] = App.Common.Configuration.PayPal.ClientId,
                ["clientSecret"] = App.Common.Configuration.PayPal.ClientSecret,
                ["endpoint"] = App.Common.Configuration.PayPal.ServiceUrl
            };
        }
```

The property names for the config came from [here](https://github.com/paypal/PayPal-NET-SDK/wiki/Configuration) (they're the same names as what goes into the `web.config`)

Hope this helps anyone else who was battling with this!

**Comment by prakash-gangadharan** [comment]
Hi @tschneideriii, I hope your question was answered by @richsch through the above comment hence closing this issue out. Please reopen the same if you are still facing any challenges.

Thanks!
