### ISSUE TITLE
Type of field status in Search class is not good format for PayPal Server.

### ISSUE THREAD

**Issue by ghost** [paypal/PayPal-NET-SDK#387]
### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox 
* `PayPal-Debug-ID` values: (i don't known)
* Language, language version, and OS: .NET, Framework v4, Windows

### Issue description

Type of field _Status_ in _Search_ class is not good format for PayPal Server.
Paypal documentation defines _Status_ in search request as an array

https://developer.paypal.com/docs/api/invoicing/v1/#search
status enum
The invoice status. To search by status, specify this value as an array. For example, "status": ["REFUNDED"]

### Technical information

Class : PayPal.Api.Invoice 
Method : public static InvoiceSearchResponse Search(APIContext apiContext, Search search);

Request
{
  "status": "PAID",
  "page": 1.0,
  "page_size": 10.0,
  "total_count_required": true
}

Response
{
  "name": "VALIDATION_ERROR",
  "message": "Invalid request - see details.",
  "information_link": "https://developer.paypal.com/docs/api/invoicing/#errors",
  "details": [
    {
      "field": "status",
      "issue": "Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token at line:1, column:11"
    }
  ]
}

**Comment by xjijies** [comment]
Hi @ghost,

We will consider this in our next V2 version of API. Thanks for your suggestion. now I am closing this issue
