### ISSUE TITLE
Validation failed on Certificate Matching...

### ISSUE THREAD

**Issue by skdutta-ga** [paypal/PayPal-NET-SDK#388]
The following test in the sdk test project failed: WebhookEventValidateReceivedEventValidTest in file WebhookEventTest.cs

Then I created a test using the webhook simulator. Then got the HTTP headers from the client side. Also put the correct ClientId and ClientSecret in app.config. It failed again.

Am I missing anything?

**Comment by sucithrashanu** [comment]
@skdutta-ga 
Can you give clear context of the Issue? Or Else share the recent PayPal- Debug-Id?

Thanks
