### ISSUE TITLE
Object application_context incorrectly created causes MALFORMED_REQUEST response

### ISSUE THREAD

**Issue by insanidade** [paypal/PayPal-NET-SDK#389]
* SDK/Library version: v2.0.0-rc2
* Environment: both
* `PayPal-Debug-ID` values: 63cb2881ddba2
* Language, language version, and OS: .NET

### Issue description
I work at Paypal and have a merchant who urgently needs a fix for that. You can find me through odefranca@paypal.com

Below you can find an example of a correctly defined application_context object.

"application_context": {
    "brand_name": "My Brand Name",
    "landing_page": "Login",
    "locale": "pt_BR",
    "shipping_preference": "SET_PROVIDED_ADDRESS",
    "user_action": "commit"
  }

Issue is: shipping_preference attribute is misspelled when defined in PayPal.v1.Payments.ApplicationContext class:

 
        [DataMember(Name="shipping_preferences", EmitDefaultValue = false)]
        public string ShippingPreferences;

Notice the extra 's' character at the end of the attribute name.

**Comment by insanidade** [comment]
I work at Paypal and have a merchant who urgently needs a fix for that. You can find me through odefranca@paypal.com

**Comment by carlosmorcerf** [comment]
Any solution?

**Comment by sucithrashanu** [comment]
Hi @insanidade 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
