### ISSUE TITLE
PayPal transactions are not visible in Merchant account

### ISSUE THREAD

**Issue by gaganbajaj1** [paypal/PayPal-NET-SDK#390]
### General information

* SDK/Library version: SDK 2.0.0-beta
* Environment: Sandbox
* `PayPal-Debug-ID` values:
* Language, language version, and OS: C#, .Net core 2.1, Windows server 2016
### Issue description

Hi,

I am using SDK 2.0.0-beta version with .net core 2.1 webapi to integrate with paypal in sandbox environment using redirection flow. 

I am able to integrate it successfully with paypal, and payment process completes with success response.
But when I look into merchant account, transactions are not available there.

Please find my code below:
`
public string CreatePayment()
        {
            
            var clientId = "XXXXXXXXXXX";
            var secret = "XXXXXXXXXXXXXXXXX";
            var environment = new SandboxEnvironment(clientId, secret);
            var client = new PayPalHttpClient(environment);

            var request = BuildPaymentRequest(paymentDetails);

            var result = ExecutePaymentRequest(client, request);

            return result;

        }

private PaymentCreateRequest PaymentRequest()
{
var payment = new PayPal.v1.Payments.Payment()
            {
                Intent = "sale",
                Transactions = new List<Transaction>()
                    {
                        new Transaction()
                        {
                            Amount = new Amount()
                            {
                                Total = "10",
                                Currency = "USD"
                            }
                        }
                    },
                RedirectUrls = new RedirectUrls()
                {
                    ReturnUrl = "http://test.com/success",
                    CancelUrl = ""http://test.com/cancel""
                },
                Payer = new Payer()
                {
                    PaymentMethod = "PayPal"
                }
            };

            PaymentCreateRequest request = new PaymentCreateRequest();
            return request.RequestBody(payment);
}

private async string ExecutePayment(PayPalHttpClient client, PaymentCreateRequest request)
        {
            System.Net.HttpStatusCode statusCode;
            PaymentDetails paymentDetails = null;
            
                BraintreeHttp.HttpResponse response = await client.Execute(request);
                statusCode = response.StatusCode;
                Payment result = response.Result<Payment>();
                string redirectUrl =
                    result.Links.Where(x => x.Rel.Equals("approval_url")).Select(y => y.Href).SingleOrDefault();

               return redirectUrl ;
        }
`

Multiple transactions are done using this code but none of them appear in merchant sandbox account. Merchant sandbox account is created  with following process:

1. login to : https://developer.paypal.com/developer/applications/
2. Created a merchant and buyer account inials Accounts section
3. Goto MyApps and credentials
4. Create a new app in REST API apps
5. Click on the app and get clientid and secret
6. use client id and secret in .net core project.

Can someone help us with this?

Please find the attached image for your reference

Thanks & Regards,
Gagan Bajaj
![capture](https://user-images.githubusercontent.com/42176612/46822979-9142ab00-cdaa-11e8-8ca4-c044fe710875.PNG)

**Comment by mmikirtumov** [comment]
This issue is duplication of #391 and can be closed.

**Comment by prakash-gangadharan** [comment]
similar issue : https://github.com/paypal/PayPal-NET-SDK/issues/391
