### ISSUE TITLE
PayPal transactions are not visible in Merchant account

### ISSUE THREAD

**Issue by gaganbajaj** [paypal/PayPal-NET-SDK#391]
### General information

SDK/Library version: SDK 2.0.0-beta
Environment: Sandbox
PayPal-Debug-ID values:
Language, language version, and OS: C#, .Net core 2.1, Windows server 2016

### Issue description

Hi,

I am using SDK 2.0.0-beta version with .net core 2.1 webapi to integrate with paypal in sandbox environment using redirection flow.

I am able to integrate it successfully with paypal, and payment process completes with success response.
But when I look into merchant account, transactions are not available there.

Please find my code below:
`
public string CreatePayment()
{

        var clientId = "XXXXXXXXXXX";
        var secret = "XXXXXXXXXXXXXXXXX";
        var environment = new SandboxEnvironment(clientId, secret);
        var client = new PayPalHttpClient(environment);

        var request = BuildPaymentRequest(paymentDetails);

        var result = ExecutePaymentRequest(client, request);

        return result;

    }
private PaymentCreateRequest PaymentRequest()
{
var payment = new PayPal.v1.Payments.Payment()
{
Intent = "sale",
Transactions = new List()
{
new Transaction()
{
Amount = new Amount()
{
Total = "10",
Currency = "USD"
}
}
},
RedirectUrls = new RedirectUrls()
{
ReturnUrl = "http://test.com/success",
CancelUrl = ""http://test.com/cancel""
},
Payer = new Payer()
{
PaymentMethod = "PayPal"
}
};

        PaymentCreateRequest request = new PaymentCreateRequest();
        return request.RequestBody(payment);
}

private async string ExecutePayment(PayPalHttpClient client, PaymentCreateRequest request)
{
System.Net.HttpStatusCode statusCode;
PaymentDetails paymentDetails = null;

            BraintreeHttp.HttpResponse response = await client.Execute(request);
            statusCode = response.StatusCode;
            Payment result = response.Result<Payment>();
            string redirectUrl =
                result.Links.Where(x => x.Rel.Equals("approval_url")).Select(y => y.Href).SingleOrDefault();

           return redirectUrl ;
    }
`

Multiple transactions are done using this code but none of them appear in merchant sandbox account. Merchant sandbox account is created with following process:

login to : https://developer.paypal.com/developer/applications/
Created a merchant and buyer account inials Accounts section
Goto MyApps and credentials
Create a new app in REST API apps
Click on the app and get clientid and secret
use client id and secret in .net core project.
Can someone help us with this?

Please find the attached image for your reference

Thanks & Regards,
Gagan Bajaj
![capture](https://user-images.githubusercontent.com/23055959/46823212-2fcf0c00-cdab-11e8-9054-5ba3aae20ced.PNG)

**Comment by buraktamturk** [comment]
You need to execute the payment itself after user agrees to pay and redirected back to your site, unless you do it, the user is not charged and you dont get paid.

```csharp
var request = new PaymentExecuteRequest(payment_id);

request.RequestBody(new PaymentExecution() {
    PayerId = payer_id
});

var response = await paypal.Execute(request);
var payment = response.Result<Payment>();

if (payment.State != "approved") { // no blance or something else?
    throw new Exception("Failed to execute your payment: " + payment.FailureReason);
}
```

**Comment by kkagill** [comment]
@buraktamturk How did you get the payer_id? I tried via 

`HttpResponse response = await client.Execute(request);
                    var statusCode = response.StatusCode;
                    Payment result = response.Result<Payment>();

                    PaymentExecuteRequest paymentExecuteRequest = new PaymentExecuteRequest(result.Id);
                    paymentExecuteRequest.RequestBody(new PaymentExecution()
                    {
                        PayerId = result.Payer.PayerInfo.PayerId
                    });`

but result.Payer.PayerInfo.PayerId was null. How can I get this?

**Comment by buraktamturk** [comment]
@kkagill payer_id is coming from the callback request as a query string parameter.

**Comment by kkagill** [comment]
@buraktamturk yes I know that it's a callback. I used to get payerID using other SDK. 

    public IActionResult ExecutePayment(string paymentID, string payerID)

but for 2.x not sure which callback i should use. For example, I got `payment_id` from 

    Payment result = response.Result<Payment>();
    PaymentExecuteRequest paymentExecuteRequest = new PaymentExecuteRequest(result.Id);

but which code returns `payer_id`?

**Comment by buraktamturk** [comment]
@kkagill 

Nothing returns payer_id here, in order to execute the payment: 

1. You need to create the payment (I guess you did this part) with a callback url,
2. You redirect the user to approval_url that get as a response from 1st step,
3. User agrees to pay you, PayPal will redirect the user to your callback url (where you set it on 1st step) with three query string parameters (payment_id, token and payer_id). 
4. You execute the request.

**Comment by kkagill** [comment]
@buraktamturk You are right. I need to send the user to paypal to approve the payment, then it will redirect to callback url. Thanks, btw is this working in live mode? and good to use for production?

**Comment by buraktamturk** [comment]
@kkagill Great it worked for you. The library is working on live mode and it is good to use it in Production (better than the previous in terms of everything).

The missing thing is the payouts feature, but if you do not use this feature then everything is good. I had to rollback to the old version just because of this feature.

**Comment by kkagill** [comment]
@buraktamturk Thanks a lot!

**Comment by prakash-gangadharan** [comment]
Hi @gaganbajaj / @kkagill, we hope @buraktamturk replies resolved your query. Please let us know if you are facing any challenges.
