### ISSUE TITLE
INTERNAL_SERVICE_ERROR when creating a payment

### ISSUE THREAD

**Issue by MaximShchukin** [paypal/PayPal-NET-SDK#395]
**General information**

    SDK/Library version: 1.9.1
    Environment: Sandbox
    PayPal-Debug-ID values: ae1171f9c8ce7
    Language, language version, and OS: .net 4.7, C#7, asp.net mvc, Windows 10

**Issue description**

When trying to create new  payment, we always get "Internal Server Error".

Find below the response we get from Paypal API:
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"ae1171f9c8ce7"}

**Comment by prakash-gangadharan** [comment]
Hi @MaximShchukin , I understand this is the very old issue and looks like it was unattended for a while. Do you still see this instances of this issue around? if yes please share us the recent PayPal-Debug-IDs to check further.

**Comment by prakash-gangadharan** [comment]
@MaximShchukin, am closing this for now and please feel free to reopen if this is still an issue.
