### ISSUE TITLE
recurring payment on 3rd of the month, with an immediate payment now

### ISSUE THREAD

**Issue by AKassir** [paypal/PayPal-NET-SDK#396]
### General information

* SDK/Library version: v.1.9.1
* Environment: Sandbox / Live
* Language, language version, and OS: VB.NET on VS2017, Windows 10

### Issue description
Hello folks,

I have a product that shoulb charge my customer EUR 5,-/month.
I want the recurring payments happens at every 3rd day of a month. So far so good, I can setup my AGREEMENT to start at 03.[next_month].

Well but I want to charge my customer for the days separating now from next payment issue, because I have to generate a software license, and the process can be only done if a payment already occures.

Saying, my customer ordered a product for EUR 5,-/month on 2018-11-17 (nov 17th).
I setup a plan with a "REGULAR" payment_definition like this:
```
Dim paymentDefinitions As New List(Of PayPal.Api.PaymentDefinition)
paymentDefinitions.Add(New PayPal.Api.PaymentDefinition With {
            .type = "REGULAR",
            .frequency = MONTH,
            .frequency_interval = 1,
            .cycles = 0,
            .charge_models = chargeModels,
            .amount = Tools.GetCurrency(5, "EUR"),
            .name = "PAYMENT DEFINITION NAME"
})
```

My agreement definition looks like:
```
Dim agreement As New PayPal.Api.Agreement With {
        .plan = New PayPal.Api.Plan With {.id = createdPlan.id},
        .name = "AGREEMENT NAME",
        .description = "AGREEMENT DESC",
        .start_date = Now.AddMonth(+1).ToString("yyyy-MM-03THH:mm:ss") + "Z",
        .payer = New PayPal.Api.Payer With {
                .payment_method = "paypal"
        }
}
```

Than, customer have to be charged for the beginning days as of 30 (days in november) - 17 (starting agreement day) + 3 (charging model on every 3rd day of the month) = 16 days to be charged for.
Customer have to be charged EUR (5*16/31) = EUR 2,58 --> ONCE and IMMEDIATLY

How can I proceed this.
Any kind of help will be appreciated,
thanks much

**Comment by prakash-gangadharan** [comment]
@AKassir, can we get some more clarity on this requirement from you?

**Comment by prakash-gangadharan** [comment]
@AKassir, we further looking forward for your inputs.

**Comment by xjijies** [comment]
@AKassir I am closing this issue now, If you need any help further, reopen the issue
