### ISSUE TITLE
Clarification: Does Refunding a Pending Payment incur a charge?

### ISSUE THREAD

**Issue by anticoagulant** [paypal/PayPal-NET-SDK#397]
### General information

* SDK/Library version: 1.9.1.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: NA
* Language, language version, and OS: c# .NET

### Issue description

When making a payment, the nature of my business requires that a purchase is either completed or not, at the point the success callback in made. 

Business accounts will be set up with that in mind, so we will be doing everything we can to avoid pending payments, preferring instead to treat requiring manual intervention as unsuccessful.

I understand (the SDK and API docs on this are very fluffy) that the correct approach is to refund the payment if it is pending (please correct me if I am wrong on this point as it probably nullifies the rest of this issue if I am).

I also understand issuing a refund incurs a charge. My question is : Is this true of refunding a pending transaction? Or just when refunding a sale or a completed payment?

Can the business account be set up to treat pending transactions as unsuccessful - thereby saving me a fair bit of coding and logic? 

Thanks

**Comment by xjijies** [comment]
@anticoagulant 
Refer this, [https://developer.paypal.com/docs/integration/direct/payments/refund-payments/] 

Actually Refund is possible for Sale completed payment and capture payment. Let me know if you need any further clarification on refund.

Thanks,
Xavier Jijies
