### ISSUE TITLE
PaymentExecuteRequest Not Executing

### ISSUE THREAD

**Issue by chuksgpfr** [paypal/PayPal-NET-SDK#398]
This is my execution mwthod : 

`private async void ExecutePayment(string PayerId, string paymentId)
        {
        PaymentExecuteRequest request = new PaymentExecuteRequest(paymentId);
            request.RequestBody(new PaymentExecution()
            {
                PayerId = PayerId
            });
        }

It doesn't execute ...
help needed. .NET core 2.0`

**Comment by pspejman** [comment]
Hi, there is no any environment definition in your code, you have to define paypal client with (sandbox or production) environment and execute your request with it.

```c#
private async void ExecutePayment(string PayerId, string paymentId)
{
   PaymentExecuteRequest request = new PaymentExecuteRequest(paymentId);
   request.RequestBody(new PaymentExecution()
   {
      PayerId = PayerId
   });
   var response = await PayPalClient.Execute(request);
   var result = response.Result<Payment>();
}
```

**Comment by prakash-gangadharan** [comment]
Hi @chuksgpfr, to **Process PayPal Payments** / create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)

Let us know if you are facing any challenges.
