### ISSUE TITLE
Please make something with WebhookEvent

### ISSUE THREAD

**Issue by ivanromakh** [paypal/PayPal-NET-SDK#399]
paypal version sdk version 1.9.1
dotnet  version 4.0.3

code:
public JsonResult Index(WebhookEvent event)
{
// event.resource is empty
}

Please fix the resource it is empty object always but in inputStream it isn`t or make it dynamic. I used InputStream now becouse of this and make dynamic object and all works nice but would be better to get it as parameter.

data is from sandbox paypal api
![image](https://user-images.githubusercontent.com/18567511/50233250-b4e22d00-03bb-11e9-920c-6cdd5627570d.png)
I used inputStream here.
![image](https://user-images.githubusercontent.com/18567511/50233483-3639bf80-03bc-11e9-961c-80e54cd7ea25.png)

And get webhookEvent
![image](https://user-images.githubusercontent.com/18567511/50235467-9cc0dc80-03c0-11e9-9304-63cba79052a7.png)

Then I serialize and deserialize resource from dynamic to string and from string to Agreement Plan or what I need.
![image](https://user-images.githubusercontent.com/18567511/50235931-ca5a5580-03c1-11e9-81ad-50f0acfce14c.png)

Please fix WebhookEvent

**Comment by xjijies** [comment]
Hi @ivanromakh,
Do you need any help on this or shall I close this issue?

**Comment by ivanromakh** [comment]
@xjijies yep sure. This its too old.
