### ISSUE TITLE
AccessToken.createdDate is not updated after getting response from AccessTokenRequest

### ISSUE THREAD

**Issue by kaifeong** [paypal/PayPal-NET-SDK#402]
### General information

* SDK/Library version: 2.0-beta
* Environment: Sandbox
* Language, language version, and OS: Windows 10

### Issue description

PaypalHttpClient class under line 52 as below did not invoke AccessToken constructor which cause the createdDate variable not set to current date and is always minimum date. Which means the token always expired and each invocation / execute will request new token.
`this.accessToken = accessTokenResponse.Result<AccessToken>();`

**Comment by xjijies** [comment]
Hi @kaifeong ,
Do u need help on this or shall I close this issue?

**Comment by kaifeong** [comment]
> Hi @kaifeong ,
> Do u need help on this or shall I close this issue?

nope. just highlighting it but didnt expect nobody reply close to a year.
