### ISSUE TITLE
Validate Webhook Message

### ISSUE THREAD

**Issue by devmartins** [paypal/PayPal-NET-SDK#406]
* SDK/Library version: 2.0-rc2
* Environment: Production
* Language, language version, and OS: C#, .NetCore 2.1, Win10/Ubuntu 18.04

How can I validate a message with the new SDK?
I'm using C# with .Net Core 2.1.

**Comment by devmartins** [comment]
Is this repository abandoned ?
@jaypatel512 Can you give a little help ?

**Comment by jaypatel512** [comment]
Hey @devmartins !

Unfortunately I do not have access to these repositories anymore. 

However, you should be able to validate webhook as shown [here](https://github.com/paypal/PayPal-NET-SDK/wiki/Webhook-Event-Validation).

**Comment by devmartins** [comment]
This is for .Net Framework. I'm using .Net Core.
Is there other employee who can help?
Thanks.

**Comment by alextretij** [comment]
I have the same issue with validation webhook.

**Comment by Iuli1478** [comment]
I have issue with validation webhook too. 
This is my code:

`            var apiContext = _payPalHelper.GetApiContext();  
            string requestBody;
            using (var reader = new StreamReader(Request.Body))
            {
                requestBody = reader.ReadToEnd();
            }
            var webhookEvent = JsonConvert.DeserializeObject<WebhookEvent>(requestBody);
            var nameValueCollection = new NameValueCollection();
            foreach (var item in Request.Headers)
            {
                nameValueCollection.Add(item.Key, string.Join(",", item.Value));
            }
            var isValid = WebhookEvent.ValidateReceivedEvent(apiContext, nameValueCollection, requestBody, _payPalSettings.WebhookId);
`
I get this Exception:: 
PayPal.PayPalException: 'Unable to load trusted certificate.'
Inner exception:
NullReferenceException: Object reference not set to an instance of an object.

In Request.Headers (NameValueCollection) I have key "Paypal-Cert-Url": https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-5edc0ebc

I'm using .net core 2.1

**Comment by dsedleckas** [comment]
👍 Having this issue as well

**Comment by sucithrashanu** [comment]
@devmartins 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
