### ISSUE TITLE
Find out which payment method is being used

### ISSUE THREAD

**Issue by kkagill** [paypal/PayPal-NET-SDK#409]
### General information

* SDK/Library version: SDK 2.0.0-beta
* Environment: Both
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: c# aspnet core, windows 10

### Issue description

I'd like to find out whether customer used debit or credit, more specifically which credit card is used (visa, master, etc).

where can I retrieve that value?

checkout.js:

    paypal.Button.render({
        env: 'sandbox', // Or 'production',
        style: {
          size: 'medium',
          height: 48,
          color: 'silver',
          shape: 'rect',
          label: 'checkout',
          tagline: 'true',
          fundingicons: 'true',
          layout: 'horizontal'
      },        
     payment: function (data, actions) {
        // 2. Make a request to server
        return actions.request.post('/api/RewardsManagerAPI/create-payment/')
            .then(function (res) {
                ....
            }
          }

backend using PayPal SDK 2.0.0-beta:

    var payment = new Payment()
            {
                ExperienceProfileId = experienceProfileId,
                Intent = "sale",
                Payer = new Payer()
                {
                    PaymentMethod = ?,
                },

**Comment by MLyons10** [comment]
I'm not aware of a way to do this through the PayPal SDK, but you can do this pretty easily using a separate class like this:

        public static string GetCardType(string _CardNumber)
        {
            string CardTypeString = "Not Available";

            //Handle dashes and spaces in the card number
            string CardNumber = _CardNumber.Replace("-", "").Replace(" ", ""); ;
            string IINNumber = string.Empty;

            //
            if (CardNumber.Length > 6)
            {
                try
                {
                    IINNumber = CardNumber.Substring(0, 6);

                    if (IINNumber.Substring(0, 2) == "34")
                    {
                        CardTypeString = "Amex";
                    }
                    if (IINNumber.Substring(0, 2) == "36")
                    {
                        CardTypeString = "Diners Club";
                    }
                    if (IINNumber.Substring(0, 2) == "37")
                    {
                        CardTypeString = "Amex";
                    }
                    if (IINNumber.Substring(0, 2) == "38")
                    {
                        CardTypeString = "Diners Club";
                    }
                    if (IINNumber.Substring(0, 1) == "4")
                    {
                        CardTypeString = "Visa";
                    }
                    if (IINNumber.Substring(0, 2) == "51")
                    {
                        CardTypeString = "MasterCard";
                    }
                    if (IINNumber.Substring(0, 2) == "52")
                    {
                        CardTypeString = "MasterCard";
                    }
                    if (IINNumber.Substring(0, 2) == "53")
                    {
                        CardTypeString = "MasterCard";
                    }
                    if (IINNumber.Substring(0, 2) == "54")
                    {
                        CardTypeString = "MasterCard";
                    }
                    if (IINNumber.Substring(0, 2) == "55")
                    {
                        CardTypeString = "MasterCard";
                    }
                    if (IINNumber.Substring(0, 4) == "6011")
                    {
                        CardTypeString = "Discover";
                    }
                    if (IINNumber.Substring(0, 3) == "644")
                    {
                        CardTypeString = "Discover";
                    }
                    if (IINNumber.Substring(0, 2) == "65")
                    {
                        CardTypeString = "Discover";
                    }
                }
                catch
                {
                    CardTypeString = "Not Available";
                }
            }

            return CardTypeString;
        }

Hope that helps!

**Comment by sucithrashanu** [comment]
@kkagill  

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
