### ISSUE TITLE
Chain building status: FalseChain error: Revoked The certificate is revoked.

### ISSUE THREAD

**Issue by TomGullen** [paypal/PayPal-NET-SDK#411]
### General information

* SDK/Library version: 1.9.1
* Environment: Production
* Language, language version, and OS: Windows Server 2012 R2 Datacentre

### Issue description

Receiving the following errors on our webhook:

```
PayPal.PayPalException: Unable to verify the certificate(s) found at https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-8079afec
   at PayPal.CertificateManager.GetCertificatesFromUrl(String certUrl)
   at PayPal.Api.WebhookEvent.ValidateReceivedEvent(APIContext apiContext, NameValueCollection requestHeaders, String requestBody, String webhookId)
   at C3.Code.Helpers.Payments.Paypal.Webhooks.HandleWebhookRequest(HttpContext context, EventSender gaEventSender) in C:\Construct.net\Source\C3Alpha2\Code\Helpers\Payments\Paypal\Webhook.cs:line 144
   at C3.Handlers.Payments.BraintreeWebhook.ProcessRequest(HttpContext context) in C:\Construct.net\Source\C3Alpha2\Handlers\Payments\PaypalWebhook.ashx.cs:line 11
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Investigating the certificate at: https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-8079afec

The X509Chain throws the error:
`FalseChain error: Revoked The certificate is revoked.`

Which I believe to be why the exception is being thrown.  How do we fix this issue?

**Comment by TomGullen** [comment]
See here for solution:  
https://serverfault.com/questions/961681/revoked-ssl-certificate

**Comment by TomGullen** [comment]
Paypal - really need an explanation here.  This is your official SDK for .NET, and it appears there is problem with your SSL certificates which is causing failure.

**Comment by nicklmiller** [comment]
Agreed, this is a major issue.  The only workaround is to install the revoked cert on the server (not ideal...) or remove the call to ValidateReceivedEvent.  From what I can tell, the cert URL is being sent in the Webhook's request header, so I'm not sure anything in the actual SDK needs to be updated.  The URL being sent in the request header needs to be updated to a working cert.

**Comment by nathanschopf** [comment]
I'll chime in here as well to see if we can get some grease on this wheel. Our situation is exactly as @TomGullen's. Installing a revoked certificate as a temporary solution is entirely unacceptable for us. We continue to receive thousands of errors a day attempting to validate webhook messages. Removing the validation check is also an unacceptable option for us. Where are you at, PayPal?

**Comment by AAMajor** [comment]
I'll also support this. Exactly the same situation as above and we detected it a few days ago. I know you can ref a new cert via config but which cert would help us? We need to ref a PayPal one:
https://github.com/paypal/PayPal-NET-SDK/wiki/Webhook-Event-Validation

**Comment by nicklmiller** [comment]
I submitted a PayPal support ticket and here's their response:

> Unfortunately, the problem you're experiencing is being caused by some technical issues with the PayPal system. Our engineers are currently working diligently on a solution to this problem. I am going to assign this ticket to our internal engineering ticket so that when the problem is resolved, you will be notified of its completion right away.

**Comment by nicklmiller** [comment]
I've been told by PayPal support that the issue has been resolved.  I haven't checked to see for myself yet, though.

**Comment by TomGullen** [comment]
Anyone confirm if this is resolved?

**Comment by nicklmiller** [comment]
Yeah, they fixed it on their side.  No need to update the SDK.

**Comment by prakash-gangadharan** [comment]
Hi @TomGullen, is this still an issue?
