### ISSUE TITLE
Will this be deprecated sooner?

### ISSUE THREAD

**Issue by rananga** [paypal/PayPal-NET-SDK#414]
I'm going to integrate PayPal to our e-commerce platform using this SDK. Will this be deprecated? I tried the new PayPal Checkout SDK but it's not stable yet it seems, since I came up with some issue while trying to integrating it.

Please let me know your suggestions.

**Comment by prakash-gangadharan** [comment]
similar question asked here : https://github.com/paypal/PayPal-NET-SDK/issues/392
