### ISSUE TITLE
[SDK 2.0.0-rc2] POST ExecuteBillingAgreement Error 500

### ISSUE THREAD

**Issue by kanadaj** [paypal/PayPal-NET-SDK#418]
### General information

* SDK/Library version: .NET Core 2.2
* Environment: Sandbox
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: .NET Core 2.2, Windows 10 1903 and CentOS 7.6

### Issue description

When executing a CreateBillingAgreement request, the server returns a 500 error. After some trial and error, this seems to be related to the fact that the request body cannot be null

Setting the content type of the request like so seems to fix the issue:
```cs
if (request.Body != null)
    request.Content = this.Encoder.SerializeRequest((HttpRequest)request);
else request.Content = new StringContent("{}", Encoding.UTF8, "application/json");```

**Comment by sucithrashanu** [comment]
@kanadaj 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
