### ISSUE TITLE
Is  billing agreement deprecated as created billing here?

### ISSUE THREAD

**Issue by CSEALAMIN** [paypal/PayPal-NET-SDK#419]
I beg pardon if i am at wrong site.
I have noticed that when agreement create like here it calls 
/v1/payments/billing-agreements.

in api docs I found 

"Deprecation notice: The /v1/billing-agreements endpoints are deprecated. Use the /v1/billing/subscriptions endpoints instead."

how can I use /v1/billing/subscription instead of /v1/billing-agreements since I am not manually
calling API

**Comment by r24mille** [comment]
I do not work for PayPal, but you may have more luck here, if it's a general API question: https://github.com/paypal/PayPal-REST-API-issues

**Comment by prakash-gangadharan** [comment]
Hi @CSEALAMIN, this PayPal-NET-SDK still using below `Billing Plans API` which is  deprecated.
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one in sdk but it may be available in near future.

**Comment by xjijies** [comment]
@CSEALAMIN  Hi,
Refer this link: https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions
https://github.com/paypal/PayPal-NET-SDK/wiki/Quick-Start

If you need any further I would help.
