### ISSUE TITLE
How to send 3DS Values

### ISSUE THREAD

**Issue by kleviFoodchain** [paypal/PayPal-NET-SDK#420]
### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox

### Issue description

In order to be compliant with PSD2 requirement, I have implemented Cardinal Cruise on our site that is already using PayPal-NET-SDK. 

In order for PayPal to validate that I have authenticated with Cardinal, I need to pass the following 3DS values to PayPal:
Cavv, Eci3ds, Xid

Is this possible with PayPal-NET_SDK?

I appreciate any help, Thank You

**Comment by RJN368** [comment]
Any update on this, the deadline for 3DS s looming and it looks like we can no longer use the SDK?

**Comment by sucithrashanu** [comment]
@kleviFoodchain 

HI
Please refer the below link for merchant technical support. 
[https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723](url)

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!

**Comment by RJN368** [comment]
> > Any update on this, the deadline for 3DS s looming and it looks like we can no longer use the SDK?
> 
> I called PayPal support, looks like the SDK will never have 3DS support. We are switching to Braintree because of this.

Thanks for the link, however we have now both talked to PayPal technical support and had the same response.  The SDK will not support 3DS which is pretty strange.
