### ISSUE TITLE
Obtaining a ClientToken

### ISSUE THREAD

**Issue by robnorthen** [paypal/PayPal-NET-SDK#421]
### General information

* SDK/Library version: 2.0.0-rc2
* Environment: .Net Core
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

I'm following the instructions in  the _PayPal Complete Payments Integration Guide_ and have successfully managed to obtain an Access Token, using the AccessTokenRequest class, however I am unable to obtain a ClientToken, as there is no ClientTokenRequest class provided.

Please can you provide a sample of how to create the ClientToken required for the js api for Complete Payments integration.

Thank you.

**Comment by sucithrashanu** [comment]
@robnorthen 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
