### ISSUE TITLE
BaseSamplePage unknown

### ISSUE THREAD

**Issue by vinceweeks** [paypal/PayPal-NET-SDK#424]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Your sample code won't compile

**Comment by prakash-gangadharan** [comment]
@vinceweeks can you be specific about which sample code doesn't get compiled?

**Comment by vinceweeks** [comment]
HI Prakash – I was trying to implement your service for a Xamarin project I’m working on. I tried to implement your example code without success. I’ve decided to go with a different processor. Thanks.

**Comment by prakash-gangadharan** [comment]
@vinceweeks , do you have the code snippet where you experiencing error,  i.e  example code in which you ended up with unsuccessful compilation..

**Comment by prakash-gangadharan** [comment]
Closing this issue, please revert us back if you still facing any challenge.
