### ISSUE TITLE
Get error information for "Account does not have enough money" when doing a payment in C#

### ISSUE THREAD

**Issue by vandat07** [paypal/PayPal-NET-SDK#426]
Hello,

I would like to record the error when executing a payment for the errors code in this page: https://developer.paypal.com/docs/api/payments/v2/#errors

Thanks a lot

**Comment by prakash-gangadharan** [comment]
Hi @vandat07,  still you getting this issue?

**Comment by prakash-gangadharan** [comment]
please revert us back if this is still an issue.
