### ISSUE TITLE
Wish to update the sample for the latest source code. :)

### ISSUE THREAD

**Issue by shandye2** [paypal/PayPal-NET-SDK#427]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by Trupti21** [comment]
@shandye2 ,

- If you find solution to an [issue/improvements](https://github.com/paypal/PayPal-NET-SDK/issues) sdk that would be helpful to everyone, feel free to send us a pull request.

- The ideal approach to create a fix would be to fork the repository, create a branch in your repository, and make a pull request out of it.

- It is desirable if there is enough comments/documentation and Tests included in the pull request.

- For general idea of contribution, please follow the guidelines mentioned [here](https://github.com/paypal/PayPal-NET-SDK/wiki/Contributing-to-the-SDK).

Thanks
