### ISSUE TITLE
Any update on this, the deadline for 3DS s looming and it looks like we can no longer use the SDK?

### ISSUE THREAD

**Issue by Juz05050505** [paypal/PayPal-NET-SDK#430]
Any update on this, the deadline for 3DS s looming and it looks like we can no longer use the SDK?

_Originally posted by @RJN368 in https://github.com/paypal/PayPal-NET-SDK/issues/420#issuecomment-524251236_

**Comment by sucithrashanu** [comment]
@Juz05050505  

HI
Please refer the below link for merchant technical support. 
[https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723](url)

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
