### ISSUE TITLE
Billing Address Null

### ISSUE THREAD

**Issue by dakar2008** [paypal/PayPal-NET-SDK#431]
### General information

* SDK/Library version: Latest 1.9.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: C# - MVC 5.2.7.0 - MS Windows 10

### Issue description

After recieving response from PayPal, i use

`var thispayment = Payment.Get(apiContext, paymentId);`
`Payer thispayer = thispayment.payer;`
`PayerInfo thispayerinfo = thispayer.payer_info;`

But `thispayerinfo.billing_address` is always `null`, how do i retrieve the billing address, if the customer has entered both a billing address and a shipping address.

Because it's not a problem to get the billing address if the customer is not entering a seperate shipping address, but if they do, i only have the shipping address, i need the billing information for my invoice, i don't like to use PayPal's invoice so i created my own system.

Anynone has any idea how to get these informations.

**Comment by prakash-gangadharan** [comment]
Hi @dakar2008, can you help us with the `PayPal-Debug-ID`

**Comment by dakar2008** [comment]
Thanks for responding to my issue, but it has been solved now, it's turned out that the billing address is null because PayPal has disabled it by default on all accounts, but if you make contact to PayPal through the developer page, they can enable it for you, and i have just done that and now it's not null anymore, now i can see the billing address of the customer.

Hope this helps others that have the same issue.
