### ISSUE TITLE
"CREDIT CARD REFUSED" and "INSTRUMENT DECLINED" errors

### ISSUE THREAD

**Issue by tjhackzy** [paypal/PayPal-NET-SDK#432]
We use PayPal Pro within our production system (website : https://comodosslstore.com/) and we are having "Credit Card Refused" error for the following debug IDs. Could you please check what exactly went wrong with these transactions? 

### General information

* Environment: Production
* `PayPal-Debug-ID` values: b4b1b080dbe62 , 2bf5aace86627, 673b656f4671, ae87aca0f91e2, 5a650ec3fec5
* Language, language version, and OS: c#

### Issue description
Since last 1-2 weeks these errors are continuously coming from paypal for our prod account. Could you please check?

Here are the invoice number : 

COR83063880N3518011 (debug id : 2bf5aace86627)
COR83065417N3543359 (debug id:  ae87aca0f91e2)
COR83063947M3519289(debug id:  b4b1b080dbe62)

Other Debug IDs : 
673b656f4671, 
 5a650ec3fec5

Please provide support in above cases. Thank you. 

Regards, 
https://comodosslstore.com/

**Comment by xjijies** [comment]
Hi @tjhackzy ,

We analyzed above debug ID's and all are externally declined by the card processor.

**Comment by xjijies** [comment]
@tjhackzy I close this issue now. If you need any further help,please re-open this.

**Comment by tjhackzy** [comment]
Hi @xjijies  

We have a few more "Error while processing transaction. CREDIT_CARD_REFUSED" Errors from our customers. 

The debug IDs are: 

Invoice_number: COR83069032M3606993 (8d87c50f98e4e)
Invoice_number: COR83069032M3606623 (78376bf9c4620)
Invoice_number: COR83069031M3604310 (46c89246eaa1b , 5ec5f16e4081b, b85a029bf67b3, 495c7c2164b1f, db2d311642603)


Can you please recheck for the above error on why exactly the CREDIT cards were refused? 


regards,
https://comodosslstore.com/
