### ISSUE TITLE
Plan details missing from Agreement order summary page

### ISSUE THREAD

**Issue by amunns** [paypal/PayPal-NET-SDK#54]
Everything seems to work in the above example, up until the redirecturl is followed, when arriving at the PayPal site, none of the agreement financial details are displayed, just the following:

Your order summary
Description
Agreement for T-Shirt of the Month Club

Once the transaction has been completed, which seems to run smoothly, a bad request 400 error is returned. Any ideas?

**Comment by jaypatel512** [comment]
Closing this issue, as we can use the https://github.com/paypal/PayPal-PHP-SDK/issues/149 for tracking this feature's progress.
