### ISSUE TITLE
How can we Receive Money using this IBAN ? Not mentioned any where else. 

### ISSUE THREAD

**Issue by aAmitSengar** [paypal/PayPal-NET-SDK#58]
Actually this is not an issue but i'm tired but still didn't find any solution please help me

**Comment by burrm** [comment]
I was looking at this too, I'd like to be able to provide the ability for customers to pay by e-check. Based on the API documentation, payer has to be a credit_card or paypal.

https://developer.paypal.com/docs/api/#payer-object

Looking at the FundingInstrument class, there are at least the bindings to support bank payments:

/// <summary>
        /// Bank Account information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "bank_account")]
        public ExtendedBankAccount bank_account { get; set; }

        /// <summary>
        /// Bank Account information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "bank_account_token")]
        public BankToken bank_account_token { get; set; }


Thoughts on how to execute one of these sales?

**Comment by jziaja** [comment]
Thanks for pointing that out, @burrm!  I'll check with the API team to see what the correct call should be and circle back when I have an answer.

**Comment by jziaja** [comment]
@burrm, unfortunately, the ability to pay be e-check isn't supported at this time.  Currently, only `credit_card` and `paypal` are supported as payment methods in the REST API.  The API team did say that they plan to enable other payment methods in the future but had no ETA on when that might happen.

The reason these other funding instrument properties made it into this codebase (and the other SDK codebases) is the schema files given to the SDK team by the various API teams are also used elsewhere for other services.  In this case, there is another service not related to the REST APIs that is consuming this schema and supports these other funding instruments.  We've raised this issue with the API teams and a plan is in place to better flag properties like these to avoid exposing them in the wrong area, which is what happened here.

The SDK team is currently working on identifying what other properties in the SDK might also be affected and to possibly deprecate/obsolete those properties in upcoming releases so as not to confuse developers.

**Comment by jziaja** [comment]
The [`FundingInstrument`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/FundingInstrument.cs#L42) properties that are currently not supported have been flagged in the latest release with attributes so they don't appear in the Intellisense list or a Properties grid.  I held off from marking them with an `Obsolete` attribute since there's a chance they could be supported in the future.  I've also included notes on each of the unsupported properties that explicitly say they are unsupported.  If I find out later that the properties will never be supported, then I'll update them with the `Obsolete` attribute.

Sorry for the confusion on this.

**Comment by burrm** [comment]
Thanks, I appreciate it. Are the changes available in the latest NuGet package?

**Comment by jziaja** [comment]
Yup!  [Version 1.3](https://www.nuget.org/packages/PayPal/1.3.0) contains the changes and was just published.  [Direct downloads](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.3.0) are also available here on GitHub.
