### ISSUE TITLE
Question: allow_note

### ISSUE THREAD

**Issue by EdSF** [paypal/PayPal-NET-SDK#63]
While one can toggle the ability for a user to [`allow_note`](https://developer.paypal.com/docs/api/#inputfields-object) in a `web_profile` there doesn't seem to be a way to get this data (the note) back from any response in a "normal" payment flow (or "extra" call that I've tried so far - e.g.`Payment.Get`.). Is there a way to do so?

Unsure if this is the right forum for such, if not, just let me know, I'll remove it.

**Comment by jziaja** [comment]
Great question, @EdSF, and yes, this is definitely the place to ask these types of questions. :)  [StackOverflow](http://stackoverflow.com/) is another good place, but asking here allows for us (the PayPal SDK team) to see the question immediately and forward it to the appropriate API team if necessary.

I tried testing this out, and the only place I could find the note is in the email that gets sent to the merchant informing them of the payment completion (in this test I added a note saying _"Thanks for the stuff!"_ when I approved the payment using my test PayPal account):

![image](https://cloud.githubusercontent.com/assets/8227966/5629879/edb285f4-957d-11e4-9cd3-b6cd87f5a800.png)

I'll forward this question to the Experience API team to see if there's any other way to retrieve the included note and circle back here once I have more information.

**Comment by jziaja** [comment]
Also, while testing this scenario I realized the sample project doesn't have a sample that uses an experience profile when making a payment with PayPal.  I'm going to add a new sample that creates a new experience profile along with making a payment with PayPal so developers have an easier time seeing this flow in action.  I'll also include a note in the sample that tells developers where they can find the buyer's note to the merchant.

**Comment by EdSF** [comment]
Awesome @jziaja :+1:  Thanks!

**Comment by jziaja** [comment]
**Update:** According to the API team, the note to seller field cannot be retrieved via a REST call, and there's no immediate plans to add that support.

Also, the note to seller field is only available in the older PayPal payment experience, and is not available in the newer payment experience.  Unfortunately, there's nothing the caller can do at this time to force an old or new experience.
