### ISSUE TITLE
Seamless checkout using REST API 

### ISSUE THREAD

**Issue by moatazelgamal** [paypal/PayPal-NET-SDK#64]
Hi there :) 

I am using the paypal REST API for a project and I need to use paypal seamless-checkout. The docs on the link below suggest that REST API support for seamless-checkout is coming soon. What is the time-frame expected?
https://developer.paypal.com/docs/integration/direct/identity/seamless-checkout/

My use case is as follows: 
User authenticates to my website using Paypal login. User browse the cart. User makes a purchase using paypal without the need to login again to paypal. (I do not want the user to login again to paypal to complete the purchase) . My understanding is that seamless checkout is the way to go. Please correct me if I am wrong. 

Thanks, 
Moataz

**Comment by jziaja** [comment]
Hi @moatazelgamal, great question!  I'm checking on the status of that feature with the teams and will get back to you here when I have an answer.

**Comment by jziaja** [comment]
Unfortunately, there's no ETA at this time for when seamless checkout will be supported by the REST API.
