### ISSUE TITLE
Account reporting features

### ISSUE THREAD

**Issue by MECLab** [paypal/PayPal-NET-SDK#65]
Hi @jziaja,

I've been looking into migrating from the Classic API to the RESTful API. There are 3 main API operations that we use - **GetBalance**, **TransactionSearch** and **GetTransactionDetails**.

Sifting through the RESTful API documentation, I don't see equivalent operations. Do you know if these exist?

Thanks
Keagan

**Comment by jziaja** [comment]
Heya @MECLab!  `GetBalance` isn't available yet in the REST API; I'll follow up with the API team to see where that is on the roadmap and get back to you.  

`TransactionSearch` and `GetTransactionDetails` can be accomplished by first calling [`Payment.List`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/Payment.cs#L215) with search criteria specified (which is a little more limited [in REST](https://developer.paypal.com/docs/api/#paging--filtering) than Classic, currently).  This call returns a [`PaymentHistory`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/PaymentHistory.cs) object containing the list of payments that match the search criteria.  Each payment object in the list includes a [list of transactions](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/Payment.cs#L43) associated with the payment.

**Example:**
````c#
var paymentHistory = Payment.List(apiContext,  /* search criteria */);
foreach(var payment in paymentHistory.payments)
{
  if(/* do any other payment filtering here that couldn't be accomplished via the above search criteria */)
  {
    foreach(var transaction in payment.transactions)
    {
      // At this point you have all the details to the specific transaction for the given payment
    }
  }
}
````

**Comment by jziaja** [comment]
Sorry for the delay on this!  At this time, there's no plan on supporting the `GetBalance` operation with the REST API.
