### ISSUE TITLE
How to get Buyer/Payer Name using Adaptive Payment

### ISSUE THREAD

**Issue by HoneyShyam** [paypal/PayPal-NET-SDK#66]
Hi Dear,
Is there any way/method to get Buyer when do a Chained Payment using Adaptive Payment.
Any help will be great.
Thanks in advance.
Regards
Shyam

**Comment by jziaja** [comment]
Hi @HoneyShyam, this repository is for the PayPal .NET SDK, which is built on PayPal's REST APIs.  The [PayPal Adaptive Payments Classic SDK for .NET](https://github.com/paypal/adaptivepayments-sdk-dotnet) is in a different repository.  Please resubmit your issue in that repository.

**Comment by HoneyShyam** [comment]
Thanks @jziaja
