### ISSUE TITLE
.NET SDK seems to be missing the equivalent of "&useraction=commit"?

### ISSUE THREAD

**Issue by Jaans** [paypal/PayPal-NET-SDK#68]
Hi all
Thanks for a great SDK - practical to work with! 

I cannot seem to find the equivalent in the SDK for making the payment immediate on the PayPal site, which traditionally was done with the 'useraction' parameter and the 'commit' value for it.

Normally that 'commit' value would have the PayPal page show **"Pay Now"** instead of "Continue - You will confirm your payment on XXXXXX". So that is what I'm after with the SDK, please add functionality if it does not exist.
Thanks

**Comment by Jaans** [comment]
Related to the above, would I still need to "Execute" the payment upon returning from the PayPal site if the above "Pay Now" scenario were enabled?

**Comment by jziaja** [comment]
Hi @Jaans, glad to hear you're enjoying the SDK, and great question!  The **Pay Now** feature does look to still be available (and can be taken advantage of by appending `&useraction=commit` to the `approval_url` HATEOAS link of the created **Payment** resource).  However, in testing this, I'm noticing that the **Payment** resource is still marked with `state="created"` and includes an `execute` HATEOAS link.  Also, I'm not seeing the transaction appear on the Dashboard.  Ideally, you should not need to execute a payment made with the **Pay Now** feature as that should perform the execution automatically.

I'm following up with the Payments team to see if **Pay Now** is supported with REST payments and will get back to you here once I have more information.

**Comment by Jaans** [comment]
Thanks for the feedback. 
I'm happy to still issue a  "Execute" call upon returning from PayPal using the "**Pay Now**" scenario, I just wasn't sure whether I should, or whether it is still the intent from an RestAPI point of view. I'll await your feedback.

FYI: We have a pending deployment with PayPal UK in the next few weeks, so it would be great if we could have this working by then :wink:

**Comment by jziaja** [comment]
@Jaans , I heard back from the payments team, and apparently I misunderstood how the **Pay Now** feature works.

Using Classic or REST, redirecting a buyer to PayPal with `useraction=commit` is intended as a way of alerting the user that when they click the "Pay Now" button, the payment can be processed by the merchant immediately.  The merchant will still need to call `Execute` (or `GetExpressCheckoutDetails` and `DoExpressCheckoutPayment` using Classic) after PayPal redirects back to the merchant site after the buyer clicks the button.  This information (while not spelled out exactly in this manner) can be found in the [Classic Express Checkout documentation for customizing the checkout experience](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECCustomizing/) (it's at the very bottom of the page).

Sorry for the confusion earlier and hope this clears things up. :)  

I'm currently discussing with the other SDK team members to see if we can add a helper method to each of the SDKs that takes an `approval_url` and appends parameters like this to it to get the customized checkout experience.  I'll leave this issue open for time being as an enhancement request and close it once the helper method has been added.

Also, I'm going to notify the documentation team to see if we can add some extra documentation somewhere that explains how **Pay Now** can be used in context of REST payments.

**Comment by Jaans** [comment]
Thanks for the prompt follow-up, and also the related contextual information. 

Our PayPal UK contact confirmed the same with regards to executing the transaction. 

I agree, it would be better for the SDK to handle the relevant `approval_url` manipulation for **Pay Now** support, rather than relying on end-user manipulation thereof. 

I'm happy to do that (manipulate the`approval_url`) in the interim though, and when explicitly handled by the SDK, to then use that. Please post back to this issue if that does indeed get added to the SDK.

Thanks again for some very good support!

**Comment by jziaja** [comment]
Hi @Jaans, I've published the 1.3 release ([GitHub direct download](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.3.0) | [NuGet](https://www.nuget.org/packages/PayPal/1.3.0)) that includes helper methods for accessing the HATEOAS links for any resource object that might have them.  For a Payment resource object, you can call `payment.GetApprovalUrl(true)` to get the URL for the `approval_url` HATEOAS link and auto-append the `&useraction=commit` parameters so you get the **Pay Now** checkout experience.  If we ever need to add support for more parameters on this link, this will be an easy and quick place we can add that support.

Thanks again for bringing this to our attention! :+1:

**Comment by Jaans** [comment]
Brilliant! That works very well indeed. Thank you for the quick turnaround and support.
