### ISSUE TITLE
Send to shopping cart paypal

### ISSUE THREAD

**Issue by darkducke** [paypal/PayPal-NET-SDK#69]
I am starting now, and I'm a little lost, I want to send the shopping cart, the application for the user to complete the payment in paypal page, which example of the demo should I use? Payment would be ()? or Invoice ()?

Thank U!

**Comment by jziaja** [comment]
Hi @darkducke!  If you need to send a bill to a customer regarding a payment for items, then you'll want to create an Invoice to send to the customer.  However, if you just need a way for your customers to purchase items immediately from their shopping cart, then creating a Payment is what you want.

I'd suggest taking a look at the [**Make a payment with PayPal** sample](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/PaymentWithPayPal.aspx.cs) in the [Samples](https://github.com/paypal/PayPal-NET-SDK/tree/master/Samples) project.  Using the information from your shopping cart, you'll want to construct a [Payment](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/Payment.cs) object and include all the information from the cart.  Once created, you'll follow the flow described [here](https://developer.paypal.com/docs/integration/web/accept-paypal-payment/) for creating a sale.  If your shopping cart contains items the customer is ordering and you don't want to capture the payment immediately, then you'll want to follow the flow described [here](https://developer.paypal.com/docs/integration/direct/create-process-order/) for creating an order.

**Comment by darkducke** [comment]
Thank you for your help!
