### ISSUE TITLE
Delivery details not passed through to paypal

### ISSUE THREAD

**Issue by halimakoundi** [paypal/PayPal-NET-SDK#71]
Hi ,
I have an issue with the direct payment with VISA cards, I do set up billing and delivery info for the payer and it does not seem to make it through to the paypal live account 

My code to set up the payment 

````vb
Dim shippingInfo As New PayPal.Api.ShippingAddress()
shippingInfo.city = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line4
shippingInfo.country_code = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Country.Code
shippingInfo.line1 = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line1
shippingInfo.postal_code = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.PostCode
If Not String.IsNullOrEmpty(GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line2) Then
    shippingInfo.line2 = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line2
End If
If Not String.IsNullOrEmpty(GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line3) Then
    shippingInfo.state = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line3
End If

Dim payerInfo As New PayPal.Api.PayerInfo()
payerInfo.billing_address = billingInfo
payerInfo.shipping_address = shippingInfo
payerInfo.email = GlobalRegistry.OrderInProgress.Customer.Email
credtCard.billing_address = billingInfo

Dim fundInstrument As New PayPal.Api.FundingInstrument()
fundInstrument.credit_card = credtCard
                
Dim fundingInstrumentList As New List(Of PayPal.Api.FundingInstrument)()
fundingInstrumentList.Add(fundInstrument)

Dim payr As New PayPal.Api.Payer()
payr.funding_instruments = fundingInstrumentList
payr.payment_method = "credit_card"
payr.payer_info = payerInfo
````

etc..

On the Website Payments Pro transaction view it says 

![image](https://cloud.githubusercontent.com/assets/5450688/5917761/bc3d111e-a618-11e4-8381-6a9b50309114.png)

Am i setting the shipping info the right way ?

Thanks for your help.

**Comment by halimakoundi** [comment]
For Payment with Maestro i am using the Merchant sdk 

 Dim shippingInfo As New PayPal.PayPalAPIInterfaceService.Model.AddressType()
        shippingInfo.Name = payer.FirstName
        shippingInfo.CityName = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line4
        shippingInfo.Country = DirectCast([Enum].Parse(GetType(CountryCodeType), GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Country.Code), CountryCodeType)
        shippingInfo.Street1 = DirectCast([Enum].Parse(GetType(CountryCodeType), GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Country.Code), CountryCodeType)
        If Not String.IsNullOrEmpty(GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line2) Then
            shippingInfo.Street2 = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line2
        End If
        If Not String.IsNullOrEmpty(GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line3) Then
            shippingInfo.StateOrProvince = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.Line3
        End If
        shippingInfo.PostalCode = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedDeliveryAddress.PostCode

Dim PaymentDetails As New PaymentDetailsType()
        PaymentDetails.ShipToAddress = shippingInfo

And billing info 

Dim billingInfo As New PayPal.PayPalAPIInterfaceService.Model.AddressType()
        billingInfo.CityName = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedBillingAddress.Line4
        billingInfo.Country = DirectCast([Enum].Parse(GetType(CountryCodeType), GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedBillingAddress.Country.Code), CountryCodeType)
        billingInfo.Street1 = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedBillingAddress.Line1
        billingInfo.PostalCode = GlobalRegistry.OrderInProgress.Customer.Addresses.GetSelectedBillingAddress.PostCode

Dim payerInfo As New PayerInfoType()
        payerInfo.Address = billingInfo
        payerInfo.PayerName = payer

**Comment by jziaja** [comment]
Hi @halimakoundi, the correct place to put the shipping address information is in the `item_list.shipping_address` property for the `transaction`.  The documentation is a little confusing, but the `payer_info` is actually only used to pre-fill fields on the PayPal site if you do a direct payment using PayPal.  `payer_info` is effectively ignored if you do a direct payment using a credit card since there's no fields to pre-fill.

Here's some sample code (in C#, but can be easily converted to VB) along with a screenshot of the transaction details in my sandbox account:

````csharp
var payment = new Payment
{
    intent = "sale",
    payer = new Payer { /* credit card payer details... */ }
    transactions = new List<Transaction>
    {
        new Transaction
        {
            amount = new Amount { /* amount info... */ },
            description = "This is the payment transaction description.",
            item_list = new ItemList
            {
                items = new List<Item> { /* item details... */ },
                shipping_address = new ShippingAddress
                {
                    city = "Johnstown",
                    country_code = "US",
                    line1 = "52 N Main ST",
                    postal_code = "43210",
                    state = "OH",
                    recipient_name = "Joe Buyer"
                }
            }
        }
    }
};
````

![image](https://cloud.githubusercontent.com/assets/8227966/5922913/f8e1e382-a614-11e4-962a-b954b35419ca.png)

I'll be following up with the documentation team to see if we can make this clearer in the docs.  Also, I'm going to update the sample project with a direct credit card payment sample that defines the shipping address to make it easier to test this use case out in the future.

**Comment by jziaja** [comment]
Updated my previous comment as I was incorrect on how the `payer_info` object is being used.  However, that just adds to the fact that using that object is currently very confusing...  I've notified the docs team concerning this and we will be working with the Payments API team to get this documentation updated as well as raise the following API bug & issue that were discovered:

* Payment resources for credit card payments aren't returning a `payer_info` object if one is initially provided
* Setting the shipping address for a credit card payment is not intuitive - it should be a child property of a `transaction` object and not a transaction's `item_list` object

**Comment by halimakoundi** [comment]
Hi Thanks you,
I am switching to the classic API for now for all payments.

Thanks for your explanation.
