### ISSUE TITLE
Seamless Checkout : IDENTITYACCESSTOKEN 

### ISSUE THREAD

**Issue by prparamasivam** [paypal/PayPal-NET-SDK#73]
Hi,
I am trying to integrate PayPal seamless checkout. I'm using .NET PayPalMerchantSDK for SetExpressCheckout API call.The documentation here https://developer.paypal.com/docs/integration/direct/identity/seamless-checkout/ states that I should be passing in an IDENTITYACCESSTOKEN parameter. However, this doesn't seem to be available in the sdk. Could you please guide on how to integrate?

**Comment by jziaja** [comment]
Hi @prparamasivam, would you mind moving this issue over to the [PayPal Classic Merchant SDK for .NET](https://github.com/paypal/merchant-sdk-dotnet) repository?  This repository is for the PayPal .NET SDK, which uses PayPal's REST APIs.  Thanks!
