### ISSUE TITLE
Documentation issue with NuGet package

### ISSUE THREAD

**Issue by martinsteel** [paypal/PayPal-NET-SDK#77]
The PayPal developer site (https://developer.paypal.com/docs/api/) uses the wrong package name in the instructions to install with NuGet.

Instructions say ```nuget install PayPalRestApiSDK -version 0.5.0``` however there isn't a package called ```PayPalRestApiSDK```. I suspect they mean ```RestApiSDK``` although wouldn't it make more sense to suggest this package for new users?

Apologies if this is the wrong place to report this but the developer site doesn't seem to have any section for documentation feedback.

**Comment by jziaja** [comment]
Thanks for reporting this @martinsteel!  And yes, this is definitely the right place to report this. :)  The documentation team is currently working on revamping that site, and they'll soon be removing the language buttons.  Along with removing those buttons, we'll be working on a newer documentation solution that gives the SDK team better control over the content that goes on the docs site.

I'll forward this feedback to them and get a status update on when we can expect that information to be removed.

**Comment by jziaja** [comment]
Documentation has been updated:

![image](https://cloud.githubusercontent.com/assets/8227966/6229872/87214108-b680-11e4-945b-2b7211aacea7.png)
