### ISSUE TITLE
INTERNAL_ERROR when retrieving payout status

### ISSUE THREAD

**Issue by abhishek4official** [paypal/PayPal-NET-SDK#80]
````json
{
  "name": "INTERNAL_ERROR",
  "message": "An internal service error has occurred.",
  "debug_id": "4fad24b5e3c63",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_ERROR"
}
````

while getting the pay out status with batch ID

**Comment by jziaja** [comment]
Hi @abhishek4official, is this issue happening consistently?

**Comment by jziaja** [comment]
I've been able to consistently reproduce this issue using an invalid batch payout ID:

![image](https://cloud.githubusercontent.com/assets/8227966/6373412/1f5a9ffa-bcd0-11e4-90f8-9269941bca7e.png)

@abhishek4official , is the batch payout ID you're using one that was created recently?  The Payouts service on sandbox was recently restarted, and there's a chance that some older batch payout IDs may have been removed during the restart.

**Comment by abhishek4official** [comment]
@jziaja Yes Payout ID was Created recently.

Well Thanks for response
