### ISSUE TITLE
Pre fill is not working when creating a payment

### ISSUE THREAD

**Issue by tony0121** [paypal/PayPal-NET-SDK#83]
Is there any way can pre fill the 'email address' when using guest checkout? I've tried to use 'shipping_address' object to pre fill the 'name' and 'phone' on guest checkout page, but I can not find a way to send para 'email'. 
'payer_info' object includes 'email', but it seems not work when setting 'paypal' to 'payment_method'. 
I'm looking forward to hearing you about the method how to pre fill the 'email address' on guest checkout page. Thanks.

**Comment by jziaja** [comment]
Hi @tony0121, please see [this issue](https://github.com/paypal/PayPal-PHP-SDK/issues/161) previously posted on the PHP SDK.

In short, prefilling the email address is not currently supported as it's not a required field for making the payment.
