### ISSUE TITLE
Retrieve payout details - Always status is denied

### ISSUE THREAD

**Issue by abhishek4official** [paypal/PayPal-NET-SDK#84]
![capture](https://cloud.githubusercontent.com/assets/5192884/6439314/9a207360-c0f7-11e4-83ea-af1b854a0b5f.PNG)

**Comment by jziaja** [comment]
Hi @abhishek4official , is this being done with a sandbox or live account?  Does the currency being used with the payout match the countries and currencies setup by the accounts the payout is attempting to send money to ([see PHP SDK Issue #220](https://github.com/paypal/PayPal-PHP-SDK/issues/220#issuecomment-71167657))?

**Comment by abhishek4official** [comment]
It is on live Account

**Comment by jziaja** [comment]
To verify you have Payouts (formerly known as Mass Payment) enabled for your REST application, you will need to perform the following steps:
  1. Login to your [developer dashboard on PayPal Developer](https://developer.paypal.com/webapps/developer/applications/myapps)
  2. In the **My REST apps** section, click your REST application to view its details
  3. At the bottom of the details page, find the **APP CAPABILITIES** section and verify **Payouts** is checked

**Comment by abhishek4official** [comment]
it is Already Checked

![capture](https://cloud.githubusercontent.com/assets/5192884/6569963/f39c113e-c718-11e4-9602-2d9ba44ef172.PNG)

**Comment by jziaja** [comment]
Sorry for the delay, the `DENIED` status is being returned because the PayPal account you're using is registered in India, which has a zero-balance requirement for PayPal accounts.  Payouts requires a balance in the account to use when transferring money and, unfortunately, is not supported in areas that have a zero-balance requirement.
