### ISSUE TITLE
Why is there no "mass pay" sample?

### ISSUE THREAD

**Issue by gidmeister** [paypal/PayPal-NET-SDK#86]
I can't see any of the samples that does a "mass pay" to several people from a dot-net website, whether using REST or any other method.  Does this mean that "mass pay" is not supported?
Thanks.

**Comment by jziaja** [comment]
Hi @gidmeister , Mass Pay was renamed to [**Payouts**](https://developer.paypal.com/docs/integration/direct/payouts-overview/) in the [PayPal REST API](https://developer.paypal.com/docs/api/#payouts).  The [samples project](https://github.com/paypal/PayPal-NET-SDK/tree/master/Samples) includes samples for each of the Payout operations:

![image](https://cloud.githubusercontent.com/assets/8227966/7008027/a3cc0604-dc54-11e4-920f-6044c3adb7eb.png)

If you find a sample that's missing or needs further clarification, please feel free to open an issue with the feedback. Thanks!
