### ISSUE TITLE
Better documentation needed for samples

### ISSUE THREAD

**Issue by gidmeister** [paypal/PayPal-NET-SDK#90]
Like many github projects, there is no documentation here.  If you give samples, have a readme that explains what each sample does!  If you give functions, don't just explain the arguments, say what the functions do!
And, have a task-based list: for instance: "how to make a payment from your website to a particular person" or "how to make a mass-pay to many persons from your web-site."
-- Gidmeister

**Comment by juwlee** [comment]
@gidmeister I am not sure if you are looking for particular docs, but have you looked at [README](https://github.com/paypal/PayPal-NET-SDK/blob/master/README.md) or [wiki](https://github.com/paypal/PayPal-NET-SDK/wiki)?

Regarding method description, most methods have [this kind of doc](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/BillingPlanCreate.aspx.cs#L26) right before its declaration unless they are straight-forward like RunSample(). They also have links to [PayPal developer docs](https://developer.paypal.com/webapps/developer/docs/api/) [sample](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/BillingPlanCreate.aspx.cs#L22) that has more explanation on APIs such as their input fields, behavior.

As for the details on functionalities, the aforementioned website, [PayPal developer docs](https://developer.paypal.com/webapps/developer/docs/api/), may help.

**Comment by jziaja** [comment]
@gidmeister:

> Like many github projects, there is no documentation here.

This statement is patently false, as @juwlee pointed out.  There is documentation in this repository; just not the specific documentation you may be wanting.  

> If you give samples, have a readme that explains what each sample does! If you give functions, don't just explain the arguments, say what the functions do!

This is already available when running the samples.  When you run the sample project, each sample item has a `Source` link that provides a view of the source code along with an explanation of what each call or object means.  However, our intention with the SDK is **not** to provide a level of detail on the arguments being used that rivals what is already available on PayPal Developer.  This is why we link back to PayPal Developer numerous times, both in the readme and in the samples.

Granted, not all the documentation is perfect in the samples, and if there's something that needs updating, please let us know.

> And, have a task-based list: for instance: "how to make a payment from your website to a particular person" or "how to make a mass-pay to many persons from your web-site."

This is a great suggestion, and I'll see if I can get this added to the wiki.  Also remember that with this being an open source project, you're more than welcome to contribute any improvements you think might be helpful to others.

I'll keep this issue open as an enhancement request for the SDK concerning its documentation; however, if it tuns into simply bashing the documentation and samples presented here, then I'll close this issue.

*Please continue to use this thread to highlight the specific use cases you'd like to see fully explained.*

**Comment by gidmeister** [comment]
Thank you.  Right now, I am looking into how to make a payment from my website to a user who uses the website, in return for the user providing a service (the service would be commenting on videos).  So I looked at the REST API document, and found one call that seems promising: "Create a Payment".  The reason I use the word "seems" is that it requires a URL that Paypal goes back to on my own website - its not just an asynchronous call to Paypal that the user does not even notice.  I've am also looking at how to authenticate with PayPal using an OAuth access token (this would be in the SDK).   So after looking at all this, I would think I would have to combine the two together somehow, and information on how to do this might be in the samples.  I did not compile the sample and run it - maybe that is the way to go.  Perhaps the sample has a list of operations that I would recognize and be able to copy and paste (with modifications), into my project.  I will look at that.  But just from my description, you can see the hurdles that a newbie faces when trying out a simple operation.

**Comment by gidmeister** [comment]
Another hurdle: I go to paypal-net-sdk-master/source, and find 3 solution files.  I assume they are for the same project, but different net frameworks.  When I try them, I get a message that I cannot run a class.  (in other words, they are not 'exe' projects, but just dll or class projects).  So I can't run the samples.
Thanks.

**Comment by jziaja** [comment]
This is great feedback. :)  If you're confused about how to start using the SDK, then your best option is to follow the [Getting Started](https://github.com/paypal/PayPal-NET-SDK/wiki#getting-started) instructions.  It goes over how to get the SDK setup and begin using it.  

It should be noted that the wiki portion of this repo is something that was added very recently.  So if there are pages or sections that need more elaboration or better examples, definitely let me know.

Once you have your project setup to use the SDK, you're ready to begin testing out some PayPal transactions with your sandbox credentials.  This is where the samples come in very handy.  As you mentioned, they are intended for you to modify and play around with to accomplish whatever it is that you need to accomplish.  Then, it should be as simple as copy/pasting the code from the sample into your project.  The samples have grown organically over time as our team has found more use cases that developers encounter and report to us.

Taking your feedback into account, it sounds like it may be worthwhile to link the wiki page [Making Your First Call](https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call) directly from the main readme, as that specifically goes over how to get the OAuth access token and begin making API calls using the SDK.

**Comment by gidmeister** [comment]
I now go to the samples folder and try opening the project there with Visual Studio Express 2013 for Desktop:.  It tries to migrate the project.   I get this error message:
Migration Report - 

 Source\PayPal.SDK.Sample.VS.2013.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=349c5851-65df-11da-9384-00065b846f21

**Comment by gidmeister** [comment]
I just saw your follow up comment ("great feedback").  I'll try your suggestions there.

**Comment by jziaja** [comment]
I'm not overly familiar with the Express versions of Visual Studio, but it sounds like you may need to either install [Visual Studio Express 2013 for Web](http://www.asp.net/vwd) or get [Visual Studio Community 2013](https://www.visualstudio.com/products/visual-studio-community-vs).  Between the two, I'd recommend Visual Studio Community 2013 as it provides more flexibility with the types of projects it supports.  The sample projects are all web applications, as this SDK is intended to be used for server environments and not mobile apps.

**Comment by gidmeister** [comment]
For some reason I thought the solution files were meant to be run as a VS project, not a Web project.  I tried them with VS Express for web, and that does work.  
It shows a list of operations, and that raises a question:
What is the difference between a payment and a payout?
Thanks.

**Comment by jziaja** [comment]
> What is the difference between a payment and payout?

One of the big differences between the two is that payments are typically used in context of an exchange of goods or services (e.g. when a customer wants to buy something from your website); whereas a payout is typically used for sending money to one ore more recipients (e.g. a site can send payouts to affiliates for referrals).

For more in-depth information, I'd recommend taking a look at the documentation on the PayPal Developer site:
* [Payments](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/)

  > The Payments API provides an easy and secure way to accept online and mobile payments. You can take advantage of all the great benefits of PayPal while enabling customers to make payments with only a few clicks.

* [Payouts](https://developer.paypal.com/docs/integration/direct/payouts-overview/) (I'd also recommend reading the linked [Mass Payment](https://developer.paypal.com/docs/classic/mass-pay/integration-guide/MassPayOverview/) overview, as it does a slightly better job of defining what exactly it does)

  > The Payout API enables you to send up to 500 disbursements in one API call to any email address or US mobile phone number. The Payouts API lets you easily send, track, and search for your previously made payouts.

If you need more clarification on the differences or need more help with respect to what each service has to offer, I'd recommend contacting [PayPal Customer Support](https://www.paypal.com/us/webapps/helpcenter/helphub/home/) directly as they can quickly provide you with the information you need.

**Comment by gidmeister** [comment]
I don't want to keep changing topics, but I took the sample and tried to convert it to VB, so that it would fit in with my current VB website.  There is one section of code that I have doubts about translating because I don't know if JSON is needed.  Can I just make a class called PayoutItem to make this work?:
  ' items = new List<PayoutItem>
        '        {
        '            new PayoutItem
        '            {
        '                recipient_type = PayoutRecipientType.EMAIL,
        'Amount = New Currency
        '                {
        '                    value = "0.99",
        'Currency = "USD"
        '                },
        '                receiver = "shirt-supplier-one@mail.com",
        '                note = "Thank you.",
        'sender_item_id = "item_1"
        '            },

        '        }
        '    };

**Comment by jziaja** [comment]
@gidmeister, I'd recommend reaching out to the friendly developer community over on [StackOverflow](http://stackoverflow.com/) with that question.  They can help to show you the best way for converting C# syntax to VB.  I'll be honest in that I'm not overly familiar with whether or not VB allows for inline object instantiation like how the C# code is written.

**Comment by jziaja** [comment]
Closing this issue as the documentation has since been updated.  If you have any other documentation feedback, please feel free to open a new issue explaining where things need to be improved.  Thanks again for the feedback!
