### ISSUE TITLE
converting samples to vb.net

### ISSUE THREAD

**Issue by gidmeister** [paypal/PayPal-NET-SDK#91]
I tried to convert the batch payout sample to vb.net, and I get 2 errors.
Those are:
1)
Value of type 'PayPal.APIContext' cannot be converted to 'PayPal.Api.APIContext'.
2)
'Public Sub AddNewRequest(title As String, [requestObject As PayPal.Api.IPayPalSerializableObject = Nothing], [description As String = ""])' is declared in project 'App_SubCode_CSCode.frmz3wkl.dll', which is not referenced by project '6_zOwner_CreatePayout.aspx'. Add a reference to 'App_SubCode_CSCode.frmz3wkl.dll' to your project '6_zOwner_CreatePayout.aspx'.

Is there any help you can give on this?  Why would there be two types of APIContext?  Also, since I did use Nuget to add the paypal net sdk to my project, why would I get the second error (which says that I have to add a reference).  The line that prompted the second error was:
  Me.flow.AddNewRequest("Create payout", payout)
and the line that prompted the first error was:
 Dim createdPayout = payout.Create(apiContext, False)

**Comment by jziaja** [comment]
Which NuGet package(s) did you pull into your project?  `APIContext` is defined in the `PayPal.Api` namespace to avoid a namespace conflict with the older Core SDK (which was integrated into this SDK with the v1.0 release).

**Comment by gidmeister** [comment]
Over time, I put in the "Paypal Merchant SDK" the "Paypal NET SDK", and I also have a class called 'Paypal' from earlier work.  I should probably delete absolutely any file that starts with the word 'Paypal' and try to reload only this SDK.  I'll keep you posted if that works.

**Comment by gidmeister** [comment]
I'm getting nowhere.  But here is another approach.  I could retain every single file in the samples project, but modify them so they take arguments.  I mean that for instance with the "PayoutCreate" sample, I would modify it to take an array that I pass, so it creates a payout based on that array.  Then I recompile the whole thing.  So my question is: Is it as simple as:
1 copying the 'samples' folder (only) to my web project in a special C# subfolder in the app_code folder
2. modifying the C# code to take arguments
3. using Nuget to install the paypal NET SDK
4. calling the C# code from my VB routines?
Or is there more to it?
Thanks,

**Comment by jziaja** [comment]
That plan should work; however, I'm curious as to why the VB code to create the Payouts objects and call the Payouts interface on the SDK wasn't working.  Is the code you posted [here](https://github.com/paypal/PayPal-NET-SDK/issues/90#issuecomment-93032267) the part that wasn't working or are you encountering a different problem?

**Comment by gidmeister** [comment]
The code that isn't working is the sample that Creates a payout.  I converted that to VB, and then I had to convert the page class that it inherits into VB, etc.  If you want to try and duplicate the problem I'm having, I can create a project for you and zip it up and upload it to skydrive.  
-- Gideon

**Comment by jziaja** [comment]
Can you share the code here that creates the Payout?  By "isn't working" do you mean you're getting a compilation error or an error returned from the API?

**Comment by gidmeister** [comment]
I get compilation errors  so that I can't get to the run and test stage.

Here are 2 pages (the baseSamplePage is  needed for the createPayout page).  I used nuget to add the paypal net sdk, and the way I got the samples CS files to merge with my VB project was to create a special subfolder called CsCode in my APP_CODE folder, and then in my web.config, I put the following:
    <compilation debug="true" strict="false" explicit="true" targetFramework="4.5">
      <codeSubDirectories>
        <add directoryName="CSCode" />
      </codeSubDirectories>
    </compilation>
' ===============FIRST FILE (BaseSamplePage)
Imports Microsoft.VisualBasic
Imports PayPal.Api
Imports PayPal.Sample.Utilities
Imports System.Collections.Generic
Imports System.Linq
Imports System.Web

Public MustInherit Class BaseSamplePage
    Inherits System.Web.UI.Page

    Protected flow As RequestFlow

    Protected Sub Page_Load(sender As Object, e As EventArgs)
        ' Call this so the request/response flow is recorded and displayed properly.
        Me.RegisterSampleRequestFlow()
        Try
            Me.RunSample()
        Catch ex As Exception
            Me.flow.RecordException(ex)
        End Try
        Server.Transfer("~/Response.aspx")
    End Sub

    ''' <summary>
    ''' Primary method where each sample page should run their sample code.
    ''' </summary>
    Protected MustOverride Sub RunSample()

    Protected Sub RegisterSampleRequestFlow()
        If Me.flow Is Nothing Then
            Me.flow = New RequestFlow()
        End If
        HttpContext.Current.Items("Flow") = Me.flow
    End Sub
End Class
    
'=======================================================
Second page:
Imports System.Collections.Generic
Imports PayPal.Api
Partial Class zOwner_CreatePayout
    Inherits BaseSamplePage


    ' # Create Batch Payout
    ' This sample code demonstrates how you can create a batch payout.
    ' More Information: https://developer.paypal.com/docs/integration/direct/payouts-overview/


    Protected Overrides Sub RunSample()
        ' ### Api Context
        ' Pass in a `APIContext` object to authenticate 
        ' the call and to send a unique request id 
        ' (that ensures idempotency). The SDK generates
        ' a request id if you do not pass one explicitly. 
        ' See [Configuration.cs](/Source/Configuration.html) to know more about APIContext.
        Dim apiContext = PayPal.Sample.Configuration.GetAPIContext()

        ' ### Initialize `Payout` Object
        ' Initialize a new `Payout` object with details of the batch payout to be created.
        ' #### sender_batch_header
        ' Describes how the payments defined in the `items` array are to be handled.
        ' #### items
        ' The `items` array contains the list of payout items to be included in this payout.
        ' If `syncMode` is set to `true` when calling `Payout.Create()`, then the `items` array must only
        ' contain **one** item.  If `syncMode` is set to `false` when calling `Payout.Create()`, then the `items`
        ' array can contain more than one item.
        ' ==================
        ' items = new List<PayoutItem>
        '        {
        '            new PayoutItem
        '            {
        '                recipient_type = PayoutRecipientType.EMAIL,
        'Amount = New Currency
        '                {
        '                    value = "0.99",
        'Currency = "USD"
        '                },
        '                receiver = "shirt-supplier-one@mail.com",
        '                note = "Thank you.",
        'sender_item_id = "item_1"
        '            },

        '        }
        '    };
        ' ================
        Dim payout = New Payout() With { _
             .sender_batch_header = New PayoutSenderBatchHeader() With { _
                 .sender_batch_id = "batch_" + System.Guid.NewGuid().ToString().Substring(0, 8), _
                 .email_subject = "You have a payment" _
            }, _
         .items = New List(Of PayoutItem)({ _
                New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = "0.99", _
                          .currency = "USD" _
                    }, _
                      .receiver = "shirt-supplier-one@mail.com", _
                      .note = "Thank you.", _
                      .sender_item_id = "item_1" _
                }, _
                New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = "0.90", _
                          .currency = "USD" _
                    }, _
                      .receiver = "shirt-supplier-two@mail.com", _
                      .note = "Thank you.", _
                      .sender_item_id = "item_2" _
                }, _
                New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = "2.00", _
                          .currency = "USD" _
                    }, _
                      .receiver = "shirt-supplier-three@mail.com", _
                      .note = "Thank you.", _
                      .sender_item_id = "item_3" _
                } _
            }) _
        }

        ' ^ Ignore workflow code segment
        '#Region "Track Workflow"
        Me.flow.AddNewRequest("Create payout", payout)
        '#End Region

        ' ### Payout.Create()
        ' Creates the batch payout resource.
        ' `syncMode = false` indicates that this call will be performed **asynchronously**,
        ' and will return a `payout_batch_id` that can be used to check the status of the payouts in the batch.
        ' `syncMode = true` indicates that this call will be performed **synchronously** and will return once the payout has been processed.
        ' > **NOTE**: The `items` array can only have **one** item if `syncMode` is set to `true`.
        Dim createdPayout = payout.Create(apiContext, False)

        ' ^ Ignore workflow code segment
        '#Region "Track Workflow"
        Me.flow.RecordResponse(createdPayout)
        '#End Region

        ' For more information, please visit [PayPal Developer REST API Reference](https://developer.paypal.com/docs/api/).
    End Sub
End Class

'=======================================================

**Comment by gidmeister** [comment]
The web.config code had angle brackets and did not appear in the comment, so I'm putting it here   
 [compilation debug="true" strict="false" explicit="true" targetFramework="4.5"]
      [codeSubDirectories]
        [add directoryName="CSCode" /]
      [/codeSubDirectories]
    
    [/compilation]

**Comment by jziaja** [comment]
I updated your previous comment with Markdown formatting.  By default, Markdown assumes you're embedding HTML if you include raw tags.  You can always surround code elements with backticks (`` ` ``) to have them appear inline with text, or you can flag code blocks by surrounding them with a series of backticks.  Feel free to preview your previous comment to see how to do that. :)

[Daring Fireball](http://daringfireball.net/projects/markdown/syntax) provides a great resource for Markdown syntax.

----

Concerning the sample code, [BaseSamplePage.cs](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/BaseSamplePage.cs) is intended to allow for the recording of the request & response flows when running each sample.  Therefore, if you choose to copy a sample's code over to your application, all you need is what is in the [PayoutCreate.aspx.cs](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/PayoutCreate.aspx.cs#L12) page's `RunSample()` method.

Also, in the `RunSample()` method, the code segments that are surrounded with _"^ Ignore workflow code segment"_ are parts where the sample is recording what is happening.  These parts too can be removed.  In an upcoming release I'll be adding HTTP events a caller can listen to, if desired, which will remove the need to have these code bits littered throughout the samples. :)

These notes about code specific to recording the flows in the samples don't appear to be documented anywhere, so I'll get them added as a disclaimer at the top of each sample file.

Once I removed all the unneeeded code and fixed the code that creates the `APIContext` object to be used ([described here](https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call#1-authenticate-with-paypal), albeit in C#), I was then able to get it to compile and create a payout successfully.

Here's the modified VB code for the _CreatePayout_ page:

````vb
Imports PayPal.Api

Public Class CreatePayout
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        ' Initialize an APIContext object with a fresh access token.
        ' The config will be populated with values set in the Web.config file.
        Dim config = ConfigManager.Instance.GetProperties()
        Dim accessToken = New OAuthTokenCredential(config).GetAccessToken()
        Dim apiContext = New APIContext(accessToken)

        ' Initialize Payout object
        Dim payout = New Payout() With { _
             .sender_batch_header = New PayoutSenderBatchHeader() With { _
                 .sender_batch_id = "batch_" + System.Guid.NewGuid().ToString().Substring(0, 8), _
                 .email_subject = "You have a payment" _
            }, _
         .items = New List(Of PayoutItem)({ _
                New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = "0.99", _
                          .currency = "USD" _
                    }, _
                      .receiver = "shirt-supplier-one@mail.com", _
                      .note = "Thank you.", _
                      .sender_item_id = "item_1" _
                }, _
                New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = "0.90", _
                          .currency = "USD" _
                    }, _
                      .receiver = "shirt-supplier-two@mail.com", _
                      .note = "Thank you.", _
                      .sender_item_id = "item_2" _
                }, _
                New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = "2.00", _
                          .currency = "USD" _
                    }, _
                      .receiver = "shirt-supplier-three@mail.com", _
                      .note = "Thank you.", _
                      .sender_item_id = "item_3" _
                } _
            }) _
        }

        ' Create the payout
        Dim createdPayout = payout.Create(apiContext, False)
    End Sub

End Class
````

This code assumes you've updated your project's **Web.config** file with the appropriate PayPal settings:

````xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  http://go.microsoft.com/fwlink/?LinkId=169433
  -->
<configuration>
  <configSections>
    <!-- ... -->
    <section name="paypal" type="PayPal.SDKConfigHandler, PayPal" />
  </configSections>
  
  <!-- ... -->

  <!-- PayPal SDK settings -->
  <paypal>
    <settings>
      <add name="mode" value="sandbox"/>
      <add name="connectionTimeout" value="360000"/>
      <add name="requestRetries" value="1"/>
      <add name="clientId" value="AUASNhD7YM7dc5Wmc5YE9pEsC0o4eVOyYWO9ezXWBu2XTc63d3Au_s9c-v-U"/>
      <add name="clientSecret" value="EBq0TRAE-4R9kgCDKzVh09sm1TeNcuY-xJirid7LNtheUh5t5vlOhR0XSHt3"/>
    </settings>
  </paypal>
  
  <!-- ... -->
  
</configuration>
````

**NOTE:** The `clientId` and `clientSecret` are both set to the sandbox credentials used in the sample app.  You'll want to change these to your own application's credentials.

**Comment by gidmeister** [comment]
Thanks!

**Comment by Greesemonkey3** [comment]
@jziaja I was wondering if you had any sample asp .net VB code for Requesting a payment, processing it, and redirecting. I have been looking at your C# code but am unable to translate the part about creating & executing a payment request. Any help or advice would be greatly appriciated!
