### ISSUE TITLE
Null reference exception thrown when making SDK call with APIContext object with null Config property

### ISSUE THREAD

**Issue by gidmeister** [paypal/PayPal-NET-SDK#94]
I make a VB project and used Nuget to link to "Paypal NET SDK".  Then I put in the web.config settings as follows:
````xml
<?xml version="1.0"?>
<configuration>
   <configSections>
         <section name="paypal" type="PayPal.SDKConfigHandler, PayPal" />
  </configSections>
    <system.web>
      <compilation debug="true" strict="false" explicit="true" targetFramework="4.5" />
      <httpRuntime targetFramework="4.5" />  
    </system.web>
 <paypal>
      <settings>
        <add name="mode" value="sandbox"/>
        <add name="connectionTimeout" value="360000"/>
        <add name="requestRetries" value="1"/>
        <add name="clientId" value="AZDacL-onsbcZpBV5bQnC" />
        <add name="clientSecret" value="EBjM7aEmpkm"/>
      </settings>
    </paypal>  
</configuration>
````
This most definitely does not compile.  It does not know what the paypal section (above) is.  It says "could not find schema information for the element 'paypal' ".  Am I missing something?

**Comment by gidmeister** [comment]
another try, my project does not compile with this web.config.  I did use NuGet to install the Paypal NET SDK in the project.
   <?xml version="1.0"?> 
    <configuration> 
    <configSections> 
    <section name="paypal" type="PayPal.SDKConfigHandler, PayPal" /> 
    </configSections> 
    <system.web> 
    <compilation debug="true" strict="false" explicit="true" targetFramework="4.5" /> 
    <httpRuntime targetFramework="4.5" /> 
    </system.web> 
    <paypal> 
    <settings> 
    <add name="mode" value="sandbox"/> 
    <add name="connectionTimeout" value="360000"/> 
    <add name="requestRetries" value="1"/> 
    <add name="clientId" value="AZDacLIOBs15bQnC" /> 
    <add name="clientSecret" value="EBjM7aEmpkmrhofk48S4uoIhTBd"/> 
    </settings> 
    </paypal> 
     
    </configuration>

**Comment by gidmeister** [comment]
Is there no way to delete erroneous comments?  Anyway, here is another try:
    [?xml version="1.0"?] 
    [configuration] 
    [configSections] 
    [section name="paypal" type="PayPal.SDKConfigHandler, PayPal" /] 
    [/configSections] 
    [system.web] 
    [compilation debug="true" strict="false" explicit="true" targetFramework="4.5" /] 
    [httpRuntime targetFramework="4.5" /] 
    [/system.web] 
    [paypal] 
    [settings] 
    [add name="mode" value="sandbox"/] 
    [add name="connectionTimeout" value="360000"/] 
    [add name="requestRetries" value="1"/] 
    [add name="clientId" value="AZDacLIOBs15bQnC" /] 
    [add name="clientSecret" value="EBjM7aEmpkmrhofk48S4uoIhTBd"/] 
    [/settings] 
    [/paypal] 
     
    [/configuration]
 You mentioned earlier some markdown source, but I wasn't able to see it.

**Comment by jziaja** [comment]
_(Cleaned up your markdown.  When you create an issue, you can also preview it beforehand to make sure everything is displayed properly.  For code markdown, you can also refer to the [Mastering Markdown - GitHub Guide](https://guides.github.com/features/mastering-markdown/) page, which has examples of how to post code blocks.)_

What version of VS Express are you using?  Can you share the SDK calls you're making in the code?  I just tested your web.config with a new VB ASP.NET project in Visual Studio Express 2013, and it was able to compile and run without any error.

**Comment by gidmeister2** [comment]
I am able to compile it now.  VS 2013 was giving errors in the web.config even though the error was located in my code.  The web.config was fine.  Now I can run it, but I get an error :

PayPal.PayPalException was unhandled by user code   HResult=-2146233088   Message=Object reference not set to an instance of an object.

The line that gives that error is:

Dim createdPayout = payout.Create(apiContext, False) 

 Why would this happen?  The entire code is below, I should explain that I'm passing an array that I filled in my own code with emails and other information, and then transferring it into a structure that the Paypal library itself has.  Here is the code that fails.

```VB
Public Shared Sub PayThruTheNose(ByVal passedArray() As passPayout, ByRef email_subject_arg As String)

        ' Initialize an APIContext object with a fresh access token.
        ' The config will be populated with values set in the Web.config file.
        ' email_subject might be "You have a payment"
        Dim config = ConfigManager.Instance.GetProperties()
        Dim accessToken = New OAuthTokenCredential(config).GetAccessToken()
        Dim apiContext = New APIContext(accessToken)
        Dim i As Integer

        ' Initialize Payout object
        Dim payout As PayPal.Api.Payout = New Payout() With { _
             .sender_batch_header = New PayoutSenderBatchHeader() With { _
                 .sender_batch_id = "batch_" + System.Guid.NewGuid().ToString().Substring(0, 8), _
                 .email_subject = email_subject_arg _
            }, _
         .items = New List(Of PayoutItem)
         }


        With payout.items
            For i = 0 To passedArray.Length - 1
                .Add(New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = passedArray(i).amountvalue, _
                          .currency = "USD" _
                    }, _
                      .receiver = passedArray(i).receiverEmail, _
                      .note = passedArray(i).note, _
                      .sender_item_id = passedArray(i).senderItemID _
                })
            Next
        End With


        ' Create the payout
        Dim createdPayout = payout.Create(apiContext, False)
    End Sub

**Comment by jziaja** [comment]
Thanks for sharing your code, @gidmeister / @gidmeister2 .  I was able to reproduce this, and it appears to be caused from the `APIContext` object not having its `Config` property set.  This is a bug with the SDK as it should pickup the settings from the web.config if no config is provided.  I'll get this fixed in the next release.

For the time being, you can work around this issue by adding the following line to your code when creating the `APIContext` object:

````vb
' Initialize an APIContext object with a fresh access token.
 ' The config will be populated with values set in the Web.config file.
' email_subject might be "You have a payment"
Dim config = ConfigManager.Instance.GetProperties()
Dim accessToken = New OAuthTokenCredential(config).GetAccessToken()
Dim apiContext = New APIContext(accessToken)
apiContext.Config = config
````

Let me know if you run into any other issues.

**Comment by gidmeister2** [comment]
I am running into another issue.  I ran the code, and then I checked the sandbox to see if the users who were paid were notified, and they received no notifications today.  I have to look into this further.

**Comment by gidmeister2** [comment]
Jason,
Thanks for the workaround with the apiContext.config:
I have the code running now, but I find that the users in the “sandbox” do not get notified of the payment.  This may not be a problem with the code at all, but I’m pasting the whole code here, and perhaps you may have an idea.  I also posted a brief comment on github.

Imports Microsoft.VisualBasic
Imports PayPal.Api
Imports System.Collections.Generic
Partial Class _Default
    Inherits System.Web.UI.Page

    Protected Sub Button1_Click(sender As Object, e As System.EventArgs) Handles Button1.Click
        Dim theDate As Date
        theDate = Date.Today
        Dim email_subject As String = "refund to misers"
        Dim passedArray(1) As passPayout
        With passedArray(0)
            .amountvalue = 123.45
            .receiverEmail = "johnDenver@gmail.com"
            .note = "thank you for 'Rocky Mountain High'"
            .senderItemID = "refund on 5/6/2010"

        End With
        With passedArray(1)
            .amountvalue = 543.21
            .receiverEmail = "candace@pert.com"
            .note = "thanks for 'Endorphins'"
            .senderItemID = "refund on " & theDate.ToString("d")
        End With
        Dim errmsg As String = ""
        PayThruTheNose(passedArray, email_subject, errmsg)
        Me.LabelResult.Text = "SUCCESS"
    End Sub
    Public Structure passPayout
        Dim amountvalue As Double ' 2.00
        Dim receiverEmail As String ' johnDenver@gmail.com
        Dim note As String ' thank you for 'Rocky Mountain High'
        Dim senderItemID As String 'item 3'
    End Structure

    Protected Function PayThruTheNose(ByVal passedArray() As passPayout, ByRef email_subject_arg As String, ByRef errmsg As String) As Boolean
        Dim i As Integer
        errmsg = ""
        If passedArray.Length = 0 Then
            errmsg = "Error, you have an empty array of items to pay for."
            Return False
        End If
        For i = 0 To passedArray.Length - 1
            If passedArray(i).senderItemID.Length > 30 Then
                errmsg = "Error, you have a sender item ID that is over 30 characters.  This is the item ID: " & passedArray(i).senderItemID
                Return False
            End If
            If passedArray(i).note.Length > 30 Then
                errmsg = "Error, you have a note (email subject) that is over 30 characters.  This is the note: " & passedArray(i).note
                Return False
            End If
        Next
        ' Initialize an APIContext object with a fresh access token.
        ' The config will be populated with values set in the Web.config file.
        ' email_subject might be "You have a payment"
        Dim config = ConfigManager.Instance.GetProperties()
        Dim accessToken = New OAuthTokenCredential(config).GetAccessToken()
        Dim apiContext = New APIContext(accessToken)
        apiContext.Config = config


        ' Initialize Payout object
        Dim payout As PayPal.Api.Payout = New Payout() With { _
             .sender_batch_header = New PayoutSenderBatchHeader() With { _
                 .sender_batch_id = "batch_" + System.Guid.NewGuid().ToString().Substring(0, 8), _
                 .email_subject = email_subject_arg _
            }, _
         .items = New List(Of PayoutItem)
         }


        With payout.items
            For i = 0 To passedArray.Length - 1
                .Add(New PayoutItem() With { _
                      .recipient_type = PayoutRecipientType.EMAIL, _
                      .amount = New Currency() With { _
                          .value = passedArray(i).amountvalue, _
                          .currency = "USD" _
                    }, _
                      .receiver = passedArray(i).receiverEmail, _
                      .note = passedArray(i).note, _
                      .sender_item_id = passedArray(i).senderItemID _
                })
            Next
        End With


        ' Create the payout
        Dim createdPayout = payout.Create(apiContext, False)
        Return True
    End Function
End Class
Thanks,
Gideon Isaac

**Comment by tomwhipple** [comment]
@gidmeister2 EMail notifications are suppressed in sandbox, though you can check the [notifications section of developer.paypal.com](https://developer.paypal.com/developer/notifications) to see what is sent by the REST API.
