### ISSUE TITLE
is mass pay done with payout code (just with very large array)?

### ISSUE THREAD

**Issue by gidmeister2** [paypal/PayPal-NET-SDK#98]
I have your payout code working nicely, but I was wondering - is a "mass pay" done with that code, just using a very large array of addresses?  Will Paypal "understand" that this is a "mass pay" and allow the 250 (or whatever the limit is) people to be paid, with just one transaction fee for the bunch?
Thanks.

**Comment by jziaja** [comment]
Yes, the Payouts API is the REST version of the classic Mass Payments service.  By creating a batch payout, you are effectively sending out a mass payment.  The transaction fee structure is outlined on the [Payouts Overview](https://developer.paypal.com/docs/integration/direct/payouts-overview/) developer doc page.  If you have any other questions specific to the transaction fees and how they are handled, please contact [PayPal Customer Support](https://www.paypal.com/us/webapps/helpcenter/helphub/home/).
