### ISSUE TITLE
Do you use strong types or just objects?

### ISSUE THREAD

**Issue by gidmeister2** [paypal/PayPal-NET-SDK#99]
I put in the following code to get details on a payout - to find whether it was successful, for instance.  But since I have 'payout' here as an object, I can't read any of its fields.  Is there a better declaration than 'as object' that I can use here?
Thanks:
```VB
 Public Shared Sub GetMassPayBatchDetails(ByRef payoutBatchID As String, ByRef payout As Object)
        Dim config = ConfigManager.Instance.GetProperties()
        Dim accessToken = New OAuthTokenCredential(config).GetAccessToken()
        Dim apiContext = New APIContext(accessToken)
        apiContext.Config = config


        payout = payout.Get(apiContext, payoutBatchID)
    End Sub

**Comment by jziaja** [comment]
`Payout.Get(...)` returns a [`PayoutBatch`](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Payout.cs#L71) type.  Try using `PayoutBatch` instead of `Object` for the `payout` type in your method signature.
